# EHR Pipeline Benchmark on MIMIC-III-Ext-Notes

Benchmarks the `ehr_pipeline` package on real MIMIC-III clinical notes joined with the matching structured EHR.

Inputs:
- `datasets/mimic-iii-ext-notes-1.0.0/notes.csv` — 150 deidentified clinical notes (`row_id`, `subject_id`, `hadm_id`, `text`).
- `datasets/mimic-iii-ext-notes-1.0.0/labels.csv` — 2,288 expert-annotated clinical concepts per note, used as the **gold entity set** (filtered to `detection=yes`, `encounter=yes`, `negation=no`).
- `datasets/bquxjob_5dbe3bd2_19dae30f3cf.json` — structured EHR (diagnoses + procedures) per `hadm_id`. 130 of 130 unique note `hadm_id`s match.

Per case the notebook:
1. Materializes a FHIR R4 Bundle from the structured EHR and writes the **real** clinical note text to disk.
2. Runs the 8-stage pipeline (the context agent / stage 4 is **disabled** by default for benchmarking — `ENABLE_CONTEXT_AGENT`).
3. Builds a deterministic reference summary from gold concepts + structured EHR fields.
4. Scores the generated Markdown against the reference with **ROUGE-1/2/L**, **BERTScore P/R/F1**, **entity precision / recall / F1**, and reports the achieved **compression ratio** vs the 0.20–0.30 target.

Setup: `pip install -r requirements-bench.txt`. The pipeline reads `OLLAMA_API_KEY` and `OLLAMA_HOST` from `.env`.

In [9]:
import importlib
import logging
import sys
import warnings
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
warnings.filterwarnings("ignore", category=FutureWarning)

# Force-reload every ehr_pipeline submodule so stale model names are never used.
# Re-run this cell if you edit config.py, prompts.py, or any stage file.
import ehr_pipeline.config
import ehr_pipeline.prompts
import ehr_pipeline.ollama_client
import ehr_pipeline.schemas
import ehr_pipeline.evidence_store
import ehr_pipeline.runtime
import ehr_pipeline.stages.s1_evidence
import ehr_pipeline.stages.s2_extract
import ehr_pipeline.stages.s3_verify
import ehr_pipeline.stages.s4_context
import ehr_pipeline.stages.s5_fact_sheet
import ehr_pipeline.stages.s6_summarize
import ehr_pipeline.stages.s7_check
import ehr_pipeline.stages.s8_review
import ehr_pipeline.extraction
import ehr_pipeline.verification
import ehr_pipeline.pipeline
import benchmarks.mimic
import benchmarks.metrics

for _mod in [
    ehr_pipeline.config, ehr_pipeline.prompts, ehr_pipeline.ollama_client,
    ehr_pipeline.schemas, ehr_pipeline.evidence_store, ehr_pipeline.runtime,
    ehr_pipeline.stages.s1_evidence, ehr_pipeline.stages.s2_extract,
    ehr_pipeline.stages.s3_verify, ehr_pipeline.stages.s4_context,
    ehr_pipeline.stages.s5_fact_sheet, ehr_pipeline.stages.s6_summarize,
    ehr_pipeline.stages.s7_check, ehr_pipeline.stages.s8_review,
    ehr_pipeline.extraction, ehr_pipeline.verification, ehr_pipeline.pipeline,
    benchmarks.mimic, benchmarks.metrics,
]:
    importlib.reload(_mod)

from ehr_pipeline import config as pipeline_config
from ehr_pipeline.pipeline import run_pipeline
from benchmarks import mimic, metrics

print("project root:", PROJECT_ROOT)
print("models:")
for k, v in vars(pipeline_config.MODELS).items():
    print(f"  {k}: {v}")
print("ollama host:", pipeline_config.OLLAMA_HOST)
print("api key set:", bool(pipeline_config.OLLAMA_API_KEY))

project root: /Users/natejly/Desktop/LLMS's FInal
models:
  claim_extraction: gemma3:27b
  claim_verification: gemma3:27b
  context_agent: gemma3:27b
  summary_generation: gemma4:31b
  final_review: gemma3:27b
ollama host: https://ollama.com
api key set: True

## Configuration

In [10]:
EHR_JSON_PATH = PROJECT_ROOT / "datasets" / "bquxjob_5dbe3bd2_19dae30f3cf.json"
NOTES_CSV_PATH = PROJECT_ROOT / "datasets" / "mimic-iii-ext-notes-1.0.0" / "notes.csv"
LABELS_CSV_PATH = PROJECT_ROOT / "datasets" / "mimic-iii-ext-notes-1.0.0" / "labels.csv"

BENCH_DIR = PROJECT_ROOT / "outputs" / "_bench"
BENCH_DIR.mkdir(parents=True, exist_ok=True)

NUM_CASES = 10
RANDOM_SEED = 7
ALLOW_VIOLATIONS = True       # don't drop a case just because the deterministic check found something
RESUME = True                 # reuse cached stage outputs across re-runs
ENABLE_CONTEXT_AGENT = False  # skip stage 4 in benchmark mode
SUMMARY_MIN_RATIO = 0.20
SUMMARY_MAX_RATIO = 0.30
BERTSCORE_MODEL = "roberta-large"

# Ollama: if OLLAMA_HOST is http://localhost:11434, do NOT send OLLAMA_API_KEY
# in the Authorization header (local Ollama returns 401). Keys are only used
# when OLLAMA_HOST=https://ollama.com unless you set OLLAMA_SEND_BEARER_TO_LOCAL=1.

print("work dir:", BENCH_DIR)
print("context agent:", "ON" if ENABLE_CONTEXT_AGENT else "OFF")
print(f"compression target: {SUMMARY_MIN_RATIO:.0%}-{SUMMARY_MAX_RATIO:.0%}")

work dir: /Users/natejly/Desktop/LLMS's FInal/outputs/_bench
context agent: OFF
compression target: 20%-30%

## Load and sample real cases (notes joined with structured EHR)

In [11]:
import random

all_cases = mimic.load_real_cases(
    ehr_json_path=EHR_JSON_PATH,
    notes_csv_path=NOTES_CSV_PATH,
    labels_csv_path=LABELS_CSV_PATH,
)
print(f"loaded {len(all_cases)} cases (notes joined with EHR by hadm_id)")

rng = random.Random(RANDOM_SEED)
sampled = rng.sample(all_cases, k=min(NUM_CASES, len(all_cases)))
for c in sampled:
    print(
        f"  {c.case_id:36s}  note_chars={len(c.note_text):5d}  "
        f"gold_concepts={len(c.gold_concepts):3d}  "
        f"diags={len(c.admission.get('all_diagnoses') or []):3d}  "
        f"procs={len(c.admission.get('all_procedures') or []):3d}"
    )

loaded 150 cases (notes joined with EHR by hadm_id)
  mimic-72907-165405-520384             note_chars= 3404  gold_concepts=  9  diags= 18  procs= 16
  mimic-29307-175627-318233             note_chars=  784  gold_concepts=  7  diags= 14  procs=  4
  mimic-47927-161682-717576             note_chars= 2592  gold_concepts=  7  diags= 18  procs=  5
  mimic-77013-141363-444743             note_chars= 2827  gold_concepts=  7  diags= 44  procs= 28
  mimic-54229-165594-598031             note_chars= 2337  gold_concepts=  9  diags= 48  procs= 16
  mimic-17539-153621-390912             note_chars= 4686  gold_concepts=  5  diags= 22  procs= 10
  mimic-85464-164726-466035             note_chars= 3032  gold_concepts=  9  diags= 34  procs=  6
  mimic-79877-185698-417636             note_chars= 1836  gold_concepts=  8  diags= 14  procs= 10
  mimic-92277-173474-1282               note_chars=16139  gold_concepts= 20  diags= 18  procs=  5
  mimic-94229-146659-541449             note_chars= 2700  gold_concepts=  6  diags= 35  procs=  9

## Materialize FHIR + notes and run the pipeline

In [12]:
import traceback

from ehr_pipeline.ollama_client import OllamaError

# Reset the Ollama client singleton so any config/env changes take effect.
from ehr_pipeline import ollama_client as _oc
_oc._client = None
_oc._client_fingerprint = None

# Stage labels for the debug table (format placeholders filled at runtime).
_STAGE_LABELS = {
    "stage1_evidence":   "S1  Evidence store      [deterministic]",
    "stage2_extract":    "S2  Claim extraction    [LLM: {claim_extraction}]",
    "stage3_verify":     "S3  Claim verification  [LLM: {claim_verification}]",
    "stage4_context":    "S4  Context agent       [LLM: {context_agent}]",
    "stage5_fact_sheet": "S5  Fact sheet          [deterministic]",
    "stage6_summarize":  "S6  Summary generation  [LLM: {summary_generation}]",
    "stage7_check":      "S7  Deterministic check [deterministic]",
    "stage8_review":     "S8  Final LLM review    [LLM: {final_review}]",
}

def _print_stage_debug(pipe_result):
    """Print a per-stage timing table for one pipeline run."""
    m = {
        "claim_extraction":   pipeline_config.MODELS.claim_extraction,
        "claim_verification": pipeline_config.MODELS.claim_verification,
        "context_agent":      pipeline_config.MODELS.context_agent,
        "summary_generation": pipeline_config.MODELS.summary_generation,
        "final_review":       pipeline_config.MODELS.final_review,
    }
    W = 60
    print(f"  ┌{'─'*W}┬──────────┬────────┐")
    print(f"  │ {'Stage':<{W-2}} │  Time(s) │ Status │")
    print(f"  ├{'─'*W}┼──────────┼────────┤")
    for t in pipe_result.timings:
        label = _STAGE_LABELS.get(t.name, t.name).format(**m)
        status = "SKIP " if t.skipped else "ok   "
        print(f"  │ {label:<{W-2}} │ {t.seconds:>8.2f} │ {status:<6} │")
    total = sum(t.seconds for t in pipe_result.timings)
    print(f"  ├{'─'*W}┼──────────┼────────┤")
    print(f"  │ {'TOTAL':<{W-2}} │ {total:>8.2f} │        │")
    print(f"  └{'─'*W}┴──────────┴────────┘")
    comp = pipe_result.compression
    if comp:
        band = "IN BAND ✓" if comp.in_target_band else "OUT OF BAND ✗"
        print(f"  compression: {comp.achieved_ratio:.2f}  "
              f"({comp.summary_chars} / {comp.note_chars} chars)  [{band}]")
    # Deterministic check result
    s7 = "PASS ✓" if pipe_result.check_passed else "FAIL ✗"
    print(f"  S7 det. check : {s7}")

    # LLM review result
    cc = pipe_result.review_concern_counts
    s8 = "PASS ✓" if pipe_result.review_passed else "FAIL ✗ (high-severity concern)"
    print(f"  S8 LLM review : {s8}  "
          f"(high={cc.get('high',0)}  medium={cc.get('medium',0)}  low={cc.get('low',0)})")
    for c in (getattr(pipe_result, '_review', None) and [] or []):
        pass  # concerns printed below if desired

    if pipe_result.input_note_path:
        print(f"  input note    : {pipe_result.input_note_path}")
    if pipe_result.summary_path:
        print(f"  summary       : {pipe_result.summary_path}")
    if pipe_result.revised_summary_path:
        rcp = pipe_result.revised_check_passed
        rcp_str = "check PASS ✓" if rcp else ("check FAIL ✗" if rcp is False else "not checked")
        print(f"  revised summ. : {pipe_result.revised_summary_path}  [{rcp_str}]")
    else:
        print(f"  revised summ. : (none — no applicable revisions)")

results = []
for case in sampled:
    bundle_path, notes_dir = mimic.materialize_real_case(case, BENCH_DIR)

    print(f"\n{'='*66}")
    print(f"  CASE: {case.case_id}")
    print(f"  note_chars={len(case.note_text)}  gold_concepts={len(case.gold_concepts)}")
    print(f"{'='*66}")

    try:
        pipe_result = run_pipeline(
            case_id=case.case_id,
            bundle_path=bundle_path,
            notes_dir=notes_dir,
            resume=RESUME,
            allow_violations=ALLOW_VIOLATIONS,
            enable_context_agent=ENABLE_CONTEXT_AGENT,
            summary_min_ratio=SUMMARY_MIN_RATIO,
            summary_max_ratio=SUMMARY_MAX_RATIO,
        )
    except OllamaError as exc:
        print(f"  ERROR: {exc}")
        if exc.status_code == 401:
            print("  Hint: local Ollama rejects Bearer tokens — set OLLAMA_HOST=https://ollama.com"
                  " or unset OLLAMA_API_KEY for local runs.")
        elif exc.status_code == 404:
            print("  Hint: model not found. Check MODELS in ehr_pipeline/config.py.")
        traceback.print_exc()
        reference = mimic.real_case_reference_summary(case)
        gold_set = mimic.real_case_gold_entities(case)
        results.append({
            "case_id": case.case_id,
            "check_passed": False,
            "context_agent_on": ENABLE_CONTEXT_AGENT,
            "prediction": "",
            "reference": reference,
            "gold_entities": gold_set,
            "output_dir": str(pipeline_config.output_dir(case.case_id)),
            "total_seconds": 0.0,
            "note_chars": len(case.note_text),
            "summary_chars": 0,
            "compression_ratio": 0.0,
            "compression_in_band": False,
            "error": str(exc),
        })
        continue

    _print_stage_debug(pipe_result)

    if pipe_result.summary_path is None:
        print(f"\n  WARNING: no summary emitted (check_passed=False, "
              f"audit at {pipe_result.audit_path})")
        prediction = ""
        prediction_source = "none"
    elif pipe_result.revised_summary_path and pipe_result.revised_check_passed:
        # Use the revised summary when it exists AND passes the deterministic check.
        prediction = pipe_result.revised_summary_path.read_text(encoding="utf-8")
        prediction_source = "revised"
    else:
        prediction = pipe_result.summary_path.read_text(encoding="utf-8")
        prediction_source = "original"

    print(f"  benchmarking  : using {prediction_source} summary for metrics")

    reference = mimic.real_case_reference_summary(case)
    gold_set = mimic.real_case_gold_entities(case)

    comp = pipe_result.compression
    cc = pipe_result.review_concern_counts
    ps = pipe_result.patient_summary
    patient_md = ps.path.read_text(encoding="utf-8") if ps and ps.path.exists() else ""
    results.append({
        "case_id": case.case_id,
        "check_passed": pipe_result.check_passed,
        "review_passed": pipe_result.review_passed,
        "review_high": cc.get("high", 0),
        "review_medium": cc.get("medium", 0),
        "review_low": cc.get("low", 0),
        "prediction_source": prediction_source,   # "original" | "revised" | "none"
        "context_agent_on": pipe_result.context_agent_enabled,
        "prediction": prediction,
        "reference": reference,
        "gold_entities": gold_set,
        "output_dir": str(pipe_result.output_dir),
        "total_seconds": sum(t.seconds for t in pipe_result.timings),
        "note_chars": comp.note_chars if comp else 0,
        "summary_chars": comp.summary_chars if comp else 0,
        "compression_ratio": comp.achieved_ratio if comp else 0.0,
        "compression_in_band": comp.in_target_band if comp else False,
        # Stage 9 — patient-facing summary (independent text + readability score)
        "patient_summary": patient_md,
        "patient_fk_grade": ps.fk_grade if ps else None,
        "patient_fk_words": ps.fk_words if ps else 0,
        "patient_fk_sentences": ps.fk_sentences if ps else 0,
        "patient_chars": ps.chars if ps else 0,
        "patient_in_target_band": ps.in_target_band if ps else False,
    })

2026-05-01 23:01:36,595 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-72907-165405-520384
2026-05-01 23:01:36,598 INFO ehr_pipeline.stages.s1_evidence:   wrote 46 evidence items (35 structured, 11 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/evidence_store.json
2026-05-01 23:01:36,599 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-01 23:01:36,599 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

==================================================================
  CASE: mimic-72907-165405-520384
  note_chars=3404  gold_concepts=9
==================================================================

2026-05-01 23:02:26,203 INFO ehr_pipeline.stages.s2_extract:   extracted 22 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/claims.json
2026-05-01 23:02:26,205 INFO ehr_pipeline.runtime:   stage2_extract done in 49.61s
2026-05-01 23:02:26,206 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 22 claims
2026-05-01 23:02:38,016 INFO ehr_pipeline.stages.s3_verify:   {'verified': 6, 'contradicted': 1, 'unsupported': 15} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/verifications.json
2026-05-01 23:02:38,019 INFO ehr_pipeline.runtime:   stage3_verify done in 11.81s
2026-05-01 23:02:38,020 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:02:38,028 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:02:38,037 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 39, 'medications': 1, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-01 23:02:38,041 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.01s
2026-05-01 23:02:38,045 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:02:47,444 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/patient_summary.md (1272 chars, FK grade=7.76, in_band=True)
2026-05-01 23:02:47,449 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 9.40s
2026-05-01 23:02:47,452 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:03:03,403 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/summary.md (1172 chars, ratio=0.34, target=0.20-0.30, in_band=False)
2026-05-01 23:03:03,405 INFO ehr_pipeline.runtime:   stage6_summarize done in 15.95s
2026-05-01 23:03:03,409 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:03:03,413 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/check_report.json
2026-05-01 23:03:03,414 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-01 23:03:03,415 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:03:28,493 INFO ehr_pipeline.stages.s8_review:   concerns=4 recommended_revisions=4 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/review.json
2026-05-01 23:03:28,498 INFO ehr_pipeline.runtime:   stage8_review done in 25.08s
2026-05-01 23:03:28,499 INFO ehr_pipeline.pipeline:   applied revision: 'Comorbidities include disseminated candidiasis [E:cond:2], o' → 'Other problems include disseminated candidiasis [E:cond:2], '
2026-05-01 23:03:28,500 INFO ehr_pipeline.pipeline:   applied revision: 'Additional diagnoses include necrotizing fasciitis [E:cond:8' → 'Other problems include necrotizing fasciitis [E:cond:8], acu'
2026-05-01 23:03:28,500 INFO ehr_pipeline.pipeline:   applied revision: 'Renal status is significant for acute kidney failure with tu' → 'Renal status is significant for acute kidney failure with le'
2026-05-01 23:03:28,500 INFO ehr_pipeline.pipeline:   applied revision: 'Chronic conditions include essential hypertension [E:cond:15' → 'Other problems include essential hypertension [E:cond:15], d'
2026-05-01 23:03:28,502 INFO ehr_pipeline.pipeline: Wrote revised summary (4 revision(s) applied) -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/summary_revised.md
2026-05-01 23:03:28,502 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:03:28,504 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/check_report_revised.json
2026-05-01 23:03:28,504 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-01 23:03:28,513 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-29307-175627-318233
2026-05-01 23:03:28,518 INFO ehr_pipeline.stages.s1_evidence:   wrote 28 evidence items (19 structured, 9 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/evidence_store.json
2026-05-01 23:03:28,519 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-01 23:03:28,520 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    49.61 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    11.81 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.01 │ ok     │
  │ stage9_patient_summary                                     │     9.40 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    15.95 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │    25.08 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   111.88 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.34  (1172 / 3404 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=4)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/summary.md
  revised summ. : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-72907-165405-520384/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-29307-175627-318233
  note_chars=784  gold_concepts=7
==================================================================

2026-05-01 23:03:41,161 INFO ehr_pipeline.stages.s2_extract:   extracted 14 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/claims.json
2026-05-01 23:03:41,164 INFO ehr_pipeline.runtime:   stage2_extract done in 12.64s
2026-05-01 23:03:41,164 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 14 claims
2026-05-01 23:04:03,675 INFO ehr_pipeline.stages.s3_verify:   {'verified': 12, 'contradicted': 0, 'unsupported': 2} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/verifications.json
2026-05-01 23:04:03,676 INFO ehr_pipeline.runtime:   stage3_verify done in 22.51s
2026-05-01 23:04:03,677 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:04:03,681 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:04:03,684 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 24, 'medications': 2, 'labs': 1, 'vitals': 2, 'plan': 1}
2026-05-01 23:04:03,684 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-01 23:04:03,685 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:04:14,136 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/patient_summary.md (1627 chars, FK grade=7.06, in_band=True)
2026-05-01 23:04:14,137 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 10.45s
2026-05-01 23:04:14,139 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:04:20,898 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/summary.md (480 chars, ratio=0.61, target=0.20-0.30, in_band=False)
2026-05-01 23:04:20,900 INFO ehr_pipeline.runtime:   stage6_summarize done in 6.76s
2026-05-01 23:04:20,906 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:04:20,909 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/check_report.json
2026-05-01 23:04:20,909 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-01 23:04:20,911 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:04:29,019 INFO ehr_pipeline.stages.s8_review:   concerns=4 recommended_revisions=4 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/review.json
2026-05-01 23:04:29,020 INFO ehr_pipeline.runtime:   stage8_review done in 8.11s
2026-05-01 23:04:29,021 INFO ehr_pipeline.pipeline:   applied revision: 'COPD exacerbation [E:cond:1][E:note:row318233:3].' → 'Obstructive chronic bronchitis with (acute) exacerbation [E:'
2026-05-01 23:04:29,022 WARNING ehr_pipeline.pipeline:   revision original not found verbatim in summary, skipping: 'CHF [E:cond:6][E:note:row318233:2].'
2026-05-01 23:04:29,024 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/summary_revised.md
2026-05-01 23:04:29,024 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:04:29,026 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/check_report_revised.json
2026-05-01 23:04:29,026 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-01 23:04:29,034 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-47927-161682-717576
2026-05-01 23:04:29,037 INFO ehr_pipeline.stages.s1_evidence:   wrote 36 evidence items (24 structured, 12 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/evidence_store.json
2026-05-01 23:04:29,037 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-01 23:04:29,038 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    12.64 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    22.51 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    10.45 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     6.76 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │     8.11 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │    60.49 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.61  (480 / 784 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=3  low=0)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/summary.md
  revised summ. : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-29307-175627-318233/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-47927-161682-717576
  note_chars=2592  gold_concepts=7
==================================================================

2026-05-01 23:06:36,419 INFO ehr_pipeline.stages.s2_extract:   extracted 45 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/claims.json
2026-05-01 23:06:36,422 INFO ehr_pipeline.runtime:   stage2_extract done in 127.38s
2026-05-01 23:06:36,422 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 45 claims
2026-05-01 23:08:00,482 INFO ehr_pipeline.stages.s3_verify:   {'verified': 18, 'contradicted': 1, 'unsupported': 26} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/verifications.json
2026-05-01 23:08:00,487 INFO ehr_pipeline.runtime:   stage3_verify done in 84.06s
2026-05-01 23:08:00,488 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:08:00,492 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:08:00,494 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 32, 'medications': 3, 'labs': 1, 'vitals': 3, 'plan': 0}
2026-05-01 23:08:00,495 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-01 23:08:00,496 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:11:45,333 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/patient_summary.md (1577 chars, FK grade=7.58, in_band=True)
2026-05-01 23:11:45,337 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 224.84s
2026-05-01 23:11:45,338 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:12:23,064 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/summary.md (1157 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-01 23:12:23,070 INFO ehr_pipeline.runtime:   stage6_summarize done in 37.73s
2026-05-01 23:12:23,072 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:12:23,074 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/check_report.json
2026-05-01 23:12:23,075 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-01 23:12:23,079 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:12:48,838 INFO ehr_pipeline.stages.s8_review:   concerns=7 recommended_revisions=7 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/review.json
2026-05-01 23:12:48,841 INFO ehr_pipeline.runtime:   stage8_review done in 25.76s
2026-05-01 23:12:48,842 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with herpetic meningoencephalitis, acute re' → 'Patient had a history of herpetic meningoencephalitis, acute'
2026-05-01 23:12:48,842 INFO ehr_pipeline.pipeline:   applied revision: 'Additional diagnoses include sepsis, MS changes, altered men' → 'Additional diagnoses include altered mental status and agita'
2026-05-01 23:12:48,843 INFO ehr_pipeline.pipeline:   applied revision: 'Comorbidities include severe SLE, cryoglobulinemia vasculiti' → 'Comorbidities include severe SLE and other paraproteinemias '
2026-05-01 23:12:48,843 INFO ehr_pipeline.pipeline:   applied revision: 'History of cardiac arrest, CHF, and cardiac dysrhythmias [E:' → 'Cardiac arrest, CHF, and cardiac dysrhythmias [E:cond:12][E:'
2026-05-01 23:12:48,844 INFO ehr_pipeline.pipeline:   applied revision: 'Other issues include coagulation defects, anemia, epilepsy, ' → 'Other issues include coagulation defects, anemia, drug withd'
2026-05-01 23:12:48,844 INFO ehr_pipeline.pipeline:   applied revision: 'Extremity atherosclerosis with foot ulceration noted [E:cond' → 'Extremity atherosclerosis noted [E:cond:17][E:cond:18].'
2026-05-01 23:12:48,844 INFO ehr_pipeline.pipeline:   applied revision: 'Sedation with fentanyl and versed [E:note:row717576:11].' → 'Sedation on fentanyl and versed [E:note:row717576:11].'
2026-05-01 23:12:48,846 INFO ehr_pipeline.pipeline: Wrote revised summary (7 revision(s) applied) -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/summary_revised.md
2026-05-01 23:12:48,846 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:12:48,848 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/check_report_revised.json
2026-05-01 23:12:48,849 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-01 23:12:48,857 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-77013-141363-444743
2026-05-01 23:12:48,862 INFO ehr_pipeline.stages.s1_evidence:   wrote 116 evidence items (73 structured, 43 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/evidence_store.json
2026-05-01 23:12:48,862 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-01 23:12:48,863 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │   127.38 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    84.06 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   224.84 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    37.73 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │    25.76 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   499.79 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (1157 / 2592 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=6  low=1)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/summary.md
  revised summ. : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-47927-161682-717576/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-77013-141363-444743
  note_chars=2827  gold_concepts=7
==================================================================

2026-05-01 23:13:55,645 INFO ehr_pipeline.stages.s2_extract:   extracted 53 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/claims.json
2026-05-01 23:13:55,648 INFO ehr_pipeline.runtime:   stage2_extract done in 66.79s
2026-05-01 23:13:55,649 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 53 claims
2026-05-01 23:14:47,053 INFO ehr_pipeline.stages.s3_verify:   {'verified': 43, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/verifications.json
2026-05-01 23:14:47,056 INFO ehr_pipeline.runtime:   stage3_verify done in 51.41s
2026-05-01 23:14:47,057 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:14:47,060 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:14:47,063 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 45, 'medications': 8, 'labs': 6, 'vitals': 9, 'plan': 7}
2026-05-01 23:14:47,065 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.01s
2026-05-01 23:14:47,066 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:18:20,825 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/patient_summary.md (2104 chars, FK grade=7.67, in_band=True)
2026-05-01 23:18:20,829 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 213.76s
2026-05-01 23:18:20,831 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:18:44,283 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/summary.md (1683 chars, ratio=0.60, target=0.20-0.30, in_band=False)
2026-05-01 23:18:44,284 INFO ehr_pipeline.runtime:   stage6_summarize done in 23.45s
2026-05-01 23:18:44,287 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:18:44,293 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/check_report.json
2026-05-01 23:18:44,294 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-01 23:18:44,295 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:18:44,701 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: cc2a10f6-a95b-43f3-a804-b4f0569eebbf)
2026-05-01 23:18:46,124 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 2.9s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 3e3c593e-b849-4b39-bc1d-322854b1b7d4)
2026-05-01 23:18:49,417 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 3.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: f903ffde-7f98-4ef5-88af-c25474ea2903)
2026-05-01 23:18:52,941 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 1/4), retrying in 0.5s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 4799d288-8eac-43dd-9506-c9d58d51e262)
2026-05-01 23:18:53,846 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 2b46be66-630b-42cd-9455-57c41f23304b)
2026-05-01 23:18:55,967 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 3.4s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 45ce3bc3-ad42-415d-a5a0-4ae29d965526)
2026-05-01 23:18:59,727 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 4.5s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 9be14006-4c7c-457d-9caa-4843fd01f3a9)
2026-05-01 23:19:04,683 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 2/4), retrying in 0.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 705a91ee-68ab-4c8d-803b-57ae6b804d4c)
2026-05-01 23:19:05,764 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 3417c684-2fec-4d1f-bbe6-b0ffc7527fd6)
2026-05-01 23:19:07,205 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 2.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: c50c6c9e-46a4-4805-98c4-9b853432409b)
2026-05-01 23:19:09,785 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 5.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 614c5f7f-72e4-4f99-9094-6f5ee403d861)
2026-05-01 23:19:16,833 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 3/4), retrying in 4.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: f8a26402-ec8e-4024-aea6-81a30e286376)
2026-05-01 23:19:21,399 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 0.5s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 78ba3e3d-83c7-45bc-b901-25b9af3c3794)
2026-05-01 23:19:22,312 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 1.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 6e345184-151d-405f-94fb-579055b653a5)
2026-05-01 23:19:23,723 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 1.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: e73f5399-8a17-421e-a813-4414bec1709f)
2026-05-01 23:19:25,078 WARNING ehr_pipeline.stages.s8_review: Stage 8 review skipped due to API error ([HTTP 500] Ollama API failed: Internal Server Error (ref: 09e2dfea-9c6c-41cc-a2eb-51507d753b59)); summary is still emitted — review is advisory only.
2026-05-01 23:19:25,089 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/review.json
2026-05-01 23:19:25,090 INFO ehr_pipeline.runtime:   stage8_review done in 40.79s
2026-05-01 23:19:25,091 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-01 23:19:25,105 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-54229-165594-598031
2026-05-01 23:19:25,109 INFO ehr_pipeline.stages.s1_evidence:   wrote 96 evidence items (65 structured, 31 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/evidence_store.json
2026-05-01 23:19:25,110 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-01 23:19:25,110 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    66.79 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    51.41 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.01 │ ok     │
  │ stage9_patient_summary                                     │   213.76 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    23.45 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │    40.79 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   396.22 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.60  (1683 / 2827 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-77013-141363-444743/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-54229-165594-598031
  note_chars=2337  gold_concepts=9
==================================================================

2026-05-01 23:20:23,964 INFO ehr_pipeline.stages.s2_extract:   extracted 29 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/claims.json
2026-05-01 23:20:23,967 INFO ehr_pipeline.runtime:   stage2_extract done in 58.86s
2026-05-01 23:20:23,968 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 29 claims
2026-05-01 23:20:43,743 INFO ehr_pipeline.stages.s3_verify:   {'verified': 17, 'contradicted': 0, 'unsupported': 12} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/verifications.json
2026-05-01 23:20:43,744 INFO ehr_pipeline.runtime:   stage3_verify done in 19.78s
2026-05-01 23:20:43,745 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:20:43,748 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:20:43,750 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 37, 'medications': 5, 'labs': 0, 'vitals': 4, 'plan': 0}
2026-05-01 23:20:43,751 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-01 23:20:43,752 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:24:20,309 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/patient_summary.md (2029 chars, FK grade=6.49, in_band=False)
2026-05-01 23:24:20,319 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 216.56s
2026-05-01 23:24:20,324 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:24:31,714 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/summary.md (1010 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-01 23:24:31,715 INFO ehr_pipeline.runtime:   stage6_summarize done in 11.39s
2026-05-01 23:24:31,716 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:24:31,718 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/check_report.json
2026-05-01 23:24:31,719 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-01 23:24:31,719 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:24:36,674 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/review.json
2026-05-01 23:24:36,675 INFO ehr_pipeline.runtime:   stage8_review done in 4.96s
2026-05-01 23:24:36,676 INFO ehr_pipeline.pipeline:   applied revision: 'Septic shock [E:cond:9][E:cond:10], severe sepsis [E:cond:7]' → 'Unspecified septicemia [E:cond:5][E:cond:6], severe sepsis ['
2026-05-01 23:24:36,678 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/summary_revised.md
2026-05-01 23:24:36,678 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:24:36,681 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/check_report_revised.json
2026-05-01 23:24:36,681 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-01 23:24:36,687 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-17539-153621-390912
2026-05-01 23:24:36,691 INFO ehr_pipeline.stages.s1_evidence:   wrote 92 evidence items (33 structured, 59 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/evidence_store.json
2026-05-01 23:24:36,691 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-01 23:24:36,692 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    58.86 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    19.78 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   216.56 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    11.39 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │     4.96 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   311.56 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (1010 / 2337 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/summary.md
  revised summ. : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-54229-165594-598031/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-17539-153621-390912
  note_chars=4686  gold_concepts=5
==================================================================

2026-05-01 23:25:12,800 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/claims.json
2026-05-01 23:25:12,802 INFO ehr_pipeline.runtime:   stage2_extract done in 36.11s
2026-05-01 23:25:12,804 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-01 23:25:33,278 INFO ehr_pipeline.stages.s3_verify:   {'verified': 26, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/verifications.json
2026-05-01 23:25:33,280 INFO ehr_pipeline.runtime:   stage3_verify done in 20.48s
2026-05-01 23:25:33,280 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:25:33,284 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:25:33,286 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 39, 'medications': 7, 'labs': 7, 'vitals': 0, 'plan': 2}
2026-05-01 23:25:33,287 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-01 23:25:33,288 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:29:32,901 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/patient_summary.md (1930 chars, FK grade=7.74, in_band=True)
2026-05-01 23:29:32,904 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 239.62s
2026-05-01 23:29:32,906 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:36:29,372 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/summary.md (2334 chars, ratio=0.50, target=0.20-0.30, in_band=False)
2026-05-01 23:36:29,378 INFO ehr_pipeline.runtime:   stage6_summarize done in 416.47s
2026-05-01 23:36:29,381 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:36:29,384 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=18 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/check_report.json
2026-05-01 23:36:29,384 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-01 23:36:29,385 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:36:29,765 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 706fdcaf-0a57-4e4b-a07b-f41c7802351b)
2026-05-01 23:36:31,508 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 0.6s: [HTTP 500] Ollama API failed: Internal Server Error (ref: cf140fe4-1a70-46df-a0e6-7bd3e3d0a9d2)
2026-05-01 23:36:32,504 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 3.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 6756cadd-44ec-42c2-88a3-18664b7e1008)
2026-05-01 23:36:36,507 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 1/4), retrying in 1.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 3bdebab2-146a-4a92-a468-b9b7ba305f3f)
2026-05-01 23:36:37,957 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: b7bcea8d-5f1d-406c-98c1-c0c272187e30)
2026-05-01 23:36:39,595 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 2.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 47c05a23-d4f7-4500-aa96-a881984b918a)
2026-05-01 23:36:42,771 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 7.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 8d4f45e4-1881-4898-9c5a-b25262e1b272)
2026-05-01 23:36:50,194 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 2/4), retrying in 2.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 4474707b-2ca1-4d60-93cb-1d8a6a3adcd5)
2026-05-01 23:36:53,432 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 0.6s: [HTTP 500] Ollama API failed: Internal Server Error (ref: f72b3871-5297-468b-aa21-5eb5ccb8cf27)
2026-05-01 23:36:54,547 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 0.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: e965eff5-eab5-47f6-a9d8-c18816c70c4b)
2026-05-01 23:36:55,607 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 0.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: b2a7b058-de80-4c42-9af9-1b4c404e00fd)
2026-05-01 23:36:56,901 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 3/4), retrying in 6.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: a3272116-176a-4b5c-a884-66610bc3264a)
2026-05-01 23:37:03,545 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.4s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 662cee37-817f-4b6f-bee3-d678edf1fba6)
2026-05-01 23:37:05,345 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 3.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: fc21071d-ec95-4ac6-b86f-e91df03a7562)
2026-05-01 23:37:08,883 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 1.9s: [HTTP 500] Ollama API failed: Internal Server Error (ref: b2955712-6a74-4da3-9ff7-a8904539abd8)
2026-05-01 23:37:11,132 WARNING ehr_pipeline.stages.s8_review: Stage 8 review skipped due to API error ([HTTP 500] Ollama API failed: Internal Server Error (ref: bc7cdddf-787c-4c38-9bd4-e2e045faa4ae)); summary is still emitted — review is advisory only.
2026-05-01 23:37:11,137 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/review.json
2026-05-01 23:37:11,138 INFO ehr_pipeline.runtime:   stage8_review done in 41.75s
2026-05-01 23:37:11,138 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-01 23:37:11,147 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-85464-164726-466035
2026-05-01 23:37:11,152 INFO ehr_pipeline.stages.s1_evidence:   wrote 80 evidence items (41 structured, 39 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/evidence_store.json
2026-05-01 23:37:11,152 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-01 23:37:11,153 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    36.11 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    20.48 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   239.62 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   416.47 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │    41.75 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   754.44 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.50  (2334 / 4686 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-17539-153621-390912/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-85464-164726-466035
  note_chars=3032  gold_concepts=9
==================================================================

2026-05-01 23:37:50,991 INFO ehr_pipeline.stages.s2_extract:   extracted 34 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/claims.json
2026-05-01 23:37:50,994 INFO ehr_pipeline.runtime:   stage2_extract done in 39.84s
2026-05-01 23:37:50,995 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 34 claims
2026-05-01 23:38:12,392 INFO ehr_pipeline.stages.s3_verify:   {'verified': 24, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/verifications.json
2026-05-01 23:38:12,393 INFO ehr_pipeline.runtime:   stage3_verify done in 21.40s
2026-05-01 23:38:12,394 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:38:12,396 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:38:12,398 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 28, 'medications': 5, 'labs': 2, 'vitals': 4, 'plan': 3}
2026-05-01 23:38:12,399 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-01 23:38:12,399 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:38:27,222 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/patient_summary.md (1638 chars, FK grade=6.59, in_band=False)
2026-05-01 23:38:27,223 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.82s
2026-05-01 23:38:27,225 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:38:42,842 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/summary.md (1715 chars, ratio=0.57, target=0.20-0.30, in_band=False)
2026-05-01 23:38:42,843 INFO ehr_pipeline.runtime:   stage6_summarize done in 15.62s
2026-05-01 23:38:42,846 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:38:42,849 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/check_report.json
2026-05-01 23:38:42,850 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-01 23:38:42,851 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:38:43,191 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.4s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 8fa23f74-2244-417d-b034-98858c727fcb)
2026-05-01 23:38:45,037 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 1.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 2ccd1872-4178-4aff-b5b2-5a55a011cd42)
2026-05-01 23:38:47,059 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 4.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 364aed07-cb69-440e-8c4c-dcf9bb831f9e)
2026-05-01 23:38:52,101 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 1/4), retrying in 1.9s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 272fa84b-e8e7-4b56-9236-22eb0071d2cd)
2026-05-01 23:38:54,390 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 0.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 4d6c1e86-18fe-446a-af07-f5dcb8e16395)
2026-05-01 23:38:55,481 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 1.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: fef8a81f-342b-45d9-892b-3e93b7f49828)
2026-05-01 23:38:57,621 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 4.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: cec2f1cf-8f27-4a27-b8d5-190119c50afa)
2026-05-01 23:39:02,036 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 2/4), retrying in 1.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 513307f1-518f-4f5c-bef8-1d6b818abe11)
2026-05-01 23:39:03,571 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 63de3e95-c1a1-4867-9623-7e755379ded3)
2026-05-01 23:39:05,722 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 3.9s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 56f1c8cf-5b5c-43d3-a00e-157596247cd2)
2026-05-01 23:39:10,126 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 7.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 39d6273a-23ea-4f12-b738-13cd860b8533)
2026-05-01 23:39:17,805 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 3/4), retrying in 5.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 03460cc8-ce5f-468c-8619-f9b4238ce250)
2026-05-01 23:39:23,334 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 0.6s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 52c1456a-1056-4eb6-b6e4-e657ed193a90)
2026-05-01 23:39:24,248 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 1.9s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 7ffb20b3-7094-4357-84e5-123bc0384811)
2026-05-01 23:39:26,509 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 1.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: fea5ddde-e676-47a8-b771-d159bea79ddd)
2026-05-01 23:39:28,527 WARNING ehr_pipeline.stages.s8_review: Stage 8 review skipped due to API error ([HTTP 500] Ollama API failed: Internal Server Error (ref: fe5922f4-c907-44ed-aa92-28d54eb1c7df)); summary is still emitted — review is advisory only.
2026-05-01 23:39:28,531 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/review.json
2026-05-01 23:39:28,533 INFO ehr_pipeline.runtime:   stage8_review done in 45.68s
2026-05-01 23:39:28,535 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-01 23:39:28,544 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-79877-185698-417636
2026-05-01 23:39:28,551 INFO ehr_pipeline.stages.s1_evidence:   wrote 42 evidence items (25 structured, 17 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/evidence_store.json
2026-05-01 23:39:28,551 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-01 23:39:28,552 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    39.84 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    21.40 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.82 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    15.62 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │    45.68 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   137.37 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.57  (1715 / 3032 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-85464-164726-466035/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-79877-185698-417636
  note_chars=1836  gold_concepts=8
==================================================================

2026-05-01 23:39:51,803 INFO ehr_pipeline.stages.s2_extract:   extracted 25 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/claims.json
2026-05-01 23:39:51,804 INFO ehr_pipeline.runtime:   stage2_extract done in 23.25s
2026-05-01 23:39:51,805 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 25 claims
2026-05-01 23:40:05,016 INFO ehr_pipeline.stages.s3_verify:   {'verified': 18, 'contradicted': 0, 'unsupported': 7} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/verifications.json
2026-05-01 23:40:05,017 INFO ehr_pipeline.runtime:   stage3_verify done in 13.21s
2026-05-01 23:40:05,018 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:40:05,020 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:40:05,022 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 33, 'medications': 4, 'labs': 2, 'vitals': 2, 'plan': 0}
2026-05-01 23:40:05,023 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-01 23:40:05,024 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:40:15,564 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/patient_summary.md (1434 chars, FK grade=8.52, in_band=False)
2026-05-01 23:40:15,565 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 10.54s
2026-05-01 23:40:15,566 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-01 23:40:24,062 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/summary.md (881 chars, ratio=0.48, target=0.20-0.30, in_band=False)
2026-05-01 23:40:24,063 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.50s
2026-05-01 23:40:24,066 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:40:24,068 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/check_report.json
2026-05-01 23:40:24,069 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-01 23:40:24,069 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-01 23:40:33,517 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/review.json
2026-05-01 23:40:33,517 INFO ehr_pipeline.runtime:   stage8_review done in 9.45s
2026-05-01 23:40:33,521 INFO ehr_pipeline.pipeline:   applied revision: 'Primary liver malignancy [E:cond:5], cirrhosis [E:cond:10], ' → 'Primary liver malignancy [E:cond:5], cirrhosis [E:cond:10], '
2026-05-01 23:40:33,522 INFO ehr_pipeline.pipeline:   applied revision: 'Cardiogenic shock [E:cond:14], acute systolic heart failure ' → 'Cardiogenic shock [E:cond:14], acute systolic heart failure '
2026-05-01 23:40:33,523 INFO ehr_pipeline.pipeline:   applied revision: 'Acidosis [E:cond:8], hyperpotassemia [E:cond:12], and hemoly' → 'Acidosis [E:cond:8], hyperpotassemia [E:cond:12], and acquir'
2026-05-01 23:40:33,526 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/summary_revised.md
2026-05-01 23:40:33,527 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-01 23:40:33,529 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/check_report_revised.json
2026-05-01 23:40:33,530 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-01 23:40:33,537 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-92277-173474-1282
2026-05-01 23:40:33,543 INFO ehr_pipeline.stages.s1_evidence:   wrote 159 evidence items (24 structured, 135 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-92277-173474-1282/evidence_store.json
2026-05-01 23:40:33,544 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-01 23:40:33,544 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma3:27b]                  │    23.25 │ ok     │
  │ S3  Claim verification  [LLM: gemma3:27b]                  │    13.21 │ ok     │
  │ S4  Context agent       [LLM: gemma3:27b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    10.54 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.50 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma3:27b]                  │     9.45 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │    64.96 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.48  (881 / 1836 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=3  low=0)
  input note    : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/input_note.txt
  summary       : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/summary.md
  revised summ. : /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-79877-185698-417636/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-92277-173474-1282
  note_chars=16139  gold_concepts=20
==================================================================

2026-05-01 23:40:33,992 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.5s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 1245c735-9abb-4312-a3ed-cd1be6a5bc49)
2026-05-01 23:40:35,870 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 1.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 5162565a-63b7-4358-be41-d410846bcab5)
2026-05-01 23:40:37,474 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 0.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: bdae0755-9ad8-4c24-82db-1ba4b2fc689b)
2026-05-01 23:40:38,698 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 1/4), retrying in 1.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 2d936b3c-e868-47e8-bb04-183ce2671297)
2026-05-01 23:40:40,955 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 2.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 7e5cd957-216e-4169-a2d0-0c0cf9be32f8)
2026-05-01 23:40:43,414 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 0.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 3c4eeb59-ddc0-480f-9fa5-0f3223bfbdca)
2026-05-01 23:40:44,576 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 1.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 1bdfb4e3-125f-41d7-8407-261b175285c5)
2026-05-01 23:40:46,280 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 2/4), retrying in 1.8s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 6c3e2da8-d5f0-4eec-bdee-b67f7969d921)
2026-05-01 23:40:48,636 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 5885d994-a63f-445f-925f-39ec60f90ec0)
2026-05-01 23:40:50,094 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 4.0s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 97d154fa-1a90-4eda-9c98-dee3e73a2f94)
2026-05-01 23:40:54,472 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 4.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: abcd7247-e658-46cf-aa6b-3801fb9bf2cc)
2026-05-01 23:40:59,078 WARNING ehr_pipeline.ollama_client: LLM JSON request failed (attempt 3/4), retrying in 5.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: dd813222-ea67-4f45-8f6b-19e2cc4c1190)
2026-05-01 23:41:04,764 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 8888880c-95b0-49d2-a59a-004db3bc82f8)
2026-05-01 23:41:06,453 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 2/4), retrying in 2.1s: [HTTP 500] Ollama API failed: Internal Server Error (ref: a21bfb45-1ad8-4da0-a664-1bcbc42a00e4)
2026-05-01 23:41:08,966 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 3/4), retrying in 6.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 7dec313a-6d91-430b-b509-d89dfff7a0cb)
Traceback (most recent call last):
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 109, in _post_once
    with urllib.request.urlopen(req, timeout=self.timeout) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/1p/37rbx0v13zb8r6sc4pby6lpc0000gn/T/ipykernel_44382/1941772926.py", line 81, in <module>
    pipe_result = run_pipeline(
                  ^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/pipeline.py", line 169, in run_pipeline
    extraction = run_extraction(
                 ^^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/extraction.py", line 73, in run_extraction
    claims = time_stage(
             ^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/runtime.py", line 48, in time_stage
    result = fn()
             ^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/extraction.py", line 75, in <lambda>
    lambda: s2_extract.run(notes_dir=notes_dir, output_dir=output_dir),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/stages/s2_extract.py", line 52, in run
    raw = chat_json(
          ^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 372, in chat_json
    return get_client().chat_json(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 299, in chat_json
    raise last_exc  # type: ignore[misc]
    ^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 279, in chat_json
    raw = self.chat(
          ^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 189, in chat
    return self._post(payload)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 145, in _post
    raise last_exc  # type: ignore[misc]
    ^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 132, in _post
    return self._post_once(payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/natejly/Desktop/LLMS's FInal/ehr_pipeline/ollama_client.py", line 118, in _post_once
    raise OllamaError(f"Ollama API failed: {detail}", exc.code) from exc
ehr_pipeline.ollama_client.OllamaError: [HTTP 500] Ollama API failed: Internal Server Error (ref: ba208b29-5784-49b6-96d0-e1cb4389b48c)
2026-05-01 23:41:15,685 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-94229-146659-541449
2026-05-01 23:41:15,691 INFO ehr_pipeline.stages.s1_evidence:   wrote 69 evidence items (45 structured, 24 note sentences) to /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-94229-146659-541449/evidence_store.json
2026-05-01 23:41:15,691 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-01 23:41:15,692 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ERROR: [HTTP 500] Ollama API failed: Internal Server Error (ref: ba208b29-5784-49b6-96d0-e1cb4389b48c)

==================================================================
  CASE: mimic-94229-146659-541449
  note_chars=2700  gold_concepts=6
==================================================================

2026-05-01 23:42:54,607 WARNING ehr_pipeline.schemas: Unknown claim type 'action' — coerced to 'plan'
2026-05-01 23:42:54,611 INFO ehr_pipeline.stages.s2_extract:   extracted 76 claims, wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-94229-146659-541449/claims.json
2026-05-01 23:42:54,612 INFO ehr_pipeline.runtime:   stage2_extract done in 98.92s
2026-05-01 23:42:54,613 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 76 claims
2026-05-01 23:43:36,089 INFO ehr_pipeline.stages.s3_verify:   {'verified': 51, 'contradicted': 0, 'unsupported': 25} -> /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-94229-146659-541449/verifications.json
2026-05-01 23:43:36,104 INFO ehr_pipeline.runtime:   stage3_verify done in 41.49s
2026-05-01 23:43:36,106 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-01 23:43:36,110 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-01 23:43:36,123 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 68, 'medications': 8, 'labs': 4, 'vitals': 7, 'plan': 5}
2026-05-01 23:43:36,127 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.02s
2026-05-01 23:43:36,129 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-01 23:44:55,530 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Desktop/LLMS's FInal/outputs/mimic-94229-146659-541449/patient_summary.md (1895 chars, FK grade=7.77, in_band=True)
2026-05-01 23:44:55,538 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 79.41s
2026-05-01 23:44:55,539 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown

KeyboardInterrupt:

## Inspect one generated summary vs reference

In [ ]:
if results:
    r = results[0]
    print(f"--- {r['case_id']} ---\n")
    print(
        f"compression: {r['summary_chars']}/{r['note_chars']} = {r['compression_ratio']:.2f}"
        f" (target {SUMMARY_MIN_RATIO:.2f}-{SUMMARY_MAX_RATIO:.2f}, in_band={r['compression_in_band']})\n"
    )
    print("=== REFERENCE ===\n")
    print(r["reference"])
    print("\n=== PREDICTION ===\n")
    print(r["prediction"][:3000] or "(empty)")

--- mimic-72907-165405-520384 ---

compression: 997/3404 = 0.29 (target 0.20-0.30, in_band=True)

=== REFERENCE ===

## HPI
77.0-year-old female.
## Active Problems
- Abdominal Pain.
- Sepsis.
- Septicemia.
- Pain.
- Grimaces.
- Respiratory Failure.
- Kidney Failure.
- Atrial Fibrillation.
## EHR Diagnoses
- Other postoperative infection.
- Disseminated candidiasis.
- Severe sepsis.
- Septic shock.
- Other suppurative peritonitis.
- Acute and subacute necrosis of liver.
- Acute kidney failure with lesion of tubular necrosis.
- Necrotizing fasciitis.
- Acute vascular insufficiency of intestine.
- None.
- Acidosis.
- Acute salpingitis and oophoritis.
- Candidiasis of other urogenital sites.
- Acute inflammatory diseases of uterus, except cervix.
- Unspecified essential hypertension.
- Depressive disorder, not elsewhere classified.
- Unspecified acquired hypothyroidism.
- Other specified surgical operations and procedures causing abnormal patient reaction, or later complication, without mention of misadventure at time of operation.
## Procedures
- Open and other left hemicolectomy.
- Other partial resection of small intestine.
- Temporary ileostomy.
- Open and other resection of transverse colon.
- Open and other sigmoidectomy.
- Open and other right hemicolectomy.
- Other and unspecified subtotal abdominal hysterectomy.
- Other removal of both ovaries and tubes at same operative episode.
- Venous catheterization, not elsewhere classified.
- Arterial catheterization.
- Continuous invasive mechanical ventilation for 96 consecutive hours or more.
- Hemodialysis.
- Venous catheterization for renal dialysis.
- Parenteral infusion of concentrated nutritional substances.
- Other gastrostomy.
- Other enterostomy.
## Disposition
Patient expired during this admission.


=== PREDICTION ===

## HPI
_Not documented._

## Active Problems
Patient presents with severe sepsis [E:cond:3] and septic shock [E:cond:4]. Complications include disseminated candidiasis [E:cond:2], other postoperative infection [E:cond:1], and other suppurative peritonitis [E:cond:5]. Organ dysfunction is noted with acute kidney failure with tubular necrosis [E:cond:7], acute and subacute liver necrosis [E:cond:6], and acidosis [E:cond:11]. Additional diagnoses include necrotizing fasciitis [E:cond:8], acute vascular insufficiency of the intestine [E:cond:9], cystic stump leak [E:note:row520384:2], and candidiasis of urogenital sites [E:cond:13]. Pelvic findings include acute salpingitis, oophoritis [E:cond:12], and inflammatory diseases of the uterus [E:cond:14]. Chronic conditions include essential hypertension [E:cond:15], acquired hypothyroidism [E:cond:17], and depressive disorder [E:cond:16].

## Medications
Amioderone [E:note:row520384:11].

## Labs
_Not documented._

## Plan
_Not documented._

## Compute ROUGE and entity metrics per case

In [ ]:
rows = []
for r in results:
    if not r["prediction"].strip():
        continue
    row = {
        "case_id": r["case_id"],
        "check_passed": r["check_passed"],
        "context_agent_on": r["context_agent_on"],
        "compression_ratio": r["compression_ratio"],
        "compression_in_band": r["compression_in_band"],
        "total_seconds": r["total_seconds"],
    }
    row.update(metrics.rouge_scores(r["prediction"], r["reference"]))
    row.update(metrics.entity_recall_precision(
        prediction=r["prediction"],
        reference=r["reference"],
        gold_entities=r["gold_entities"],
    ))
    # Stage 9 — patient summary readability (Flesch-Kincaid grade target 7-8).
    # Re-score from the saved markdown so the metric matches what the UI shows.
    patient_md = r.get("patient_summary", "")
    if patient_md.strip():
        fk = metrics.flesch_kincaid_grade(patient_md)
        row["patient_fk_grade"] = fk["fk_grade"]
        row["patient_fk_in_target"] = fk["fk_in_target_band"]
        row["patient_fk_words"] = fk["fk_words"]
        row["patient_fk_sentences"] = fk["fk_sentences"]
        row["patient_chars"] = r.get("patient_chars", len(patient_md))
    else:
        row["patient_fk_grade"] = None
        row["patient_fk_in_target"] = False
        row["patient_fk_words"] = 0
        row["patient_fk_sentences"] = 0
        row["patient_chars"] = 0
    rows.append(row)

rouge_df = pd.DataFrame(rows)
rouge_df

2026-05-01 22:00:12,680 INFO absl: Using default tokenizer.

,case_id,check_passed,context_agent_on,compression_ratio,compression_in_band,total_seconds,rouge1_f,rouge2_f,rougeL_f,entity_precision,entity_recall,entity_f1,entity_tp,entity_fp,entity_fn,entity_gold
0,mimic-72907-165405-520384,True,False,0.292891,True,140.879319,0.366864,0.160714,0.230769,1.0,0.439024,0.610169,18,0,23,41

## BERTScore (batched, downloads `roberta-large` the first time)

In [ ]:
non_empty = [r for r in results if r["prediction"].strip()]
preds = [r["prediction"] for r in non_empty]
refs = [r["reference"] for r in non_empty]
case_ids = [r["case_id"] for r in non_empty]

if preds:
    bert_rows = metrics.bertscore_batch(preds, refs, model_type=BERTSCORE_MODEL)
    bert_df = pd.DataFrame(bert_rows, index=case_ids)
    bert_df.index.name = "case_id"
    bert_df = bert_df.reset_index()
else:
    bert_df = pd.DataFrame(columns=["case_id", "bertscore_p", "bertscore_r", "bertscore_f1"])

bert_df

2026-05-01 22:00:18,981 INFO httpx: HTTP Request: HEAD https://huggingface.co/roberta-large/resolve/main/config.json "HTTP/1.1 200 OK"
2026-05-01 22:00:19,023 INFO httpx: HTTP Request: HEAD https://huggingface.co/roberta-large/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-05-01 22:00:19,070 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/roberta-large/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-05-01 22:00:19,107 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-large/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-05-01 22:00:19,139 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/roberta-large/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-05-01 22:00:19,180 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-large/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-05-01 22:00:19,387 INFO httpx: HTTP Request: HEAD https://huggingface.co/roberta-large/resolve/main/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

                     case_id  bertscore_p  bertscore_r  bertscore_f1
0  mimic-72907-165405-520384     0.793051     0.819489      0.806053

## Combined per-case metrics

In [ ]:
if not rouge_df.empty and not bert_df.empty:
    full = rouge_df.merge(bert_df, on="case_id", how="left")
else:
    full = rouge_df.copy()

metric_cols = [c for c in (
    "rouge1_f", "rouge2_f", "rougeL_f",
    "bertscore_p", "bertscore_r", "bertscore_f1",
    "entity_precision", "entity_recall", "entity_f1",
    "compression_ratio",
    "patient_fk_grade",
) if c in full.columns]

display_cols = ["case_id", "check_passed", "context_agent_on", "compression_in_band",
                *metric_cols, "patient_fk_in_target",
                "entity_tp", "entity_fn", "entity_gold", "total_seconds"]
full[[c for c in display_cols if c in full.columns]].round(3)

,case_id,check_passed,context_agent_on,compression_in_band,rouge1_f,rouge2_f,rougeL_f,bertscore_p,bertscore_r,bertscore_f1,entity_precision,entity_recall,entity_f1,compression_ratio,entity_tp,entity_fn,entity_gold,total_seconds
0,mimic-72907-165405-520384,True,False,True,0.367,0.161,0.231,0.793,0.819,0.806,1.0,0.439,0.61,0.293,18,23,41,140.879

## Aggregate (mean / median / min / max)

In [ ]:
if metric_cols:
    agg = full[metric_cols].agg(["mean", "median", "min", "max"]).round(3)
    display(agg)
else:
    print("No metrics computed.")

,rouge1_f,rouge2_f,rougeL_f,bertscore_p,bertscore_r,bertscore_f1,entity_precision,entity_recall,entity_f1,compression_ratio
mean,0.367,0.161,0.231,0.793,0.819,0.806,1.0,0.439,0.61,0.293
median,0.367,0.161,0.231,0.793,0.819,0.806,1.0,0.439,0.61,0.293
min,0.367,0.161,0.231,0.793,0.819,0.806,1.0,0.439,0.61,0.293
max,0.367,0.161,0.231,0.793,0.819,0.806,1.0,0.439,0.61,0.293

## Save benchmark outputs

In [ ]:
import json as _json

report_path = BENCH_DIR / "benchmark_report.json"
report = {
    "models": {k: v for k, v in vars(pipeline_config.MODELS).items()},
    "context_agent_enabled": ENABLE_CONTEXT_AGENT,
    "compression_target": [SUMMARY_MIN_RATIO, SUMMARY_MAX_RATIO],
    "per_case": full.to_dict(orient="records"),
    "aggregate": (full[metric_cols].agg(["mean", "median", "min", "max"]).round(4).to_dict() if metric_cols else {}),
    "num_cases": len(full),
}
report_path.write_text(_json.dumps(report, indent=2, default=str), encoding="utf-8")
print("wrote", report_path)

csv_path = BENCH_DIR / "benchmark_metrics.csv"
full.to_csv(csv_path, index=False)
print("wrote", csv_path)

wrote /Users/natejly/Desktop/LLMS's FInal/outputs/_bench/benchmark_report.json
wrote /Users/natejly/Desktop/LLMS's FInal/outputs/_bench/benchmark_metrics.csv