# EHR Pipeline Benchmark on MIMIC-III-Ext-Notes

Benchmarks the `ehr_pipeline` package on real MIMIC-III clinical notes joined with the matching structured EHR.

Inputs:
- `datasets/mimic-iii-ext-notes-1.0.0/notes.csv` — 150 deidentified clinical notes (`row_id`, `subject_id`, `hadm_id`, `text`).
- `datasets/mimic-iii-ext-notes-1.0.0/labels.csv` — 2,288 expert-annotated clinical concepts per note, used as the **gold entity set** (filtered to `detection=yes`, `encounter=yes`, `negation=no`).
- `datasets/bquxjob_5dbe3bd2_19dae30f3cf.json` — structured EHR (diagnoses + procedures) per `hadm_id`. 130 of 130 unique note `hadm_id`s match.

Per case the notebook:
1. Materializes a FHIR R4 Bundle from the structured EHR and writes the **real** clinical note text to disk.
2. Runs the 8-stage pipeline (the context agent / stage 4 is **disabled** by default for benchmarking — `ENABLE_CONTEXT_AGENT`).
3. Builds a deterministic reference summary from gold concepts + structured EHR fields.
4. Scores the generated Markdown against the reference with **ROUGE-1/2/L**, **BERTScore P/R/F1**, **entity precision / recall / F1**, and reports the achieved **compression ratio** vs the 0.20–0.30 target.

Setup: `pip install -r requirements-bench.txt`. The pipeline reads `OLLAMA_API_KEY` and `OLLAMA_HOST` from `.env`.

In [22]:
import importlib
import logging
import re
import sys
import warnings
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
warnings.filterwarnings("ignore", category=FutureWarning)

# Force-reload every ehr_pipeline submodule so stale model names are never used.
# Re-run this cell if you edit config.py, prompts.py, or any stage file.
import ehr_pipeline.config
import ehr_pipeline.prompts
import ehr_pipeline.ollama_client
import ehr_pipeline.schemas
import ehr_pipeline.evidence_store
import ehr_pipeline.runtime
import ehr_pipeline.stages.s1_evidence
import ehr_pipeline.stages.s2_extract
import ehr_pipeline.stages.s3_verify
import ehr_pipeline.stages.s4_context
import ehr_pipeline.stages.s5_fact_sheet
import ehr_pipeline.stages.s6_summarize
import ehr_pipeline.stages.s7_check
import ehr_pipeline.stages.s8_review
import ehr_pipeline.extraction
import ehr_pipeline.verification
import ehr_pipeline.pipeline
import benchmarks.mimic
import benchmarks.metrics

for _mod in [
    ehr_pipeline.config, ehr_pipeline.prompts, ehr_pipeline.ollama_client,
    ehr_pipeline.schemas, ehr_pipeline.evidence_store, ehr_pipeline.runtime,
    ehr_pipeline.stages.s1_evidence, ehr_pipeline.stages.s2_extract,
    ehr_pipeline.stages.s3_verify, ehr_pipeline.stages.s4_context,
    ehr_pipeline.stages.s5_fact_sheet, ehr_pipeline.stages.s6_summarize,
    ehr_pipeline.stages.s7_check, ehr_pipeline.stages.s8_review,
    ehr_pipeline.extraction, ehr_pipeline.verification, ehr_pipeline.pipeline,
    benchmarks.mimic, benchmarks.metrics,
]:
    importlib.reload(_mod)

from ehr_pipeline import config as pipeline_config
from ehr_pipeline.pipeline import run_pipeline
from benchmarks import mimic, metrics

_CITATION_RE = re.compile(r"\[E:[^\]]+\]")


def strip_citations_for_metrics(text: str) -> str:
    """Remove evidence citations before benchmark scoring and compression counts."""
    return _CITATION_RE.sub("", text).strip()


print("project root:", PROJECT_ROOT)
print("models:")
for k, v in vars(pipeline_config.MODELS).items():
    print(f"  {k}: {v}")
print("ollama host:", pipeline_config.OLLAMA_HOST)
print("api key set:", bool(pipeline_config.OLLAMA_API_KEY))

project root: /Users/natejly/Documents/GitHub/LLMS
models:
  claim_extraction: gemma4:31b
  claim_verification: gemma4:31b
  context_agent: gemma4:31b
  summary_generation: gemma4:31b
  final_review: gemma4:31b
ollama host: https://ollama.com
api key set: True

## Configuration

In [2]:
EHR_JSON_PATH = PROJECT_ROOT / "datasets" / "bquxjob_5dbe3bd2_19dae30f3cf.json"
NOTES_CSV_PATH = PROJECT_ROOT / "datasets" / "mimic-iii-ext-notes-1.0.0" / "notes.csv"
LABELS_CSV_PATH = PROJECT_ROOT / "datasets" / "mimic-iii-ext-notes-1.0.0" / "labels.csv"

BENCH_DIR = PROJECT_ROOT / "outputs" / "_bench"
BENCH_DIR.mkdir(parents=True, exist_ok=True)

NUM_CASES = 100
RANDOM_SEED = 7
ALLOW_VIOLATIONS = True       # don't drop a case just because the deterministic check found something
RESUME = True                 # reuse cached stage outputs across re-runs
ENABLE_CONTEXT_AGENT = False  # skip stage 4 in benchmark mode
SUMMARY_MIN_RATIO = 0.20
SUMMARY_MAX_RATIO = 0.30
BERTSCORE_MODEL = "roberta-large"

# Ollama: if OLLAMA_HOST is http://localhost:11434, do NOT send OLLAMA_API_KEY
# in the Authorization header (local Ollama returns 401). Keys are only used
# when OLLAMA_HOST=https://ollama.com unless you set OLLAMA_SEND_BEARER_TO_LOCAL=1.

print("work dir:", BENCH_DIR)
print("context agent:", "ON" if ENABLE_CONTEXT_AGENT else "OFF")
print(f"compression target: {SUMMARY_MIN_RATIO:.0%}-{SUMMARY_MAX_RATIO:.0%}")

work dir: /Users/natejly/Documents/GitHub/LLMS/outputs/_bench
context agent: OFF
compression target: 20%-30%

## Load and sample real cases (notes joined with structured EHR)

In [3]:
import random

all_cases = mimic.load_real_cases(
    ehr_json_path=EHR_JSON_PATH,
    notes_csv_path=NOTES_CSV_PATH,
    labels_csv_path=LABELS_CSV_PATH,
)
print(f"loaded {len(all_cases)} cases (notes joined with EHR by hadm_id)")

rng = random.Random(RANDOM_SEED)
sampled = rng.sample(all_cases, k=min(NUM_CASES, len(all_cases)))
for c in sampled:
    print(
        f"  {c.case_id:36s}  note_chars={len(c.note_text):5d}  "
        f"gold_concepts={len(c.gold_concepts):3d}  "
        f"diags={len(c.admission.get('all_diagnoses') or []):3d}  "
        f"procs={len(c.admission.get('all_procedures') or []):3d}"
    )

loaded 150 cases (notes joined with EHR by hadm_id)
  mimic-72907-165405-520384             note_chars= 3404  gold_concepts=  9  diags= 18  procs= 16
  mimic-29307-175627-318233             note_chars=  784  gold_concepts=  7  diags= 14  procs=  4
  mimic-47927-161682-717576             note_chars= 2592  gold_concepts=  7  diags= 18  procs=  5
  mimic-77013-141363-444743             note_chars= 2827  gold_concepts=  7  diags= 44  procs= 28
  mimic-54229-165594-598031             note_chars= 2337  gold_concepts=  9  diags= 48  procs= 16
  mimic-17539-153621-390912             note_chars= 4686  gold_concepts=  5  diags= 22  procs= 10
  mimic-85464-164726-466035             note_chars= 3032  gold_concepts=  9  diags= 34  procs=  6
  mimic-79877-185698-417636             note_chars= 1836  gold_concepts=  8  diags= 14  procs= 10
  mimic-94229-146659-541449             note_chars= 2700  gold_concepts=  6  diags= 35  procs=  9
  mimic-27022-196712-357513             note_chars= 1728  gold_concepts=  7  diags= 62  procs= 32
  mimic-86323-115774-624944             note_chars= 3975  gold_concepts= 12  diags= 19  procs=  7
  mimic-80791-181156-544481             note_chars= 2448  gold_concepts= 13  diags= 13  procs=  4
  mimic-98435-148017-646532             note_chars= 3021  gold_concepts=  7  diags= 20  procs=  4
  mimic-56201-104808-514628             note_chars= 2298  gold_concepts= 11  diags= 21  procs= 10
  mimic-59877-143996-528894             note_chars= 1963  gold_concepts=  5  diags= 15  procs=  4
  mimic-85999-134661-689561             note_chars= 3348  gold_concepts= 13  diags= 32  procs=  6
  mimic-58515-125506-439636             note_chars= 2266  gold_concepts= 10  diags= 19  procs= 11
  mimic-54229-165594-597675             note_chars= 3994  gold_concepts= 12  diags= 48  procs= 16
  mimic-49358-158550-701330             note_chars= 3360  gold_concepts=  9  diags=  6  procs=  5
  mimic-99613-177517-520810             note_chars= 2346  gold_concepts= 12  diags= 15  procs=  8
  mimic-1860-195382-329634              note_chars= 2464  gold_concepts= 14  diags= 24  procs= 11
  mimic-68956-147281-563910             note_chars= 3054  gold_concepts=  4  diags= 27  procs=  4
  mimic-78531-141755-649239             note_chars= 3065  gold_concepts=  7  diags=  8  procs=  7
  mimic-59113-169374-701538             note_chars= 1781  gold_concepts=  9  diags= 18  procs=  6
  mimic-88649-135549-588579             note_chars= 3063  gold_concepts= 18  diags= 22  procs= 10
  mimic-46320-113335-458422             note_chars= 2154  gold_concepts=  8  diags=156  procs=144
  mimic-30376-166341-399595             note_chars= 4780  gold_concepts=  3  diags= 21  procs= 16
  mimic-50847-123701-419476             note_chars= 3294  gold_concepts= 12  diags= 21  procs= 18
  mimic-79565-181839-427484             note_chars= 4222  gold_concepts= 13  diags= 26  procs= 11
  mimic-60919-137122-477434             note_chars= 2758  gold_concepts= 10  diags= 14  procs=  7
  mimic-49930-144435-540683             note_chars= 2971  gold_concepts=  7  diags= 16  procs= 20
  mimic-62795-173748-671473             note_chars= 3226  gold_concepts=  5  diags= 78  procs= 80
  mimic-46320-113335-462240             note_chars= 1217  gold_concepts=  9  diags=156  procs=144
  mimic-94414-170244-665535             note_chars= 2859  gold_concepts= 11  diags= 14  procs=  9
  mimic-21137-101950-1574               note_chars=12578  gold_concepts= 17  diags= 13  procs=  5
  mimic-99383-175736-674816             note_chars= 2275  gold_concepts=  5  diags= 18  procs= 13
  mimic-98220-173136-442600             note_chars= 2578  gold_concepts=  6  diags= 30  procs= 28
  mimic-85464-164726-465683             note_chars= 3066  gold_concepts=  8  diags= 34  procs=  6
  mimic-68589-152895-642898             note_chars= 2068  gold_concepts= 14  diags= 24  procs= 20
  mimic-91529-176840-424485             note_chars= 3955  gold_concepts=  9  diags= 12  procs=  8
  mimic-92525-141986-498276             note_chars= 2034  gold_concepts=  8  diags= 17  procs=  9
  mimic-73444-198874-514575             note_chars= 1160  gold_concepts=  7  diags= 22  procs= 16
  mimic-32303-185638-472970             note_chars= 1788  gold_concepts=  6  diags= 24  procs=  6
  mimic-54348-123562-690291             note_chars= 2061  gold_concepts= 10  diags= 30  procs= 11
  mimic-43126-132026-495137             note_chars= 2443  gold_concepts=  8  diags= 62  procs= 26
  mimic-41612-108873-496723             note_chars= 1485  gold_concepts= 12  diags= 22  procs=  9
  mimic-32504-149115-415025             note_chars= 1601  gold_concepts=  7  diags= 30  procs=  7
  mimic-17041-175730-1473               note_chars=17143  gold_concepts= 18  diags= 30  procs=  6
  mimic-53474-177016-556185             note_chars= 2794  gold_concepts=  7  diags= 20  procs=  4
  mimic-43937-146668-1263               note_chars=10660  gold_concepts= 18  diags= 18  procs=  4
  mimic-70206-162850-600430             note_chars= 2432  gold_concepts=  9  diags= 56  procs= 10
  mimic-70926-112660-521238             note_chars= 1272  gold_concepts=  3  diags= 11  procs=  5
  mimic-28126-161069-328226             note_chars= 2261  gold_concepts=  9  diags= 15  procs= 13
  mimic-28941-107962-328302             note_chars= 2394  gold_concepts=  7  diags= 39  procs= 13
  mimic-60337-121846-509076             note_chars= 2510  gold_concepts= 11  diags= 24  procs= 17
  mimic-66714-150541-472627             note_chars= 2521  gold_concepts= 10  diags= 33  procs= 13
  mimic-67512-105739-511563             note_chars= 1109  gold_concepts=  7  diags= 16  procs=  2
  mimic-50004-131407-447958             note_chars= 2143  gold_concepts=  8  diags= 17  procs=  5
  mimic-47974-163366-626355             note_chars= 2628  gold_concepts=  6  diags= 18  procs=  8
  mimic-60316-171649-545713             note_chars= 1993  gold_concepts=  9  diags= 16  procs=  7
  mimic-76514-125586-629067             note_chars= 3966  gold_concepts= 12  diags= 22  procs=  7
  mimic-49068-105351-489371             note_chars= 1810  gold_concepts=  5  diags= 28  procs=  9
  mimic-68589-152895-642741             note_chars= 2031  gold_concepts= 12  diags= 24  procs= 20
  mimic-91913-121738-523651             note_chars= 1889  gold_concepts= 12  diags= 18  procs= 13
  mimic-88078-105497-729882             note_chars= 3215  gold_concepts= 12  diags= 46  procs= 12
  mimic-52296-112991-422448             note_chars= 2633  gold_concepts=  6  diags= 56  procs= 32
  mimic-17997-186252-1197               note_chars= 6615  gold_concepts= 11  diags=  9  procs=  1
  mimic-74701-182133-728280             note_chars= 2702  gold_concepts=  5  diags= 39  procs= 13
  mimic-77013-141363-443428             note_chars= 2626  gold_concepts=  7  diags= 44  procs= 28
  mimic-92277-173474-1282               note_chars=16139  gold_concepts= 20  diags= 18  procs=  5
  mimic-46320-113335-462346             note_chars= 1157  gold_concepts=  5  diags=156  procs=144
  mimic-96621-138277-705450             note_chars= 2752  gold_concepts=  7  diags= 13  procs=  5
  mimic-41795-138132-683600             note_chars= 2643  gold_concepts=  6  diags= 44  procs= 12
  mimic-46320-113335-462509             note_chars= 1644  gold_concepts=  9  diags=156  procs=144
  mimic-20421-168753-346921             note_chars= 3467  gold_concepts=  5  diags= 24  procs=  8
  mimic-78481-143054-640463             note_chars= 2594  gold_concepts=  9  diags= 23  procs= 21
  mimic-97330-197571-437958             note_chars= 2114  gold_concepts=  8  diags= 23  procs= 12
  mimic-46105-126246-529623             note_chars= 4893  gold_concepts= 11  diags= 23  procs=  2
  mimic-47829-175022-600943             note_chars= 2733  gold_concepts=  9  diags= 17  procs= 17
  mimic-64407-175035-619126             note_chars= 2071  gold_concepts=  8  diags= 17  procs=  5
  mimic-86585-123444-546150             note_chars= 2785  gold_concepts= 14  diags= 13  procs=  4
  mimic-43126-132026-495933             note_chars= 3548  gold_concepts=  4  diags= 62  procs= 26
  mimic-99883-150755-651791             note_chars= 1275  gold_concepts=  8  diags= 10  procs=  5
  mimic-82313-116027-681825             note_chars= 2210  gold_concepts=  9  diags= 31  procs= 13
  mimic-60739-180716-643550             note_chars= 1640  gold_concepts=  9  diags= 44  procs= 20
  mimic-88078-105497-730292             note_chars= 1454  gold_concepts= 10  diags= 46  procs= 12
  mimic-64798-160505-695419             note_chars= 6001  gold_concepts=  4  diags= 38  procs= 10
  mimic-62795-173748-671542             note_chars= 3231  gold_concepts=  5  diags= 78  procs= 80
  mimic-80658-117314-669605             note_chars= 2297  gold_concepts=  8  diags= 23  procs=  8
  mimic-52296-112991-422543             note_chars= 1857  gold_concepts=  8  diags= 56  procs= 32
  mimic-49496-112342-514701             note_chars= 2908  gold_concepts= 12  diags= 25  procs=  7
  mimic-27022-196712-355983             note_chars= 1851  gold_concepts=  4  diags= 62  procs= 32
  mimic-41125-127965-574617             note_chars= 2534  gold_concepts=  8  diags= 11  procs=  5
  mimic-60106-136013-660723             note_chars= 2122  gold_concepts=  7  diags= 24  procs=  7
  mimic-76541-139921-737066             note_chars= 2784  gold_concepts=  9  diags= 28  procs=  9
  mimic-83607-156758-631634             note_chars= 2976  gold_concepts=  5  diags= 26  procs= 15
  mimic-25326-191645-386337             note_chars=  865  gold_concepts= 10  diags= 54  procs= 26
  mimic-56635-192782-481041             note_chars= 3841  gold_concepts= 15  diags= 23  procs= 20
  mimic-68135-163192-486433             note_chars= 1297  gold_concepts=  3  diags= 26  procs=  9
  mimic-9461-156692-597                 note_chars= 6460  gold_concepts= 12  diags=  9  procs= 10

## Materialize FHIR + notes and run the pipeline

In [ ]:
import traceback

from ehr_pipeline.ollama_client import OllamaError

# Reset the Ollama client singleton so any config/env changes take effect.
from ehr_pipeline import ollama_client as _oc
_oc._client = None
_oc._client_fingerprint = None

# Stage labels for the debug table (format placeholders filled at runtime).
_STAGE_LABELS = {
    "stage1_evidence":   "S1  Evidence store      [deterministic]",
    "stage2_extract":    "S2  Claim extraction    [LLM: {claim_extraction}]",
    "stage3_verify":     "S3  Claim verification  [LLM: {claim_verification}]",
    "stage4_context":    "S4  Context agent       [LLM: {context_agent}]",
    "stage5_fact_sheet": "S5  Fact sheet          [deterministic]",
    "stage6_summarize":  "S6  Summary generation  [LLM: {summary_generation}]",
    "stage7_check":      "S7  Deterministic check [deterministic]",
    "stage8_review":     "S8  Final LLM review    [LLM: {final_review}]",
}

def _print_stage_debug(pipe_result):
    """Print a per-stage timing table for one pipeline run."""
    m = {
        "claim_extraction":   pipeline_config.MODELS.claim_extraction,
        "claim_verification": pipeline_config.MODELS.claim_verification,
        "context_agent":      pipeline_config.MODELS.context_agent,
        "summary_generation": pipeline_config.MODELS.summary_generation,
        "final_review":       pipeline_config.MODELS.final_review,
    }
    W = 60
    print(f"  ┌{'─'*W}┬──────────┬────────┐")
    print(f"  │ {'Stage':<{W-2}} │  Time(s) │ Status │")
    print(f"  ├{'─'*W}┼──────────┼────────┤")
    for t in pipe_result.timings:
        label = _STAGE_LABELS.get(t.name, t.name).format(**m)
        status = "SKIP " if t.skipped else "ok   "
        print(f"  │ {label:<{W-2}} │ {t.seconds:>8.2f} │ {status:<6} │")
    total = sum(t.seconds for t in pipe_result.timings)
    print(f"  ├{'─'*W}┼──────────┼────────┤")
    print(f"  │ {'TOTAL':<{W-2}} │ {total:>8.2f} │        │")
    print(f"  └{'─'*W}┴──────────┴────────┘")
    comp = pipe_result.compression
    if comp:
        band = "IN BAND ✓" if comp.in_target_band else "OUT OF BAND ✗"
        print(f"  compression: {comp.achieved_ratio:.2f}  "
              f"({comp.summary_chars} / {comp.note_chars} chars)  [{band}]")
    # Deterministic check result
    s7 = "PASS ✓" if pipe_result.check_passed else "FAIL ✗"
    print(f"  S7 det. check : {s7}")

    # LLM review result
    cc = pipe_result.review_concern_counts
    s8 = "PASS ✓" if pipe_result.review_passed else "FAIL ✗ (high-severity concern)"
    print(f"  S8 LLM review : {s8}  "
          f"(high={cc.get('high',0)}  medium={cc.get('medium',0)}  low={cc.get('low',0)})")
    for c in (getattr(pipe_result, '_review', None) and [] or []):
        pass  # concerns printed below if desired

    if pipe_result.input_note_path:
        print(f"  input note    : {pipe_result.input_note_path}")
    if pipe_result.summary_path:
        print(f"  summary       : {pipe_result.summary_path}")
    if pipe_result.revised_summary_path:
        rcp = pipe_result.revised_check_passed
        rcp_str = "check PASS ✓" if rcp else ("check FAIL ✗" if rcp is False else "not checked")
        print(f"  revised summ. : {pipe_result.revised_summary_path}  [{rcp_str}]")
    else:
        print(f"  revised summ. : (none — no applicable revisions)")


def _strip_citations_for_metrics(text: str) -> str:
    return strip_citations_for_metrics(text)


def _benchmark_compression(summary_text: str, note_chars: int) -> tuple[int, float, bool]:
    safe_note_chars = max(int(note_chars), 1)
    summary_chars = len(summary_text)
    ratio = summary_chars / safe_note_chars
    return summary_chars, ratio, SUMMARY_MIN_RATIO <= ratio <= SUMMARY_MAX_RATIO


def _load_cached_result(case, out_dir: Path):
    """Try to reconstruct a benchmark result dict from cached pipeline outputs.

    Returns the result dict if audit.json exists (i.e. the pipeline ran to
    completion for this case), otherwise returns None.
    """
    audit_path = out_dir / "audit.json"
    if not audit_path.exists():
        return None

    import json as _j
    audit = _j.loads(audit_path.read_text("utf-8"))

    # Determine which summary to use as the prediction.
    summary_path = out_dir / "summary.md"
    revised_path = out_dir / "summary_revised.md"

    comp = audit.get("compression", {})
    check = audit.get("check_report", {})
    review = audit.get("review", {})
    cc = audit.get("review_concern_counts", {})
    ps = audit.get("patient_summary")
    revised_check = audit.get("revised_check_passed")

    if audit.get("stage_failed"):
        prediction = ""
        prediction_source = "none"
    elif revised_path.exists() and revised_check:
        prediction = revised_path.read_text("utf-8")
        prediction_source = "revised"
    elif summary_path.exists():
        prediction = summary_path.read_text("utf-8")
        prediction_source = "original"
    else:
        prediction = ""
        prediction_source = "none"

    patient_md_path = out_dir / "patient_summary.md"
    patient_md = patient_md_path.read_text("utf-8") if patient_md_path.exists() else ""

    timings = audit.get("timings", [])
    total_seconds = sum(t.get("seconds", 0) for t in timings)

    reference = mimic.real_case_reference_summary(case)
    gold_set = mimic.real_case_gold_entities(case)
    note_chars = comp.get("note_chars", len(case.note_text))
    prediction = _strip_citations_for_metrics(prediction)
    summary_chars, compression_ratio, compression_in_band = _benchmark_compression(prediction, note_chars)

    return {
        "case_id": case.case_id,
        "check_passed": check.get("passed", False) if check else (audit.get("stage_failed") is None),
        "review_passed": review.get("passed", True) if review else True,
        "review_high": cc.get("high", 0),
        "review_medium": cc.get("medium", 0),
        "review_low": cc.get("low", 0),
        "prediction_source": prediction_source,
        "context_agent_on": audit.get("context_agent_enabled", ENABLE_CONTEXT_AGENT),
        "prediction": prediction,
        "reference": reference,
        "gold_entities": gold_set,
        "output_dir": str(out_dir),
        "total_seconds": total_seconds,
        "note_chars": note_chars,
        "summary_chars": summary_chars,
        "compression_ratio": compression_ratio,
        "compression_in_band": compression_in_band,
        "patient_summary": patient_md,
        "patient_fk_grade": ps.get("fk_grade") if ps else None,
        "patient_fk_words": ps.get("fk_words", 0) if ps else 0,
        "patient_fk_sentences": ps.get("fk_sentences", 0) if ps else 0,
        "patient_chars": ps.get("chars", 0) if ps else 0,
        "patient_in_target_band": ps.get("in_target_band", False) if ps else False,
    }


results = []
cached_count = 0
for case in sampled:
    bundle_path, notes_dir = mimic.materialize_real_case(case, BENCH_DIR)
    out_dir = pipeline_config.output_dir(case.case_id)

    print(f"\n{'='*66}")
    print(f"  CASE: {case.case_id}")
    print(f"  note_chars={len(case.note_text)}  gold_concepts={len(case.gold_concepts)}")
    print(f"{'='*66}")

    # Skip cases that already have a completed pipeline run on disk.
    cached = _load_cached_result(case, out_dir)
    if cached is not None:
        cached_count += 1
        band = "IN BAND ✓" if cached["compression_in_band"] else "OUT OF BAND ✗"
        print(f"  *** CACHED — skipping pipeline (audit.json exists) ***")
        print(f"  compression: {cached['compression_ratio']:.2f}  "
              f"({cached['summary_chars']} / {cached['note_chars']} chars)  [{band}]")
        print(f"  prediction source: {cached['prediction_source']}")
        results.append(cached)
        continue

    try:
        pipe_result = run_pipeline(
            case_id=case.case_id,
            bundle_path=bundle_path,
            notes_dir=notes_dir,
            resume=RESUME,
            allow_violations=ALLOW_VIOLATIONS,
            enable_context_agent=ENABLE_CONTEXT_AGENT,
            summary_min_ratio=SUMMARY_MIN_RATIO,
            summary_max_ratio=SUMMARY_MAX_RATIO,
        )
    except OllamaError as exc:
        print(f"  ERROR: {exc}")
        if exc.status_code == 401:
            print("  Hint: local Ollama rejects Bearer tokens — set OLLAMA_HOST=https://ollama.com"
                  " or unset OLLAMA_API_KEY for local runs.")
        elif exc.status_code == 404:
            print("  Hint: model not found. Check MODELS in ehr_pipeline/config.py.")
        traceback.print_exc()
        reference = mimic.real_case_reference_summary(case)
        gold_set = mimic.real_case_gold_entities(case)
        results.append({
            "case_id": case.case_id,
            "check_passed": False,
            "context_agent_on": ENABLE_CONTEXT_AGENT,
            "prediction": "",
            "reference": reference,
            "gold_entities": gold_set,
            "output_dir": str(pipeline_config.output_dir(case.case_id)),
            "total_seconds": 0.0,
            "note_chars": len(case.note_text),
            "summary_chars": 0,
            "compression_ratio": 0.0,
            "compression_in_band": False,
            "error": str(exc),
        })
        continue

    _print_stage_debug(pipe_result)

    if pipe_result.summary_path is None:
        print(f"\n  WARNING: no summary emitted (check_passed=False, "
              f"audit at {pipe_result.audit_path})")
        prediction = ""
        prediction_source = "none"
    elif pipe_result.revised_summary_path and pipe_result.revised_check_passed:
        # Use the revised summary when it exists AND passes the deterministic check.
        prediction = pipe_result.revised_summary_path.read_text(encoding="utf-8")
        prediction_source = "revised"
    else:
        prediction = pipe_result.summary_path.read_text(encoding="utf-8")
        prediction_source = "original"

    prediction = _strip_citations_for_metrics(prediction)
    print(f"  benchmarking  : using {prediction_source} summary for metrics (citations stripped)")

    reference = mimic.real_case_reference_summary(case)
    gold_set = mimic.real_case_gold_entities(case)

    comp = pipe_result.compression
    note_chars = comp.note_chars if comp else len(case.note_text)
    summary_chars, compression_ratio, compression_in_band = _benchmark_compression(prediction, note_chars)
    cc = pipe_result.review_concern_counts
    ps = pipe_result.patient_summary
    patient_md = ps.path.read_text(encoding="utf-8") if ps and ps.path.exists() else ""
    results.append({
        "case_id": case.case_id,
        "check_passed": pipe_result.check_passed,
        "review_passed": pipe_result.review_passed,
        "review_high": cc.get("high", 0),
        "review_medium": cc.get("medium", 0),
        "review_low": cc.get("low", 0),
        "prediction_source": prediction_source,   # "original" | "revised" | "none"
        "context_agent_on": pipe_result.context_agent_enabled,
        "prediction": prediction,
        "reference": reference,
        "gold_entities": gold_set,
        "output_dir": str(pipe_result.output_dir),
        "total_seconds": sum(t.seconds for t in pipe_result.timings),
        "note_chars": note_chars,
        "summary_chars": summary_chars,
        "compression_ratio": compression_ratio,
        "compression_in_band": compression_in_band,
        # Stage 9 — patient-facing summary (independent text + readability score)
        "patient_summary": patient_md,
        "patient_fk_grade": ps.fk_grade if ps else None,
        "patient_fk_words": ps.fk_words if ps else 0,
        "patient_fk_sentences": ps.fk_sentences if ps else 0,
        "patient_chars": ps.chars if ps else 0,
        "patient_in_target_band": ps.in_target_band if ps else False,
    })

print(f"\n{'='*66}")
print(f"  DONE: {len(results)} cases  ({cached_count} cached, {len(results) - cached_count} fresh)")
print(f"{'='*66}")

2026-05-03 03:04:49,318 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-72907-165405-520384
2026-05-03 03:04:49,322 INFO ehr_pipeline.stages.s1_evidence:   wrote 46 evidence items (35 structured, 11 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/evidence_store.json
2026-05-03 03:04:49,322 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:04:49,323 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

==================================================================
  CASE: mimic-72907-165405-520384
  note_chars=3404  gold_concepts=9
==================================================================

2026-05-03 03:07:59,037 INFO ehr_pipeline.stages.s2_extract:   extracted 59 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/claims.json
2026-05-03 03:07:59,040 INFO ehr_pipeline.runtime:   stage2_extract done in 189.72s
2026-05-03 03:07:59,041 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 59 claims
2026-05-03 03:08:36,760 INFO ehr_pipeline.stages.s3_verify:   {'verified': 17, 'contradicted': 0, 'unsupported': 42} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/verifications.json
2026-05-03 03:08:36,766 INFO ehr_pipeline.runtime:   stage3_verify done in 37.73s
2026-05-03 03:08:36,768 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:08:36,797 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:08:36,850 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 48, 'medications': 2, 'labs': 0, 'vitals': 1, 'plan': 0}
2026-05-03 03:08:36,851 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.05s
2026-05-03 03:08:36,856 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:08:47,099 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/patient_summary.md (1385 chars, FK grade=7.13, in_band=True)
2026-05-03 03:08:47,111 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 10.26s
2026-05-03 03:08:47,112 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:09:00,946 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/summary.md (1445 chars, ratio=0.42, target=0.20-0.30, in_band=False)
2026-05-03 03:09:01,176 INFO ehr_pipeline.runtime:   stage6_summarize done in 14.04s
2026-05-03 03:09:01,439 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:09:01,804 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/check_report.json
2026-05-03 03:09:02,190 INFO ehr_pipeline.runtime:   stage7_check done in 0.75s
2026-05-03 03:09:02,196 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:09:15,848 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/review.json
2026-05-03 03:09:15,850 INFO ehr_pipeline.runtime:   stage8_review done in 13.65s
2026-05-03 03:09:15,851 INFO ehr_pipeline.pipeline:   applied revision: 'Chronic conditions include essential hypertension [E:cond:15' → 'Chronic conditions include essential hypertension [E:cond:15'
2026-05-03 03:09:15,851 INFO ehr_pipeline.pipeline:   applied revision: 'Surgical history includes left [E:proc:1] and right hemicole' → '_Not documented._'
2026-05-03 03:09:15,852 INFO ehr_pipeline.pipeline:   applied revision: 'History of ERCP [E:note:row520384:1], elective lap chole [E:' → ''
2026-05-03 03:09:15,854 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/summary_revised.md
2026-05-03 03:09:15,855 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:09:15,858 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/check_report_revised.json
2026-05-03 03:09:15,859 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:09:15,866 INFO ehr_pipeline.pipeline: Saved input note (784 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/input_note.txt
2026-05-03 03:09:15,866 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-29307-175627-318233
2026-05-03 03:09:15,869 INFO ehr_pipeline.stages.s1_evidence:   wrote 28 evidence items (19 structured, 9 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/evidence_store.json
2026-05-03 03:09:15,870 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:09:15,871 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   189.72 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    37.73 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.05 │ ok     │
  │ stage9_patient_summary                                     │    10.26 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    14.04 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.75 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    13.65 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   266.20 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.42  (1445 / 3404 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-72907-165405-520384/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-29307-175627-318233
  note_chars=784  gold_concepts=7
==================================================================

2026-05-03 03:11:02,265 INFO ehr_pipeline.stages.s2_extract:   extracted 23 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/claims.json
2026-05-03 03:11:02,270 INFO ehr_pipeline.runtime:   stage2_extract done in 106.40s
2026-05-03 03:11:02,271 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 23 claims
2026-05-03 03:12:19,349 INFO ehr_pipeline.stages.s3_verify:   {'verified': 19, 'contradicted': 0, 'unsupported': 4} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/verifications.json
2026-05-03 03:12:19,353 INFO ehr_pipeline.runtime:   stage3_verify done in 77.08s
2026-05-03 03:12:19,353 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:12:19,356 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:12:19,357 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 28, 'medications': 3, 'labs': 1, 'vitals': 3, 'plan': 2}
2026-05-03 03:12:19,358 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:12:19,358 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:13:29,150 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/patient_summary.md (1490 chars, FK grade=6.51, in_band=False)
2026-05-03 03:13:29,154 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 69.80s
2026-05-03 03:13:29,155 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:13:38,166 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/summary.md (500 chars, ratio=0.64, target=0.20-0.30, in_band=False)
2026-05-03 03:13:38,168 INFO ehr_pipeline.runtime:   stage6_summarize done in 9.01s
2026-05-03 03:13:38,171 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:13:38,174 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/check_report.json
2026-05-03 03:13:38,174 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:13:38,175 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:13:46,245 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/review.json
2026-05-03 03:13:46,250 INFO ehr_pipeline.runtime:   stage8_review done in 8.07s
2026-05-03 03:13:46,252 INFO ehr_pipeline.pipeline:   applied revision: 'Methylpred [E:note:row318233:4], vanco, and levaquin [E:note' → 'Methylpred [E:note:row318233:4], vanco [E:note:row318233:8],'
2026-05-03 03:13:46,258 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/summary_revised.md
2026-05-03 03:13:46,259 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:13:46,260 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/check_report_revised.json
2026-05-03 03:13:46,261 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:13:46,350 INFO ehr_pipeline.pipeline: Saved input note (2592 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/input_note.txt
2026-05-03 03:13:46,357 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-47927-161682-717576
2026-05-03 03:13:46,403 INFO ehr_pipeline.stages.s1_evidence:   wrote 36 evidence items (24 structured, 12 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/evidence_store.json
2026-05-03 03:13:46,405 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.05s
2026-05-03 03:13:46,408 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   106.40 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    77.08 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    69.80 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     9.01 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     8.07 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   270.37 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.64  (500 / 784 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-29307-175627-318233/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-47927-161682-717576
  note_chars=2592  gold_concepts=7
==================================================================

2026-05-03 03:15:52,014 INFO ehr_pipeline.stages.s2_extract:   extracted 56 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/claims.json
2026-05-03 03:15:52,018 INFO ehr_pipeline.runtime:   stage2_extract done in 125.61s
2026-05-03 03:15:52,020 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 56 claims
2026-05-03 03:19:15,450 INFO ehr_pipeline.stages.s3_verify:   {'verified': 23, 'contradicted': 1, 'unsupported': 32} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/verifications.json
2026-05-03 03:19:15,453 INFO ehr_pipeline.runtime:   stage3_verify done in 203.43s
2026-05-03 03:19:15,454 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:19:15,456 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:19:15,458 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 38, 'medications': 3, 'labs': 1, 'vitals': 3, 'plan': 0}
2026-05-03 03:19:15,458 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:19:15,459 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:19:27,967 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/patient_summary.md (1714 chars, FK grade=5.63, in_band=False)
2026-05-03 03:19:27,968 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 12.51s
2026-05-03 03:19:27,969 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:20:11,476 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/summary.md (985 chars, ratio=0.38, target=0.20-0.30, in_band=False)
2026-05-03 03:20:11,477 INFO ehr_pipeline.runtime:   stage6_summarize done in 43.51s
2026-05-03 03:20:11,479 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:20:11,482 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/check_report.json
2026-05-03 03:20:11,484 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:20:11,485 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:20:33,515 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/review.json
2026-05-03 03:20:33,517 INFO ehr_pipeline.runtime:   stage8_review done in 22.03s
2026-05-03 03:20:33,518 INFO ehr_pipeline.pipeline:   applied revision: 'Other conditions include SLE (severe), cryoglobulinemia vasc' → 'Other conditions include systemic lupus erythematosus and ca'
2026-05-03 03:20:33,518 INFO ehr_pipeline.pipeline:   applied revision: 'Additional issues: coagulation defects, drug withdrawal, opi' → 'Additional issues: coagulation defects, drug withdrawal, opi'
2026-05-03 03:20:33,520 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/summary_revised.md
2026-05-03 03:20:33,521 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:20:33,524 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/check_report_revised.json
2026-05-03 03:20:33,525 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:20:33,533 INFO ehr_pipeline.pipeline: Saved input note (2827 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/input_note.txt
2026-05-03 03:20:33,534 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-77013-141363-444743
2026-05-03 03:20:33,538 INFO ehr_pipeline.stages.s1_evidence:   wrote 116 evidence items (73 structured, 43 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/evidence_store.json
2026-05-03 03:20:33,539 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:20:33,540 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.05 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   125.61 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   203.43 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    12.51 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    43.51 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    22.03 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   407.15 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.38  (985 / 2592 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47927-161682-717576/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-77013-141363-444743
  note_chars=2827  gold_concepts=7
==================================================================

2026-05-03 03:23:11,642 INFO ehr_pipeline.stages.s2_extract:   extracted 46 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/claims.json
2026-05-03 03:23:11,645 INFO ehr_pipeline.runtime:   stage2_extract done in 158.11s
2026-05-03 03:23:11,646 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 46 claims
2026-05-03 03:24:09,259 INFO ehr_pipeline.stages.s3_verify:   {'verified': 33, 'contradicted': 0, 'unsupported': 13} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/verifications.json
2026-05-03 03:24:09,262 INFO ehr_pipeline.runtime:   stage3_verify done in 57.62s
2026-05-03 03:24:09,263 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:24:09,266 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:24:09,269 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 39, 'medications': 9, 'labs': 8, 'vitals': 11, 'plan': 0}
2026-05-03 03:24:09,269 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:24:09,270 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:24:31,472 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/patient_summary.md (2129 chars, FK grade=8.70, in_band=False)
2026-05-03 03:24:31,478 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 22.21s
2026-05-03 03:24:31,479 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:25:01,895 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/summary.md (1521 chars, ratio=0.54, target=0.20-0.30, in_band=False)
2026-05-03 03:25:01,897 INFO ehr_pipeline.runtime:   stage6_summarize done in 30.42s
2026-05-03 03:25:01,899 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:25:01,903 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/check_report.json
2026-05-03 03:25:01,904 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:25:01,904 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:25:28,007 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/review.json
2026-05-03 03:25:28,008 INFO ehr_pipeline.runtime:   stage8_review done in 26.10s
2026-05-03 03:25:28,009 INFO ehr_pipeline.pipeline:   applied revision: 'Additional diagnoses include hospital acquired pneumonia [E:' → 'Additional diagnoses include alcohol withdrawal [E:cond:9][E'
2026-05-03 03:25:28,010 INFO ehr_pipeline.pipeline:   applied revision: 'Nutritional deficits include beriberi [E:cond:1][E:cond:2], ' → 'Nutritional deficits include beriberi [E:cond:1][E:cond:2] a'
2026-05-03 03:25:28,012 INFO ehr_pipeline.pipeline:   applied revision: 'Neurological findings include quadriplegia [E:cond:13][E:con' → 'Neurological findings include quadriplegia [E:cond:13][E:con'
2026-05-03 03:25:28,015 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/summary_revised.md
2026-05-03 03:25:28,016 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:25:28,018 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/check_report_revised.json
2026-05-03 03:25:28,019 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:25:28,027 INFO ehr_pipeline.pipeline: Saved input note (2337 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/input_note.txt
2026-05-03 03:25:28,028 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-54229-165594-598031
2026-05-03 03:25:28,032 INFO ehr_pipeline.stages.s1_evidence:   wrote 96 evidence items (65 structured, 31 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/evidence_store.json
2026-05-03 03:25:28,032 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:25:28,033 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   158.11 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    57.62 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    22.21 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    30.42 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    26.10 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   294.46 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.54  (1521 / 2827 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-444743/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-54229-165594-598031
  note_chars=2337  gold_concepts=9
==================================================================

2026-05-03 03:27:37,632 INFO ehr_pipeline.stages.s2_extract:   extracted 41 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/claims.json
2026-05-03 03:27:37,636 INFO ehr_pipeline.runtime:   stage2_extract done in 129.60s
2026-05-03 03:27:37,638 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 41 claims
2026-05-03 03:28:19,548 INFO ehr_pipeline.stages.s3_verify:   {'verified': 24, 'contradicted': 0, 'unsupported': 17} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/verifications.json
2026-05-03 03:28:19,549 INFO ehr_pipeline.runtime:   stage3_verify done in 41.91s
2026-05-03 03:28:19,549 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:28:19,552 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:28:19,555 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 39, 'medications': 5, 'labs': 0, 'vitals': 4, 'plan': 6}
2026-05-03 03:28:19,555 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:28:19,556 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:28:43,797 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/patient_summary.md (2133 chars, FK grade=6.10, in_band=False)
2026-05-03 03:28:43,799 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 24.24s
2026-05-03 03:28:43,800 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:29:01,716 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/summary.md (1441 chars, ratio=0.62, target=0.20-0.30, in_band=False)
2026-05-03 03:29:01,716 INFO ehr_pipeline.runtime:   stage6_summarize done in 17.92s
2026-05-03 03:29:01,718 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:29:01,721 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=23 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/check_report.json
2026-05-03 03:29:01,722 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:29:01,722 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:29:19,717 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/review.json
2026-05-03 03:29:19,718 INFO ehr_pipeline.runtime:   stage8_review done in 18.00s
2026-05-03 03:29:19,718 INFO ehr_pipeline.pipeline:   applied revision: 'Type II diabetes on insulin [E:cond:29][E:cond:30][E:cond:47' → 'Type II diabetes [E:cond:29][E:cond:30][E:cond:47][E:cond:48'
2026-05-03 03:29:19,720 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/summary_revised.md
2026-05-03 03:29:19,721 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:29:19,724 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=23 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/check_report_revised.json
2026-05-03 03:29:19,724 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:29:19,732 INFO ehr_pipeline.pipeline: Saved input note (4686 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/input_note.txt
2026-05-03 03:29:19,733 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-17539-153621-390912
2026-05-03 03:29:19,737 INFO ehr_pipeline.stages.s1_evidence:   wrote 92 evidence items (33 structured, 59 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/evidence_store.json
2026-05-03 03:29:19,737 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:29:19,738 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   129.60 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    41.91 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    24.24 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    17.92 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    18.00 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   231.68 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.62  (1441 / 2337 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-598031/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-17539-153621-390912
  note_chars=4686  gold_concepts=5
==================================================================

2026-05-03 03:30:37,710 INFO ehr_pipeline.stages.s2_extract:   extracted 36 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/claims.json
2026-05-03 03:30:37,722 INFO ehr_pipeline.runtime:   stage2_extract done in 77.98s
2026-05-03 03:30:37,724 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 36 claims
2026-05-03 03:33:03,046 INFO ehr_pipeline.stages.s3_verify:   {'verified': 27, 'contradicted': 0, 'unsupported': 9} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/verifications.json
2026-05-03 03:33:03,049 INFO ehr_pipeline.runtime:   stage3_verify done in 145.32s
2026-05-03 03:33:03,050 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:33:03,052 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:33:03,055 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 46, 'medications': 7, 'labs': 0, 'vitals': 3, 'plan': 3}
2026-05-03 03:33:03,055 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:33:03,057 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:33:25,307 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/patient_summary.md (1894 chars, FK grade=7.55, in_band=True)
2026-05-03 03:33:25,402 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 22.35s
2026-05-03 03:33:25,404 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:33:46,243 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/summary.md (1984 chars, ratio=0.42, target=0.20-0.30, in_band=False)
2026-05-03 03:33:46,248 INFO ehr_pipeline.runtime:   stage6_summarize done in 20.84s
2026-05-03 03:33:46,250 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:33:46,253 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/check_report.json
2026-05-03 03:33:46,254 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:33:46,254 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:33:48,625 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/review.json
2026-05-03 03:33:48,626 INFO ehr_pipeline.runtime:   stage8_review done in 2.37s
2026-05-03 03:33:48,626 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 03:33:48,635 INFO ehr_pipeline.pipeline: Saved input note (3032 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/input_note.txt
2026-05-03 03:33:48,636 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-85464-164726-466035
2026-05-03 03:33:48,641 INFO ehr_pipeline.stages.s1_evidence:   wrote 80 evidence items (41 structured, 39 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/evidence_store.json
2026-05-03 03:33:48,641 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 03:33:48,642 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    77.98 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   145.32 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    22.35 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    20.84 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     2.37 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   268.87 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.42  (1984 / 4686 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17539-153621-390912/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-85464-164726-466035
  note_chars=3032  gold_concepts=9
==================================================================

2026-05-03 03:35:08,565 INFO ehr_pipeline.stages.s2_extract:   extracted 31 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/claims.json
2026-05-03 03:35:08,566 INFO ehr_pipeline.runtime:   stage2_extract done in 79.92s
2026-05-03 03:35:08,567 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 31 claims
2026-05-03 03:37:26,766 INFO ehr_pipeline.stages.s3_verify:   {'verified': 19, 'contradicted': 0, 'unsupported': 12} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/verifications.json
2026-05-03 03:37:26,777 INFO ehr_pipeline.runtime:   stage3_verify done in 138.21s
2026-05-03 03:37:26,779 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:37:26,786 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:37:26,789 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 27, 'medications': 7, 'labs': 2, 'vitals': 3, 'plan': 0}
2026-05-03 03:37:26,789 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:37:26,790 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:37:42,181 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/patient_summary.md (1617 chars, FK grade=5.76, in_band=False)
2026-05-03 03:37:42,182 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.39s
2026-05-03 03:37:42,183 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:37:57,333 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/summary.md (1548 chars, ratio=0.51, target=0.20-0.30, in_band=False)
2026-05-03 03:37:57,336 INFO ehr_pipeline.runtime:   stage6_summarize done in 15.15s
2026-05-03 03:37:57,338 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:37:57,341 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/check_report.json
2026-05-03 03:37:57,342 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:37:57,343 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:38:09,949 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/review.json
2026-05-03 03:38:09,950 INFO ehr_pipeline.runtime:   stage8_review done in 12.61s
2026-05-03 03:38:09,951 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with STEMI (inferior wall) [E:cond:1][E:con' → 'Patient presents with acute myocardial infarction of the inf'
2026-05-03 03:38:09,951 INFO ehr_pipeline.pipeline:   applied revision: 'Other diagnoses include UTI [E:cond:11][E:cond:12][E:note:ro' → 'Other diagnoses include UTI [E:cond:11][E:cond:12][E:note:ro'
2026-05-03 03:38:09,953 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/summary_revised.md
2026-05-03 03:38:09,954 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:38:09,956 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/check_report_revised.json
2026-05-03 03:38:09,957 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:38:09,965 INFO ehr_pipeline.pipeline: Saved input note (1836 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/input_note.txt
2026-05-03 03:38:09,966 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-79877-185698-417636
2026-05-03 03:38:09,969 INFO ehr_pipeline.stages.s1_evidence:   wrote 42 evidence items (25 structured, 17 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/evidence_store.json
2026-05-03 03:38:09,969 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:38:09,970 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    79.92 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   138.21 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.39 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    15.15 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.61 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   261.30 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.51  (1548 / 3032 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-466035/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-79877-185698-417636
  note_chars=1836  gold_concepts=8
==================================================================

2026-05-03 03:39:15,281 INFO ehr_pipeline.stages.s2_extract:   extracted 33 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/claims.json
2026-05-03 03:39:15,286 INFO ehr_pipeline.runtime:   stage2_extract done in 65.32s
2026-05-03 03:39:15,287 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 33 claims
2026-05-03 03:43:00,470 INFO ehr_pipeline.stages.s3_verify:   {'verified': 24, 'contradicted': 0, 'unsupported': 9} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/verifications.json
2026-05-03 03:43:00,472 INFO ehr_pipeline.runtime:   stage3_verify done in 225.18s
2026-05-03 03:43:00,473 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:43:00,474 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:43:00,477 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 42, 'medications': 2, 'labs': 1, 'vitals': 2, 'plan': 1}
2026-05-03 03:43:00,479 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:43:00,480 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:43:20,572 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/patient_summary.md (1656 chars, FK grade=7.56, in_band=True)
2026-05-03 03:43:20,584 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 20.10s
2026-05-03 03:43:20,585 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:43:29,779 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/summary.md (855 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 03:43:29,780 INFO ehr_pipeline.runtime:   stage6_summarize done in 9.20s
2026-05-03 03:43:29,783 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:43:29,787 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/check_report.json
2026-05-03 03:43:29,788 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 03:43:29,789 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:43:46,652 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/review.json
2026-05-03 03:43:46,655 INFO ehr_pipeline.runtime:   stage8_review done in 16.87s
2026-05-03 03:43:46,655 INFO ehr_pipeline.pipeline:   applied revision: 'Pneumonia [E:cond:1], HCV cirrhosis with hepatic coma [E:con' → 'Pneumonia [E:cond:1], HCV cirrhosis with hepatic coma [E:con'
2026-05-03 03:43:46,656 INFO ehr_pipeline.pipeline:   applied revision: 'Patient is somnolent, non-verbal, and lethargic [E:note:row4' → ''
2026-05-03 03:43:46,675 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/summary_revised.md
2026-05-03 03:43:46,682 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:43:46,686 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/check_report_revised.json
2026-05-03 03:43:46,686 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:43:46,733 INFO ehr_pipeline.pipeline: Saved input note (2700 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/input_note.txt
2026-05-03 03:43:46,742 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-94229-146659-541449
2026-05-03 03:43:46,862 INFO ehr_pipeline.stages.s1_evidence:   wrote 69 evidence items (45 structured, 24 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/evidence_store.json
2026-05-03 03:43:46,871 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.13s
2026-05-03 03:43:46,873 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    65.32 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   225.18 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    20.10 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     9.20 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    16.87 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   336.68 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (855 / 1836 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79877-185698-417636/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-94229-146659-541449
  note_chars=2700  gold_concepts=6
==================================================================

2026-05-03 03:46:01,807 INFO ehr_pipeline.stages.s2_extract:   extracted 61 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/claims.json
2026-05-03 03:46:01,810 INFO ehr_pipeline.runtime:   stage2_extract done in 134.94s
2026-05-03 03:46:01,811 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 61 claims
2026-05-03 03:48:45,373 INFO ehr_pipeline.stages.s3_verify:   {'verified': 39, 'contradicted': 0, 'unsupported': 22} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/verifications.json
2026-05-03 03:48:45,377 INFO ehr_pipeline.runtime:   stage3_verify done in 163.57s
2026-05-03 03:48:45,378 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:48:45,379 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:48:45,382 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 65, 'medications': 8, 'labs': 3, 'vitals': 4, 'plan': 0}
2026-05-03 03:48:45,382 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:48:45,383 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:48:59,022 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/patient_summary.md (1586 chars, FK grade=9.45, in_band=False)
2026-05-03 03:48:59,025 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 13.64s
2026-05-03 03:48:59,026 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:49:18,508 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/summary.md (1133 chars, ratio=0.42, target=0.20-0.30, in_band=False)
2026-05-03 03:49:18,509 INFO ehr_pipeline.runtime:   stage6_summarize done in 19.48s
2026-05-03 03:49:18,511 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:49:18,519 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/check_report.json
2026-05-03 03:49:18,520 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 03:49:18,520 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:49:24,795 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/review.json
2026-05-03 03:49:24,796 INFO ehr_pipeline.runtime:   stage8_review done in 6.28s
2026-05-03 03:49:24,797 INFO ehr_pipeline.pipeline:   applied revision: 'Diuretics were held [E:note:row541449:6].' → 'Diuretics were previously held [E:note:row541449:6], though '
2026-05-03 03:49:24,798 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/summary_revised.md
2026-05-03 03:49:24,799 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:49:24,801 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/check_report_revised.json
2026-05-03 03:49:24,801 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:49:24,807 INFO ehr_pipeline.pipeline: Saved input note (1728 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/input_note.txt
2026-05-03 03:49:24,808 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-27022-196712-357513
2026-05-03 03:49:24,815 INFO ehr_pipeline.stages.s1_evidence:   wrote 118 evidence items (95 structured, 23 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/evidence_store.json
2026-05-03 03:49:24,816 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 03:49:24,817 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.13 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   134.94 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   163.57 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    13.64 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    19.48 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     6.28 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   338.05 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.42  (1133 / 2700 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94229-146659-541449/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-27022-196712-357513
  note_chars=1728  gold_concepts=7
==================================================================

2026-05-03 03:53:50,172 INFO ehr_pipeline.stages.s2_extract:   extracted 53 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/claims.json
2026-05-03 03:53:50,175 INFO ehr_pipeline.runtime:   stage2_extract done in 265.36s
2026-05-03 03:53:50,176 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 53 claims
2026-05-03 03:55:44,311 INFO ehr_pipeline.stages.s3_verify:   {'verified': 36, 'contradicted': 0, 'unsupported': 17} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/verifications.json
2026-05-03 03:55:44,312 INFO ehr_pipeline.runtime:   stage3_verify done in 114.14s
2026-05-03 03:55:44,312 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 03:55:44,314 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 03:55:44,316 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 63, 'medications': 7, 'labs': 3, 'vitals': 0, 'plan': 6}
2026-05-03 03:55:44,317 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 03:55:44,317 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 03:55:59,306 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/patient_summary.md (1893 chars, FK grade=7.19, in_band=True)
2026-05-03 03:55:59,308 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.99s
2026-05-03 03:55:59,309 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 03:56:29,040 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/summary.md (1182 chars, ratio=0.68, target=0.20-0.30, in_band=False)
2026-05-03 03:56:29,041 INFO ehr_pipeline.runtime:   stage6_summarize done in 29.73s
2026-05-03 03:56:29,043 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:56:29,045 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/check_report.json
2026-05-03 03:56:29,046 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 03:56:29,046 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 03:56:47,378 INFO ehr_pipeline.stages.s8_review:   concerns=4 recommended_revisions=4 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/review.json
2026-05-03 03:56:47,388 INFO ehr_pipeline.runtime:   stage8_review done in 18.34s
2026-05-03 03:56:47,391 INFO ehr_pipeline.pipeline:   applied revision: 'Biliary cirrhosis [E:cond:1][E:cond:2], portal hypertension ' → 'Biliary cirrhosis [E:cond:1][E:cond:2] and ascites [E:cond:2'
2026-05-03 03:56:47,393 INFO ehr_pipeline.pipeline:   applied revision: 'Bleeding esophageal varices [E:cond:5][E:cond:6], GI bleed [' → 'Bleeding esophageal varices [E:cond:5][E:cond:6] and posthem'
2026-05-03 03:56:47,393 INFO ehr_pipeline.pipeline:   applied revision: 'SBP [E:note:row357513:12], suppurative peritonitis [E:cond:1' → 'Suppurative peritonitis [E:cond:13][E:cond:14] and candidias'
2026-05-03 03:56:47,394 INFO ehr_pipeline.pipeline:   applied revision: 'Acute kidney failure [E:cond:17][E:cond:18], chronic systoli' → 'Acute kidney failure [E:cond:17][E:cond:18] and chronic syst'
2026-05-03 03:56:47,401 INFO ehr_pipeline.pipeline: Wrote revised summary (4 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/summary_revised.md
2026-05-03 03:56:47,402 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 03:56:47,404 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/check_report_revised.json
2026-05-03 03:56:47,405 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 03:56:47,412 INFO ehr_pipeline.pipeline: Saved input note (3975 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/input_note.txt
2026-05-03 03:56:47,412 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-86323-115774-624944
2026-05-03 03:56:47,415 INFO ehr_pipeline.stages.s1_evidence:   wrote 90 evidence items (27 structured, 63 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/evidence_store.json
2026-05-03 03:56:47,415 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 03:56:47,415 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   265.36 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   114.14 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.99 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    29.73 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    18.34 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   442.57 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.68  (1182 / 1728 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=4  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-357513/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-86323-115774-624944
  note_chars=3975  gold_concepts=12
==================================================================

2026-05-03 04:00:02,977 INFO ehr_pipeline.stages.s2_extract:   extracted 66 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/claims.json
2026-05-03 04:00:02,985 INFO ehr_pipeline.runtime:   stage2_extract done in 195.57s
2026-05-03 04:00:02,986 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 66 claims
2026-05-03 04:05:33,136 INFO ehr_pipeline.stages.s3_verify:   {'verified': 56, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/verifications.json
2026-05-03 04:05:33,139 INFO ehr_pipeline.runtime:   stage3_verify done in 330.15s
2026-05-03 04:05:33,140 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:05:33,145 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:05:33,147 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 44, 'medications': 11, 'labs': 1, 'vitals': 15, 'plan': 9}
2026-05-03 04:05:33,148 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:05:33,149 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:06:17,922 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/patient_summary.md (2109 chars, FK grade=8.39, in_band=False)
2026-05-03 04:06:17,925 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 44.78s
2026-05-03 04:06:17,926 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:07:16,020 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/summary.md (1952 chars, ratio=0.49, target=0.20-0.30, in_band=False)
2026-05-03 04:07:16,021 INFO ehr_pipeline.runtime:   stage6_summarize done in 58.10s
2026-05-03 04:07:16,023 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:07:16,026 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=22 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/check_report.json
2026-05-03 04:07:16,027 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:07:16,027 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:07:18,566 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/review.json
2026-05-03 04:07:18,569 INFO ehr_pipeline.runtime:   stage8_review done in 2.54s
2026-05-03 04:07:18,575 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 04:07:18,596 INFO ehr_pipeline.pipeline: Saved input note (2448 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/input_note.txt
2026-05-03 04:07:18,601 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-80791-181156-544481
2026-05-03 04:07:18,611 INFO ehr_pipeline.stages.s1_evidence:   wrote 23 evidence items (18 structured, 5 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/evidence_store.json
2026-05-03 04:07:18,628 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.03s
2026-05-03 04:07:18,652 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   195.57 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   330.15 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    44.78 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    58.10 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     2.54 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   631.14 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.49  (1952 / 3975 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86323-115774-624944/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-80791-181156-544481
  note_chars=2448  gold_concepts=13
==================================================================

2026-05-03 04:08:25,325 INFO ehr_pipeline.stages.s2_extract:   extracted 24 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/claims.json
2026-05-03 04:08:25,326 INFO ehr_pipeline.runtime:   stage2_extract done in 66.67s
2026-05-03 04:08:25,327 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 24 claims
2026-05-03 04:08:55,567 INFO ehr_pipeline.stages.s3_verify:   {'verified': 3, 'contradicted': 0, 'unsupported': 21} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/verifications.json
2026-05-03 04:08:55,568 INFO ehr_pipeline.runtime:   stage3_verify done in 30.24s
2026-05-03 04:08:55,568 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:08:55,571 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:08:55,572 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 17, 'medications': 1, 'labs': 0, 'vitals': 1, 'plan': 0}
2026-05-03 04:08:55,573 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:08:55,574 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:09:06,097 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/patient_summary.md (989 chars, FK grade=4.44, in_band=False)
2026-05-03 04:09:06,098 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 10.52s
2026-05-03 04:09:06,099 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:09:12,801 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/summary.md (887 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 04:09:12,803 INFO ehr_pipeline.runtime:   stage6_summarize done in 6.70s
2026-05-03 04:09:12,804 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:09:12,807 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/check_report.json
2026-05-03 04:09:12,808 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:09:12,808 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:09:52,989 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/review.json
2026-05-03 04:09:52,990 INFO ehr_pipeline.runtime:   stage8_review done in 40.18s
2026-05-03 04:09:52,990 INFO ehr_pipeline.pipeline:   applied revision: 'Comorbidities include lower leg osteoarthrosis [E:cond:1], o' → 'Comorbidities include lower leg osteoarthrosis [E:cond:1] an'
2026-05-03 04:09:52,991 INFO ehr_pipeline.pipeline:   applied revision: 'Procedures performed include total knee replacement [E:proc:' → 'Procedures performed include total knee replacement [E:proc:'
2026-05-03 04:09:52,992 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/summary_revised.md
2026-05-03 04:09:52,993 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:09:52,995 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/check_report_revised.json
2026-05-03 04:09:52,996 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:09:53,001 INFO ehr_pipeline.pipeline: Saved input note (3021 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/input_note.txt
2026-05-03 04:09:53,002 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-98435-148017-646532
2026-05-03 04:09:53,005 INFO ehr_pipeline.stages.s1_evidence:   wrote 72 evidence items (25 structured, 47 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/evidence_store.json
2026-05-03 04:09:53,005 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:09:53,005 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.03 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    66.67 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    30.24 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    10.52 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     6.70 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    40.18 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   154.36 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (887 / 2448 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80791-181156-544481/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-98435-148017-646532
  note_chars=3021  gold_concepts=7
==================================================================

2026-05-03 04:13:28,759 INFO ehr_pipeline.stages.s2_extract:   extracted 54 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/claims.json
2026-05-03 04:13:28,765 INFO ehr_pipeline.runtime:   stage2_extract done in 215.76s
2026-05-03 04:13:28,766 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 54 claims
2026-05-03 04:15:56,725 INFO ehr_pipeline.stages.s3_verify:   {'verified': 34, 'contradicted': 0, 'unsupported': 20} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/verifications.json
2026-05-03 04:15:56,729 INFO ehr_pipeline.runtime:   stage3_verify done in 147.96s
2026-05-03 04:15:56,729 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:15:56,732 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:15:56,733 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 37, 'medications': 11, 'labs': 4, 'vitals': 4, 'plan': 2}
2026-05-03 04:15:56,734 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:15:56,734 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:16:14,307 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/patient_summary.md (1836 chars, FK grade=7.80, in_band=True)
2026-05-03 04:16:14,309 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.57s
2026-05-03 04:16:14,310 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:16:33,571 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/summary.md (1604 chars, ratio=0.53, target=0.20-0.30, in_band=False)
2026-05-03 04:16:33,574 INFO ehr_pipeline.runtime:   stage6_summarize done in 19.26s
2026-05-03 04:16:33,576 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:16:33,578 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=16 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/check_report.json
2026-05-03 04:16:33,579 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:16:33,580 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:17:00,530 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/review.json
2026-05-03 04:17:00,531 INFO ehr_pipeline.runtime:   stage8_review done in 26.95s
2026-05-03 04:17:00,531 INFO ehr_pipeline.pipeline:   applied revision: 'Patient is withdrawn, lethargic, and has intermittent hypote' → 'Remove sentence.'
2026-05-03 04:17:00,532 INFO ehr_pipeline.pipeline:   applied revision: 'Comorbidities include acute respiratory failure [E:cond:2], ' → 'Comorbidities include acute respiratory failure [E:cond:2], '
2026-05-03 04:17:00,532 INFO ehr_pipeline.pipeline:   applied revision: 'Other diagnoses include subendocardial infarction [E:cond:4]' → 'Other diagnoses include subendocardial infarction [E:cond:4]'
2026-05-03 04:17:00,534 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/summary_revised.md
2026-05-03 04:17:00,534 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:17:00,537 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=16 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/check_report_revised.json
2026-05-03 04:17:00,537 INFO ehr_pipeline.pipeline:   revised summary check: passed=False violations=1
2026-05-03 04:17:00,543 INFO ehr_pipeline.pipeline: Saved input note (2298 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/input_note.txt
2026-05-03 04:17:00,544 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-56201-104808-514628
2026-05-03 04:17:00,547 INFO ehr_pipeline.stages.s1_evidence:   wrote 77 evidence items (32 structured, 45 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/evidence_store.json
2026-05-03 04:17:00,547 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:17:00,548 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   215.76 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   147.96 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.57 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    19.26 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    26.95 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   427.52 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.53  (1604 / 3021 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98435-148017-646532/summary_revised.md  [check FAIL ✗]
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-56201-104808-514628
  note_chars=2298  gold_concepts=11
==================================================================

2026-05-03 04:18:41,079 INFO ehr_pipeline.stages.s2_extract:   extracted 34 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/claims.json
2026-05-03 04:18:41,081 INFO ehr_pipeline.runtime:   stage2_extract done in 100.53s
2026-05-03 04:18:41,082 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 34 claims
2026-05-03 04:20:44,681 INFO ehr_pipeline.stages.s3_verify:   {'verified': 32, 'contradicted': 0, 'unsupported': 2} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/verifications.json
2026-05-03 04:20:44,683 INFO ehr_pipeline.runtime:   stage3_verify done in 123.60s
2026-05-03 04:20:44,683 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:20:44,687 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:20:44,689 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 48, 'medications': 10, 'labs': 0, 'vitals': 5, 'plan': 0}
2026-05-03 04:20:44,689 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:20:44,690 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:21:14,271 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/patient_summary.md (1839 chars, FK grade=7.65, in_band=True)
2026-05-03 04:21:14,274 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 29.58s
2026-05-03 04:21:14,274 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:21:50,521 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/summary.md (1099 chars, ratio=0.48, target=0.20-0.30, in_band=False)
2026-05-03 04:21:50,523 INFO ehr_pipeline.runtime:   stage6_summarize done in 36.25s
2026-05-03 04:21:50,525 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:21:50,528 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/check_report.json
2026-05-03 04:21:50,529 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:21:50,529 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:22:02,526 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/review.json
2026-05-03 04:22:02,528 INFO ehr_pipeline.runtime:   stage8_review done in 12.00s
2026-05-03 04:22:02,529 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with acute respiratory failure [E:cond:3], ' → 'Patient presents with acute respiratory failure [E:cond:3], '
2026-05-03 04:22:02,530 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/summary_revised.md
2026-05-03 04:22:02,531 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:22:02,533 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/check_report_revised.json
2026-05-03 04:22:02,534 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:22:02,540 INFO ehr_pipeline.pipeline: Saved input note (1963 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/input_note.txt
2026-05-03 04:22:02,541 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-59877-143996-528894
2026-05-03 04:22:02,544 INFO ehr_pipeline.stages.s1_evidence:   wrote 37 evidence items (20 structured, 17 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/evidence_store.json
2026-05-03 04:22:02,544 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:22:02,545 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   100.53 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   123.60 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    29.58 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    36.25 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.00 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   301.97 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.48  (1099 / 2298 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56201-104808-514628/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-59877-143996-528894
  note_chars=1963  gold_concepts=5
==================================================================

2026-05-03 04:23:11,277 INFO ehr_pipeline.stages.s2_extract:   extracted 32 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/claims.json
2026-05-03 04:23:11,281 INFO ehr_pipeline.runtime:   stage2_extract done in 68.74s
2026-05-03 04:23:11,282 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 32 claims
2026-05-03 04:24:10,911 INFO ehr_pipeline.stages.s3_verify:   {'verified': 17, 'contradicted': 0, 'unsupported': 15} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/verifications.json
2026-05-03 04:24:10,912 INFO ehr_pipeline.runtime:   stage3_verify done in 59.63s
2026-05-03 04:24:10,913 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:24:10,915 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:24:10,918 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 27, 'medications': 3, 'labs': 0, 'vitals': 2, 'plan': 3}
2026-05-03 04:24:10,918 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:24:10,919 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:24:32,519 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/patient_summary.md (1489 chars, FK grade=6.26, in_band=False)
2026-05-03 04:24:32,520 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 21.60s
2026-05-03 04:24:32,521 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:24:41,448 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/summary.md (882 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 04:24:41,449 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.93s
2026-05-03 04:24:41,451 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:24:41,454 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/check_report.json
2026-05-03 04:24:41,454 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:24:41,455 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:24:58,218 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/review.json
2026-05-03 04:24:58,220 INFO ehr_pipeline.runtime:   stage8_review done in 16.76s
2026-05-03 04:24:58,220 INFO ehr_pipeline.pipeline:   applied revision: 'Other issues include SAH [E:cond:3][E:note:row528894:2], acu' → 'Other issues include SAH [E:cond:3][E:note:row528894:2], acu'
2026-05-03 04:24:58,221 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/summary_revised.md
2026-05-03 04:24:58,222 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:24:58,224 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/check_report_revised.json
2026-05-03 04:24:58,224 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:24:58,230 INFO ehr_pipeline.pipeline: Saved input note (3348 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/input_note.txt
2026-05-03 04:24:58,231 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-85999-134661-689561
2026-05-03 04:24:58,237 INFO ehr_pipeline.stages.s1_evidence:   wrote 75 evidence items (39 structured, 36 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/evidence_store.json
2026-05-03 04:24:58,238 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 04:24:58,240 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    68.74 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    59.63 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    21.60 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.93 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    16.76 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   175.67 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (882 / 1963 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59877-143996-528894/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-85999-134661-689561
  note_chars=3348  gold_concepts=13
==================================================================

2026-05-03 04:26:47,484 INFO ehr_pipeline.stages.s2_extract:   extracted 54 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/claims.json
2026-05-03 04:26:47,487 INFO ehr_pipeline.runtime:   stage2_extract done in 109.25s
2026-05-03 04:26:47,487 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 54 claims
2026-05-03 04:27:52,274 INFO ehr_pipeline.stages.s3_verify:   {'verified': 21, 'contradicted': 0, 'unsupported': 33} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/verifications.json
2026-05-03 04:27:52,275 INFO ehr_pipeline.runtime:   stage3_verify done in 64.79s
2026-05-03 04:27:52,275 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:27:52,278 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:27:52,279 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 48, 'medications': 2, 'labs': 2, 'vitals': 2, 'plan': 4}
2026-05-03 04:27:52,280 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:27:52,280 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:28:50,070 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/patient_summary.md (1792 chars, FK grade=7.07, in_band=True)
2026-05-03 04:28:50,070 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 57.79s
2026-05-03 04:28:50,071 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:29:21,797 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/summary.md (1490 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 04:29:21,798 INFO ehr_pipeline.runtime:   stage6_summarize done in 31.73s
2026-05-03 04:29:21,800 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:29:21,802 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/check_report.json
2026-05-03 04:29:21,802 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:29:21,803 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:30:21,193 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/review.json
2026-05-03 04:30:21,195 INFO ehr_pipeline.runtime:   stage8_review done in 59.39s
2026-05-03 04:30:21,196 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 04:30:21,204 INFO ehr_pipeline.pipeline: Saved input note (2266 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/input_note.txt
2026-05-03 04:30:21,204 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-58515-125506-439636
2026-05-03 04:30:21,206 INFO ehr_pipeline.stages.s1_evidence:   wrote 53 evidence items (31 structured, 22 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/evidence_store.json
2026-05-03 04:30:21,207 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:30:21,207 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   109.25 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    64.79 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    57.79 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    31.73 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    59.39 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   322.96 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (1490 / 3348 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85999-134661-689561/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-58515-125506-439636
  note_chars=2266  gold_concepts=10
==================================================================

2026-05-03 04:31:38,416 INFO ehr_pipeline.stages.s2_extract:   extracted 42 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/claims.json
2026-05-03 04:31:38,418 INFO ehr_pipeline.runtime:   stage2_extract done in 77.21s
2026-05-03 04:31:38,419 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 42 claims
2026-05-03 04:33:44,256 INFO ehr_pipeline.stages.s3_verify:   {'verified': 28, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/verifications.json
2026-05-03 04:33:44,258 INFO ehr_pipeline.runtime:   stage3_verify done in 125.84s
2026-05-03 04:33:44,258 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:33:44,260 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:33:44,261 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 44, 'medications': 2, 'labs': 4, 'vitals': 5, 'plan': 3}
2026-05-03 04:33:44,261 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:33:44,261 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:34:00,476 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/patient_summary.md (1922 chars, FK grade=5.68, in_band=False)
2026-05-03 04:34:00,477 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 16.22s
2026-05-03 04:34:00,478 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:34:11,390 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/summary.md (939 chars, ratio=0.41, target=0.20-0.30, in_band=False)
2026-05-03 04:34:11,391 INFO ehr_pipeline.runtime:   stage6_summarize done in 10.91s
2026-05-03 04:34:11,393 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:34:11,396 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/check_report.json
2026-05-03 04:34:11,396 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:34:11,398 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:34:18,888 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/review.json
2026-05-03 04:34:18,889 INFO ehr_pipeline.runtime:   stage8_review done in 7.49s
2026-05-03 04:34:18,889 INFO ehr_pipeline.pipeline:   applied revision: 'DM II [E:note:row439636:6], HTN [E:note:row439636:6], and co' → 'DM II [E:cond:15].'
2026-05-03 04:34:18,891 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/summary_revised.md
2026-05-03 04:34:18,892 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:34:18,895 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/check_report_revised.json
2026-05-03 04:34:18,895 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:34:18,899 INFO ehr_pipeline.pipeline: Saved input note (3994 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/input_note.txt
2026-05-03 04:34:18,900 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-54229-165594-597675
2026-05-03 04:34:18,902 INFO ehr_pipeline.stages.s1_evidence:   wrote 99 evidence items (65 structured, 34 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/evidence_store.json
2026-05-03 04:34:18,902 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:34:18,903 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    77.21 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   125.84 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    16.22 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    10.91 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     7.49 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   237.68 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.41  (939 / 2266 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-58515-125506-439636/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-54229-165594-597675
  note_chars=3994  gold_concepts=12
==================================================================

2026-05-03 04:36:54,622 INFO ehr_pipeline.stages.s2_extract:   extracted 46 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/claims.json
2026-05-03 04:36:54,624 INFO ehr_pipeline.runtime:   stage2_extract done in 155.72s
2026-05-03 04:36:54,625 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 46 claims
2026-05-03 04:39:19,415 INFO ehr_pipeline.stages.s3_verify:   {'verified': 30, 'contradicted': 0, 'unsupported': 16} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/verifications.json
2026-05-03 04:39:19,416 INFO ehr_pipeline.runtime:   stage3_verify done in 144.79s
2026-05-03 04:39:19,416 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:39:19,419 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:39:19,421 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 47, 'medications': 5, 'labs': 3, 'vitals': 3, 'plan': 2}
2026-05-03 04:39:19,421 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:39:19,422 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:39:50,953 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/patient_summary.md (2296 chars, FK grade=8.56, in_band=False)
2026-05-03 04:39:50,954 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 31.53s
2026-05-03 04:39:50,956 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:40:09,589 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/summary.md (1777 chars, ratio=0.44, target=0.20-0.30, in_band=False)
2026-05-03 04:40:09,591 INFO ehr_pipeline.runtime:   stage6_summarize done in 18.63s
2026-05-03 04:40:09,592 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:40:09,596 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/check_report.json
2026-05-03 04:40:09,597 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:40:09,597 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:40:21,230 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/review.json
2026-05-03 04:40:21,231 INFO ehr_pipeline.runtime:   stage8_review done in 11.63s
2026-05-03 04:40:21,231 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with septic shock [E:cond:9][E:cond:10], se' → 'Patient presents with septic shock [E:cond:9][E:cond:10], se'
2026-05-03 04:40:21,233 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/summary_revised.md
2026-05-03 04:40:21,234 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:40:21,236 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/check_report_revised.json
2026-05-03 04:40:21,237 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:40:21,244 INFO ehr_pipeline.pipeline: Saved input note (3360 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/input_note.txt
2026-05-03 04:40:21,245 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-49358-158550-701330
2026-05-03 04:40:21,247 INFO ehr_pipeline.stages.s1_evidence:   wrote 68 evidence items (12 structured, 56 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/evidence_store.json
2026-05-03 04:40:21,248 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:40:21,248 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   155.72 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   144.79 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    31.53 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    18.63 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    11.63 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   362.32 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.44  (1777 / 3994 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54229-165594-597675/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-49358-158550-701330
  note_chars=3360  gold_concepts=9
==================================================================

2026-05-03 04:41:49,942 INFO ehr_pipeline.stages.s2_extract:   extracted 38 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/claims.json
2026-05-03 04:41:49,947 INFO ehr_pipeline.runtime:   stage2_extract done in 88.70s
2026-05-03 04:41:49,948 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 38 claims
2026-05-03 04:46:19,056 INFO ehr_pipeline.stages.s3_verify:   {'verified': 23, 'contradicted': 0, 'unsupported': 15} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/verifications.json
2026-05-03 04:46:19,057 INFO ehr_pipeline.runtime:   stage3_verify done in 269.11s
2026-05-03 04:46:19,058 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:46:19,060 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:46:19,062 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 18, 'medications': 9, 'labs': 3, 'vitals': 4, 'plan': 0}
2026-05-03 04:46:19,063 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:46:19,063 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:46:31,746 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/patient_summary.md (1696 chars, FK grade=7.55, in_band=True)
2026-05-03 04:46:31,747 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 12.68s
2026-05-03 04:46:31,747 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:46:44,261 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/summary.md (1343 chars, ratio=0.40, target=0.20-0.30, in_band=False)
2026-05-03 04:46:44,262 INFO ehr_pipeline.runtime:   stage6_summarize done in 12.51s
2026-05-03 04:46:44,265 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:46:44,267 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/check_report.json
2026-05-03 04:46:44,268 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:46:44,269 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:48:23,468 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/review.json
2026-05-03 04:48:23,470 INFO ehr_pipeline.runtime:   stage8_review done in 99.20s
2026-05-03 04:48:23,471 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with severe sepsis [E:cond:6] and unspecifi' → 'Patient presents with severe sepsis [E:cond:6] and unspecifi'
2026-05-03 04:48:23,471 INFO ehr_pipeline.pipeline:   applied revision: 'Comorbidities include acute kidney failure [E:cond:2], respi' → 'Comorbidities include acute kidney failure [E:cond:2] and pa'
2026-05-03 04:48:23,472 INFO ehr_pipeline.pipeline:   applied revision: 'Blood sugars, renal function, and electrolytes are within no' → 'Blood sugars [E:note:row701330:26] and electrolytes [E:note:'
2026-05-03 04:48:23,473 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/summary_revised.md
2026-05-03 04:48:23,474 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:48:23,476 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/check_report_revised.json
2026-05-03 04:48:23,476 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:48:23,481 INFO ehr_pipeline.pipeline: Saved input note (2346 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/input_note.txt
2026-05-03 04:48:23,481 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-99613-177517-520810
2026-05-03 04:48:23,482 INFO ehr_pipeline.stages.s1_evidence:   wrote 29 evidence items (24 structured, 5 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/evidence_store.json
2026-05-03 04:48:23,482 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:48:23,483 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    88.70 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   269.11 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    12.68 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    12.51 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    99.20 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   482.22 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.40  (1343 / 3360 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=2  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49358-158550-701330/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-99613-177517-520810
  note_chars=2346  gold_concepts=12
==================================================================

2026-05-03 04:49:37,915 INFO ehr_pipeline.stages.s2_extract:   extracted 40 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/claims.json
2026-05-03 04:49:37,916 INFO ehr_pipeline.runtime:   stage2_extract done in 74.43s
2026-05-03 04:49:37,917 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 40 claims
2026-05-03 04:50:19,525 INFO ehr_pipeline.stages.s3_verify:   {'verified': 11, 'contradicted': 0, 'unsupported': 29} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/verifications.json
2026-05-03 04:50:19,526 INFO ehr_pipeline.runtime:   stage3_verify done in 41.61s
2026-05-03 04:50:19,526 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:50:19,530 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:50:19,532 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 31, 'medications': 0, 'labs': 2, 'vitals': 1, 'plan': 0}
2026-05-03 04:50:19,532 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:50:19,533 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 04:50:36,588 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/patient_summary.md (1357 chars, FK grade=8.43, in_band=False)
2026-05-03 04:50:36,589 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.06s
2026-05-03 04:50:36,590 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 04:50:44,636 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/summary.md (833 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 04:50:44,637 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.05s
2026-05-03 04:50:44,639 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:50:44,642 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/check_report.json
2026-05-03 04:50:44,642 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 04:50:44,643 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 04:50:57,741 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/review.json
2026-05-03 04:50:57,744 INFO ehr_pipeline.runtime:   stage8_review done in 13.10s
2026-05-03 04:50:57,745 INFO ehr_pipeline.pipeline:   applied revision: 'Acute and chronic respiratory failure [E:cond:2] presenting ' → 'Acute and chronic respiratory failure [E:cond:2].'
2026-05-03 04:50:57,746 INFO ehr_pipeline.pipeline:   applied revision: 'Severe COPD [E:note:row520810:1] and RLL pneumonia [E:note:r' → ''
2026-05-03 04:50:57,747 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/summary_revised.md
2026-05-03 04:50:57,747 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 04:50:57,748 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/check_report_revised.json
2026-05-03 04:50:57,748 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 04:50:57,752 INFO ehr_pipeline.pipeline: Saved input note (2464 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/input_note.txt
2026-05-03 04:50:57,753 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-1860-195382-329634
2026-05-03 04:50:57,755 INFO ehr_pipeline.stages.s1_evidence:   wrote 73 evidence items (36 structured, 37 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/evidence_store.json
2026-05-03 04:50:57,755 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 04:50:57,755 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    74.43 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    41.61 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.06 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.05 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    13.10 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   154.25 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (833 / 2346 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99613-177517-520810/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-1860-195382-329634
  note_chars=2464  gold_concepts=14
==================================================================

2026-05-03 04:53:50,154 INFO ehr_pipeline.stages.s2_extract:   extracted 59 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/claims.json
2026-05-03 04:53:50,158 INFO ehr_pipeline.runtime:   stage2_extract done in 172.40s
2026-05-03 04:53:50,158 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 59 claims
2026-05-03 04:58:31,415 WARNING ehr_pipeline.ollama_client: LLM JSON attempt 1/4 failed, appending error feedback and retrying: Remote end closed connection without response
2026-05-03 04:59:57,036 INFO ehr_pipeline.stages.s3_verify:   {'verified': 53, 'contradicted': 0, 'unsupported': 6} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/verifications.json
2026-05-03 04:59:57,037 INFO ehr_pipeline.runtime:   stage3_verify done in 366.88s
2026-05-03 04:59:57,038 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 04:59:57,039 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 04:59:57,041 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 66, 'medications': 4, 'labs': 3, 'vitals': 7, 'plan': 3}
2026-05-03 04:59:57,041 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 04:59:57,041 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:00:12,903 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/patient_summary.md (1986 chars, FK grade=8.68, in_band=False)
2026-05-03 05:00:12,905 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.86s
2026-05-03 05:00:12,905 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:03:39,207 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/summary.md (1064 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 05:03:39,210 INFO ehr_pipeline.runtime:   stage6_summarize done in 206.30s
2026-05-03 05:03:39,213 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:03:39,215 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/check_report.json
2026-05-03 05:03:39,215 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:03:39,216 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:05:04,299 INFO ehr_pipeline.stages.s8_review:   concerns=5 recommended_revisions=5 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/review.json
2026-05-03 05:05:04,302 INFO ehr_pipeline.runtime:   stage8_review done in 85.09s
2026-05-03 05:05:04,303 INFO ehr_pipeline.pipeline:   applied revision: 'SCLC [E:note:row329634:1], acute respiratory failure [E:cond' → 'Malignant neoplasm of bronchus or lung [E:cond:5], acute res'
2026-05-03 05:05:04,303 INFO ehr_pipeline.pipeline:   applied revision: 'ESRD [E:cond:3] with anuria [E:note:row329634:37].' → 'End stage renal disease [E:cond:3].'
2026-05-03 05:05:04,303 INFO ehr_pipeline.pipeline:   applied revision: 'Intestinal obstruction [E:cond:6], ileus [E:note:row329634:1' → 'Intestinal obstruction [E:cond:6].'
2026-05-03 05:05:04,304 INFO ehr_pipeline.pipeline:   applied revision: 'AFib [E:cond:15], HTN [E:note:row329634:1], DMII [E:note:row' → 'Atrial fibrillation [E:cond:15].'
2026-05-03 05:05:04,304 INFO ehr_pipeline.pipeline:   applied revision: 'Hypotension [E:note:row329634:1].' → 'Low blood pressure (SBP 60s-110s) [E:note:row329634:15, E:no'
2026-05-03 05:05:04,305 INFO ehr_pipeline.pipeline: Wrote revised summary (5 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/summary_revised.md
2026-05-03 05:05:04,305 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:05:04,307 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=10 violations=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/check_report_revised.json
2026-05-03 05:05:04,307 INFO ehr_pipeline.pipeline:   revised summary check: passed=False violations=2
2026-05-03 05:05:04,313 INFO ehr_pipeline.pipeline: Saved input note (3054 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/input_note.txt
2026-05-03 05:05:04,313 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-68956-147281-563910
2026-05-03 05:05:04,315 INFO ehr_pipeline.stages.s1_evidence:   wrote 95 evidence items (32 structured, 63 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/evidence_store.json
2026-05-03 05:05:04,315 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:05:04,316 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   172.40 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   366.88 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.86 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   206.30 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    85.09 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   846.54 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (1064 / 2464 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=5  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-1860-195382-329634/summary_revised.md  [check FAIL ✗]
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-68956-147281-563910
  note_chars=3054  gold_concepts=4
==================================================================

2026-05-03 05:08:36,106 INFO ehr_pipeline.stages.s2_extract:   extracted 50 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/claims.json
2026-05-03 05:08:36,110 INFO ehr_pipeline.runtime:   stage2_extract done in 211.79s
2026-05-03 05:08:36,111 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 50 claims
2026-05-03 05:10:28,541 INFO ehr_pipeline.stages.s3_verify:   {'verified': 44, 'contradicted': 0, 'unsupported': 6} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/verifications.json
2026-05-03 05:10:28,543 INFO ehr_pipeline.runtime:   stage3_verify done in 112.43s
2026-05-03 05:10:28,544 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:10:28,545 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:10:28,548 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 56, 'medications': 10, 'labs': 2, 'vitals': 5, 'plan': 2}
2026-05-03 05:10:28,548 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:10:28,548 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:10:51,382 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/patient_summary.md (2109 chars, FK grade=6.49, in_band=False)
2026-05-03 05:10:51,383 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 22.84s
2026-05-03 05:10:51,384 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:11:15,107 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/summary.md (1593 chars, ratio=0.52, target=0.20-0.30, in_band=False)
2026-05-03 05:11:15,108 INFO ehr_pipeline.runtime:   stage6_summarize done in 23.72s
2026-05-03 05:11:15,111 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:11:15,114 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/check_report.json
2026-05-03 05:11:15,115 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:11:15,115 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:11:24,754 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/review.json
2026-05-03 05:11:24,755 INFO ehr_pipeline.runtime:   stage8_review done in 9.64s
2026-05-03 05:11:24,756 INFO ehr_pipeline.pipeline:   applied revision: 'Malignancies include lung adenocarcinoma (T1) [E:cond:5][E:n' → 'Malignancies include malignant neoplasm of the bronchus or l'
2026-05-03 05:11:24,757 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/summary_revised.md
2026-05-03 05:11:24,759 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:11:24,761 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/check_report_revised.json
2026-05-03 05:11:24,761 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:11:24,765 INFO ehr_pipeline.pipeline: Saved input note (3065 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/input_note.txt
2026-05-03 05:11:24,766 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-78531-141755-649239
2026-05-03 05:11:24,768 INFO ehr_pipeline.stages.s1_evidence:   wrote 40 evidence items (16 structured, 24 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/evidence_store.json
2026-05-03 05:11:24,768 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:11:24,768 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   211.79 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   112.43 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    22.84 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    23.72 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     9.64 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   380.43 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.52  (1593 / 3054 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68956-147281-563910/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-78531-141755-649239
  note_chars=3065  gold_concepts=7
==================================================================

2026-05-03 05:13:38,661 INFO ehr_pipeline.stages.s2_extract:   extracted 38 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/claims.json
2026-05-03 05:13:38,663 INFO ehr_pipeline.runtime:   stage2_extract done in 133.90s
2026-05-03 05:13:38,664 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 38 claims
2026-05-03 05:14:06,858 INFO ehr_pipeline.stages.s3_verify:   {'verified': 12, 'contradicted': 0, 'unsupported': 26} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/verifications.json
2026-05-03 05:14:06,859 INFO ehr_pipeline.runtime:   stage3_verify done in 28.20s
2026-05-03 05:14:06,860 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:14:06,862 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:14:06,863 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 27, 'medications': 0, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-03 05:14:06,864 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:14:06,864 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:14:41,867 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/patient_summary.md (1412 chars, FK grade=8.21, in_band=False)
2026-05-03 05:14:41,868 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 35.00s
2026-05-03 05:14:41,869 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:14:52,217 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/summary.md (1239 chars, ratio=0.40, target=0.20-0.30, in_band=False)
2026-05-03 05:14:52,218 INFO ehr_pipeline.runtime:   stage6_summarize done in 10.35s
2026-05-03 05:14:52,220 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:14:52,223 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/check_report.json
2026-05-03 05:14:52,224 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:14:52,225 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:15:01,944 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/review.json
2026-05-03 05:15:01,944 INFO ehr_pipeline.runtime:   stage8_review done in 9.72s
2026-05-03 05:15:01,945 INFO ehr_pipeline.pipeline:   applied revision: 'Procedures performed include ventricular shunt, brain biopsy' → 'Procedures performed include ventricular shunt, brain biopsy'
2026-05-03 05:15:01,946 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/summary_revised.md
2026-05-03 05:15:01,947 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:15:01,949 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/check_report_revised.json
2026-05-03 05:15:01,949 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:15:01,955 INFO ehr_pipeline.pipeline: Saved input note (1781 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/input_note.txt
2026-05-03 05:15:01,955 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-59113-169374-701538
2026-05-03 05:15:01,956 INFO ehr_pipeline.stages.s1_evidence:   wrote 38 evidence items (25 structured, 13 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/evidence_store.json
2026-05-03 05:15:01,957 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:15:01,957 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   133.90 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    28.20 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    35.00 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    10.35 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     9.72 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   217.17 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.40  (1239 / 3065 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78531-141755-649239/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-59113-169374-701538
  note_chars=1781  gold_concepts=9
==================================================================

2026-05-03 05:16:37,794 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/claims.json
2026-05-03 05:16:37,797 INFO ehr_pipeline.runtime:   stage2_extract done in 95.84s
2026-05-03 05:16:37,798 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 05:17:34,605 INFO ehr_pipeline.stages.s3_verify:   {'verified': 17, 'contradicted': 0, 'unsupported': 20} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/verifications.json
2026-05-03 05:17:34,606 INFO ehr_pipeline.runtime:   stage3_verify done in 56.81s
2026-05-03 05:17:34,607 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:17:34,609 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:17:34,610 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 35, 'medications': 1, 'labs': 3, 'vitals': 0, 'plan': 2}
2026-05-03 05:17:34,610 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:17:34,611 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:17:59,360 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/patient_summary.md (1549 chars, FK grade=10.34, in_band=False)
2026-05-03 05:17:59,361 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 24.75s
2026-05-03 05:17:59,361 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:18:07,497 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/summary.md (925 chars, ratio=0.52, target=0.20-0.30, in_band=False)
2026-05-03 05:18:07,499 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.14s
2026-05-03 05:18:07,501 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:18:07,504 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/check_report.json
2026-05-03 05:18:07,504 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:18:07,505 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:18:13,332 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/review.json
2026-05-03 05:18:13,333 INFO ehr_pipeline.runtime:   stage8_review done in 5.83s
2026-05-03 05:18:13,334 INFO ehr_pipeline.pipeline:   applied revision: 'Patient has HIV [E:cond:15][E:note:row701538:2], T2DM [E:con' → 'Patient has HIV [E:cond:15][E:note:row701538:2].'
2026-05-03 05:18:13,336 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/summary_revised.md
2026-05-03 05:18:13,336 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:18:13,338 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/check_report_revised.json
2026-05-03 05:18:13,339 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:18:13,342 INFO ehr_pipeline.pipeline: Saved input note (3063 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/input_note.txt
2026-05-03 05:18:13,343 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-88649-135549-588579
2026-05-03 05:18:13,344 INFO ehr_pipeline.stages.s1_evidence:   wrote 97 evidence items (33 structured, 64 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/evidence_store.json
2026-05-03 05:18:13,344 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:18:13,345 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    95.84 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    56.81 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    24.75 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.14 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     5.83 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   191.37 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.52  (925 / 1781 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-59113-169374-701538/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-88649-135549-588579
  note_chars=3063  gold_concepts=18
==================================================================

2026-05-03 05:20:02,785 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/claims.json
2026-05-03 05:20:02,795 INFO ehr_pipeline.runtime:   stage2_extract done in 109.45s
2026-05-03 05:20:02,796 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 05:22:06,222 INFO ehr_pipeline.stages.s3_verify:   {'verified': 33, 'contradicted': 0, 'unsupported': 4} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/verifications.json
2026-05-03 05:22:06,223 INFO ehr_pipeline.runtime:   stage3_verify done in 123.43s
2026-05-03 05:22:06,224 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:22:06,226 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:22:06,228 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 43, 'medications': 12, 'labs': 0, 'vitals': 5, 'plan': 2}
2026-05-03 05:22:06,228 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:22:06,228 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:22:23,560 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/patient_summary.md (2073 chars, FK grade=9.41, in_band=False)
2026-05-03 05:22:23,561 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.33s
2026-05-03 05:22:23,562 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:22:46,851 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/summary.md (1673 chars, ratio=0.55, target=0.20-0.30, in_band=False)
2026-05-03 05:22:46,854 INFO ehr_pipeline.runtime:   stage6_summarize done in 23.29s
2026-05-03 05:22:46,856 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:22:46,859 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/check_report.json
2026-05-03 05:22:46,860 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:22:46,860 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:24:09,899 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/review.json
2026-05-03 05:24:09,902 INFO ehr_pipeline.runtime:   stage8_review done in 83.04s
2026-05-03 05:24:09,903 INFO ehr_pipeline.pipeline:   applied revision: 'Respiratory status is critical with acute respiratory failur' → 'Respiratory findings include acute respiratory failure [E:co'
2026-05-03 05:24:09,904 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/summary_revised.md
2026-05-03 05:24:09,905 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:24:09,906 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/check_report_revised.json
2026-05-03 05:24:09,906 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:24:09,916 INFO ehr_pipeline.pipeline: Saved input note (2154 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/input_note.txt
2026-05-03 05:24:09,916 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-46320-113335-458422
2026-05-03 05:24:09,920 INFO ehr_pipeline.stages.s1_evidence:   wrote 308 evidence items (301 structured, 7 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/evidence_store.json
2026-05-03 05:24:09,921 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:24:09,921 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   109.45 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   123.43 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.33 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    23.29 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    83.04 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   356.55 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.55  (1673 / 3063 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88649-135549-588579/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-46320-113335-458422
  note_chars=2154  gold_concepts=8
==================================================================

2026-05-03 05:25:40,213 INFO ehr_pipeline.stages.s2_extract:   extracted 33 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/claims.json
2026-05-03 05:25:40,215 INFO ehr_pipeline.runtime:   stage2_extract done in 90.29s
2026-05-03 05:25:40,216 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 33 claims
2026-05-03 05:29:51,811 INFO ehr_pipeline.stages.s3_verify:   {'verified': 11, 'contradicted': 0, 'unsupported': 22} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/verifications.json
2026-05-03 05:29:51,813 INFO ehr_pipeline.runtime:   stage3_verify done in 251.60s
2026-05-03 05:29:51,813 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:29:51,816 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:29:51,819 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 55, 'medications': 0, 'labs': 1, 'vitals': 1, 'plan': 0}
2026-05-03 05:29:51,820 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:29:51,820 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:31:02,790 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/patient_summary.md (1304 chars, FK grade=9.13, in_band=False)
2026-05-03 05:31:02,793 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 70.97s
2026-05-03 05:31:02,793 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:31:11,518 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/summary.md (771 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 05:31:11,519 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.73s
2026-05-03 05:31:11,523 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:31:11,527 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/check_report.json
2026-05-03 05:31:11,528 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 05:31:11,528 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:31:17,847 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/review.json
2026-05-03 05:31:17,849 INFO ehr_pipeline.runtime:   stage8_review done in 6.32s
2026-05-03 05:31:17,850 INFO ehr_pipeline.pipeline:   applied revision: 'Other conditions: sepsis [E:note:row458422:7], MRSA at opera' → 'Other conditions: C. difficile [E:cond:55] and urogenital ca'
2026-05-03 05:31:17,852 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/summary_revised.md
2026-05-03 05:31:17,853 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:31:17,854 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/check_report_revised.json
2026-05-03 05:31:17,855 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:31:17,859 INFO ehr_pipeline.pipeline: Saved input note (4780 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/input_note.txt
2026-05-03 05:31:17,859 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-30376-166341-399595
2026-05-03 05:31:17,862 INFO ehr_pipeline.stages.s1_evidence:   wrote 67 evidence items (38 structured, 29 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/evidence_store.json
2026-05-03 05:31:17,862 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:31:17,862 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    90.29 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   251.60 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    70.97 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.73 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     6.32 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   427.92 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (771 / 2154 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-458422/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-30376-166341-399595
  note_chars=4780  gold_concepts=3
==================================================================

2026-05-03 05:35:52,592 INFO ehr_pipeline.stages.s2_extract:   extracted 77 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/claims.json
2026-05-03 05:35:52,595 INFO ehr_pipeline.runtime:   stage2_extract done in 274.73s
2026-05-03 05:35:52,595 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 77 claims
2026-05-03 05:36:38,459 INFO ehr_pipeline.stages.s3_verify:   {'verified': 26, 'contradicted': 1, 'unsupported': 50} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/verifications.json
2026-05-03 05:36:38,460 INFO ehr_pipeline.runtime:   stage3_verify done in 45.86s
2026-05-03 05:36:38,461 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:36:38,463 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:36:38,466 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 48, 'medications': 5, 'labs': 3, 'vitals': 2, 'plan': 3}
2026-05-03 05:36:38,466 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:36:38,466 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:36:51,654 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/patient_summary.md (1711 chars, FK grade=6.06, in_band=False)
2026-05-03 05:36:51,655 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 13.19s
2026-05-03 05:36:51,656 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:37:10,085 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/summary.md (1879 chars, ratio=0.39, target=0.20-0.30, in_band=False)
2026-05-03 05:37:10,087 INFO ehr_pipeline.runtime:   stage6_summarize done in 18.43s
2026-05-03 05:37:10,089 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:37:10,092 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/check_report.json
2026-05-03 05:37:10,093 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:37:10,093 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:37:11,723 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/review.json
2026-05-03 05:37:11,724 INFO ehr_pipeline.runtime:   stage8_review done in 1.63s
2026-05-03 05:37:11,725 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 05:37:11,732 INFO ehr_pipeline.pipeline: Saved input note (3294 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/input_note.txt
2026-05-03 05:37:11,732 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-50847-123701-419476
2026-05-03 05:37:11,735 INFO ehr_pipeline.stages.s1_evidence:   wrote 66 evidence items (40 structured, 26 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/evidence_store.json
2026-05-03 05:37:11,735 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:37:11,735 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   274.73 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    45.86 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    13.19 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    18.43 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     1.63 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   353.86 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.39  (1879 / 4780 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-30376-166341-399595/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-50847-123701-419476
  note_chars=3294  gold_concepts=12
==================================================================

2026-05-03 05:39:55,055 INFO ehr_pipeline.stages.s2_extract:   extracted 43 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/claims.json
2026-05-03 05:39:55,057 INFO ehr_pipeline.runtime:   stage2_extract done in 163.32s
2026-05-03 05:39:55,058 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 43 claims
2026-05-03 05:41:34,321 INFO ehr_pipeline.stages.s3_verify:   {'verified': 26, 'contradicted': 0, 'unsupported': 17} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/verifications.json
2026-05-03 05:41:34,323 INFO ehr_pipeline.runtime:   stage3_verify done in 99.26s
2026-05-03 05:41:34,323 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:41:34,326 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:41:34,328 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 46, 'medications': 4, 'labs': 2, 'vitals': 6, 'plan': 1}
2026-05-03 05:41:34,328 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:41:34,328 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:41:45,381 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/patient_summary.md (1535 chars, FK grade=6.22, in_band=False)
2026-05-03 05:41:45,381 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 11.05s
2026-05-03 05:41:45,381 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:42:08,368 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/summary.md (1212 chars, ratio=0.37, target=0.20-0.30, in_band=False)
2026-05-03 05:42:08,369 INFO ehr_pipeline.runtime:   stage6_summarize done in 22.99s
2026-05-03 05:42:08,371 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:42:08,374 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/check_report.json
2026-05-03 05:42:08,375 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:42:08,375 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:42:27,254 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/review.json
2026-05-03 05:42:27,256 INFO ehr_pipeline.runtime:   stage8_review done in 18.88s
2026-05-03 05:42:27,257 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with acute and subacute bacterial endocardi' → 'Patient presents with acute and subacute bacterial endocardi'
2026-05-03 05:42:27,257 INFO ehr_pipeline.pipeline:   applied revision: 'Cardiac issues include acute diastolic heart failure [E:cond' → 'Cardiac issues include acute diastolic heart failure [E:cond'
2026-05-03 05:42:27,259 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/summary_revised.md
2026-05-03 05:42:27,260 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:42:27,262 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/check_report_revised.json
2026-05-03 05:42:27,262 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:42:27,266 INFO ehr_pipeline.pipeline: Saved input note (4222 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/input_note.txt
2026-05-03 05:42:27,266 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-79565-181839-427484
2026-05-03 05:42:27,269 INFO ehr_pipeline.stages.s1_evidence:   wrote 88 evidence items (38 structured, 50 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/evidence_store.json
2026-05-03 05:42:27,269 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:42:27,269 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   163.32 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    99.26 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    11.05 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    22.99 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    18.88 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   315.52 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.37  (1212 / 3294 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50847-123701-419476/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-79565-181839-427484
  note_chars=4222  gold_concepts=13
==================================================================

2026-05-03 05:45:48,397 INFO ehr_pipeline.stages.s2_extract:   extracted 42 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/claims.json
2026-05-03 05:45:48,401 INFO ehr_pipeline.runtime:   stage2_extract done in 201.13s
2026-05-03 05:45:48,402 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 42 claims
2026-05-03 05:47:15,255 INFO ehr_pipeline.stages.s3_verify:   {'verified': 31, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/verifications.json
2026-05-03 05:47:15,257 INFO ehr_pipeline.runtime:   stage3_verify done in 86.85s
2026-05-03 05:47:15,258 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:47:15,259 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:47:15,260 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 50, 'medications': 8, 'labs': 7, 'vitals': 2, 'plan': 0}
2026-05-03 05:47:15,261 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:47:15,261 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:47:32,040 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/patient_summary.md (1850 chars, FK grade=6.82, in_band=False)
2026-05-03 05:47:32,042 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 16.78s
2026-05-03 05:47:32,042 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:48:04,523 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/summary.md (1828 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 05:48:04,523 INFO ehr_pipeline.runtime:   stage6_summarize done in 32.48s
2026-05-03 05:48:04,525 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:48:04,528 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=14 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/check_report.json
2026-05-03 05:48:04,528 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:48:04,529 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:48:21,564 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/review.json
2026-05-03 05:48:21,564 INFO ehr_pipeline.runtime:   stage8_review done in 17.04s
2026-05-03 05:48:21,565 INFO ehr_pipeline.pipeline:   applied revision: 'Heparin [E:note:row427484:2], coumadin [E:note:row427484:2],' → 'Heparin [E:note:row427484:2], coumadin [E:note:row427484:2],'
2026-05-03 05:48:21,566 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/summary_revised.md
2026-05-03 05:48:21,567 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:48:21,569 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=14 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/check_report_revised.json
2026-05-03 05:48:21,570 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:48:21,574 INFO ehr_pipeline.pipeline: Saved input note (2758 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/input_note.txt
2026-05-03 05:48:21,574 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-60919-137122-477434
2026-05-03 05:48:21,576 INFO ehr_pipeline.stages.s1_evidence:   wrote 67 evidence items (22 structured, 45 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/evidence_store.json
2026-05-03 05:48:21,576 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:48:21,576 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   201.13 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    86.85 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    16.78 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    32.48 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    17.04 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   354.29 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (1828 / 4222 chars)  [OUT OF BAND ✗]
  S7 det. check : FAIL ✗
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-79565-181839-427484/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-60919-137122-477434
  note_chars=2758  gold_concepts=10
==================================================================

2026-05-03 05:52:32,215 INFO ehr_pipeline.stages.s2_extract:   extracted 40 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/claims.json
2026-05-03 05:52:32,217 INFO ehr_pipeline.runtime:   stage2_extract done in 250.64s
2026-05-03 05:52:32,217 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 40 claims
2026-05-03 05:54:19,420 INFO ehr_pipeline.stages.s3_verify:   {'verified': 33, 'contradicted': 0, 'unsupported': 7} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/verifications.json
2026-05-03 05:54:19,422 INFO ehr_pipeline.runtime:   stage3_verify done in 107.21s
2026-05-03 05:54:19,423 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 05:54:19,425 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 05:54:19,426 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 40, 'medications': 8, 'labs': 5, 'vitals': 1, 'plan': 0}
2026-05-03 05:54:19,427 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 05:54:19,427 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 05:54:44,199 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/patient_summary.md (1939 chars, FK grade=7.72, in_band=True)
2026-05-03 05:54:44,200 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 24.77s
2026-05-03 05:54:44,201 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 05:55:17,993 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/summary.md (1305 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 05:55:17,995 INFO ehr_pipeline.runtime:   stage6_summarize done in 33.79s
2026-05-03 05:55:17,997 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:55:18,000 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/check_report.json
2026-05-03 05:55:18,000 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 05:55:18,001 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 05:55:24,136 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/review.json
2026-05-03 05:55:24,137 INFO ehr_pipeline.runtime:   stage8_review done in 6.14s
2026-05-03 05:55:24,138 INFO ehr_pipeline.pipeline:   applied revision: 'Hepatic encephalopathy [E:cond:2], portal hypertension [E:co' → 'Hepatic encephalopathy [E:cond:2], portal hypertension [E:co'
2026-05-03 05:55:24,139 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/summary_revised.md
2026-05-03 05:55:24,140 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 05:55:24,143 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/check_report_revised.json
2026-05-03 05:55:24,144 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 05:55:24,147 INFO ehr_pipeline.pipeline: Saved input note (2971 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/input_note.txt
2026-05-03 05:55:24,148 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-49930-144435-540683
2026-05-03 05:55:24,150 INFO ehr_pipeline.stages.s1_evidence:   wrote 90 evidence items (37 structured, 53 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/evidence_store.json
2026-05-03 05:55:24,150 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 05:55:24,150 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   250.64 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   107.21 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    24.77 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    33.79 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     6.14 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   422.56 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (1305 / 2758 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60919-137122-477434/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-49930-144435-540683
  note_chars=2971  gold_concepts=7
==================================================================

2026-05-03 05:57:23,953 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/claims.json
2026-05-03 05:57:23,956 INFO ehr_pipeline.runtime:   stage2_extract done in 119.81s
2026-05-03 05:57:23,957 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 06:01:06,775 INFO ehr_pipeline.stages.s3_verify:   {'verified': 27, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/verifications.json
2026-05-03 06:01:06,777 INFO ehr_pipeline.runtime:   stage3_verify done in 222.82s
2026-05-03 06:01:06,777 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:01:06,779 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:01:06,780 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 46, 'medications': 6, 'labs': 3, 'vitals': 3, 'plan': 1}
2026-05-03 06:01:06,780 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:01:06,780 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:01:28,981 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/patient_summary.md (1847 chars, FK grade=10.22, in_band=False)
2026-05-03 06:01:28,982 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 22.20s
2026-05-03 06:01:28,983 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:03:45,425 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/summary.md (1346 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 06:03:45,426 INFO ehr_pipeline.runtime:   stage6_summarize done in 136.44s
2026-05-03 06:03:45,427 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:03:45,430 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=16 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/check_report.json
2026-05-03 06:03:45,430 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:03:45,431 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:04:46,714 INFO ehr_pipeline.stages.s8_review:   concerns=5 recommended_revisions=5 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/review.json
2026-05-03 06:04:46,717 INFO ehr_pipeline.runtime:   stage8_review done in 61.29s
2026-05-03 06:04:46,718 INFO ehr_pipeline.pipeline:   applied revision: 'Other encephalopathy [E:cond:15] and asthma [E:cond:16].' → 'Other encephalopathy [E:cond:15].'
2026-05-03 06:04:46,719 INFO ehr_pipeline.pipeline:   applied revision: 'Tachycardia [E:note:row540683:48], liver function abnormalit' → 'Tachycardia [E:note:row540683:48].'
2026-05-03 06:04:46,719 INFO ehr_pipeline.pipeline:   applied revision: 'Abdominal wound [E:proc:5] with yellow fibrin/exudate [E:not' → ''
2026-05-03 06:04:46,720 INFO ehr_pipeline.pipeline:   applied revision: 'Start diuresis with lasix gtt [E:note:row540683:7].' → ''
2026-05-03 06:04:46,720 INFO ehr_pipeline.pipeline:   applied revision: 'Wean to CPAP [E:note:row540683:9] and wean fentanyl gtt as t' → 'Wean fentanyl gtt as tolerated [E:note:row540683:42].'
2026-05-03 06:04:46,721 INFO ehr_pipeline.pipeline: Wrote revised summary (5 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/summary_revised.md
2026-05-03 06:04:46,721 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:04:46,723 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=14 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/check_report_revised.json
2026-05-03 06:04:46,723 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:04:46,737 INFO ehr_pipeline.pipeline: Saved input note (3226 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/input_note.txt
2026-05-03 06:04:46,738 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-62795-173748-671473
2026-05-03 06:04:46,741 INFO ehr_pipeline.stages.s1_evidence:   wrote 199 evidence items (159 structured, 40 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/evidence_store.json
2026-05-03 06:04:46,741 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:04:46,741 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   119.81 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   222.82 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    22.20 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   136.44 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    61.29 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   562.56 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (1346 / 2971 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=5  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49930-144435-540683/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-62795-173748-671473
  note_chars=3226  gold_concepts=5
==================================================================

2026-05-03 06:06:38,456 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/claims.json
2026-05-03 06:06:38,457 INFO ehr_pipeline.runtime:   stage2_extract done in 111.72s
2026-05-03 06:06:38,458 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 06:10:43,325 INFO ehr_pipeline.stages.s3_verify:   {'verified': 29, 'contradicted': 0, 'unsupported': 8} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/verifications.json
2026-05-03 06:10:43,328 INFO ehr_pipeline.runtime:   stage3_verify done in 244.87s
2026-05-03 06:10:43,328 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:10:43,329 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:10:43,332 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 78, 'medications': 4, 'labs': 5, 'vitals': 1, 'plan': 1}
2026-05-03 06:10:43,332 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:10:43,333 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:11:28,538 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/patient_summary.md (1853 chars, FK grade=6.97, in_band=False)
2026-05-03 06:11:28,538 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 45.21s
2026-05-03 06:11:28,539 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:11:56,919 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/summary.md (1523 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 06:11:56,923 INFO ehr_pipeline.runtime:   stage6_summarize done in 28.38s
2026-05-03 06:11:56,924 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:11:56,927 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/check_report.json
2026-05-03 06:11:56,927 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:11:56,927 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:12:22,515 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/review.json
2026-05-03 06:12:22,516 INFO ehr_pipeline.runtime:   stage8_review done in 25.59s
2026-05-03 06:12:22,517 INFO ehr_pipeline.pipeline:   applied revision: 'Additional diagnoses include DM2 [E:note:row671473:3][E:cond' → 'Additional diagnoses include bacteremia [E:cond:21][E:cond:2'
2026-05-03 06:12:22,519 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/summary_revised.md
2026-05-03 06:12:22,520 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:12:22,522 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/check_report_revised.json
2026-05-03 06:12:22,523 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:12:22,530 INFO ehr_pipeline.pipeline: Saved input note (1217 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/input_note.txt
2026-05-03 06:12:22,530 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-46320-113335-462240
2026-05-03 06:12:22,534 INFO ehr_pipeline.stages.s1_evidence:   wrote 314 evidence items (301 structured, 13 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/evidence_store.json
2026-05-03 06:12:22,534 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:12:22,535 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   111.72 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   244.87 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    45.21 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    28.38 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    25.59 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   455.77 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (1523 / 3226 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671473/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-46320-113335-462240
  note_chars=1217  gold_concepts=9
==================================================================

2026-05-03 06:13:44,229 INFO ehr_pipeline.stages.s2_extract:   extracted 15 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/claims.json
2026-05-03 06:13:44,230 INFO ehr_pipeline.runtime:   stage2_extract done in 81.70s
2026-05-03 06:13:44,231 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 15 claims
2026-05-03 06:14:04,511 INFO ehr_pipeline.stages.s3_verify:   {'verified': 8, 'contradicted': 0, 'unsupported': 7} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/verifications.json
2026-05-03 06:14:04,512 INFO ehr_pipeline.runtime:   stage3_verify done in 20.28s
2026-05-03 06:14:04,513 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:14:04,515 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:14:04,518 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 50, 'medications': 1, 'labs': 0, 'vitals': 1, 'plan': 2}
2026-05-03 06:14:04,519 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:14:04,519 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:14:25,183 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/patient_summary.md (1535 chars, FK grade=7.96, in_band=True)
2026-05-03 06:14:25,183 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 20.66s
2026-05-03 06:14:25,184 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:14:36,862 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/summary.md (503 chars, ratio=0.41, target=0.20-0.30, in_band=False)
2026-05-03 06:14:36,864 INFO ehr_pipeline.runtime:   stage6_summarize done in 11.68s
2026-05-03 06:14:36,865 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:14:36,869 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/check_report.json
2026-05-03 06:14:36,870 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:14:36,870 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:14:42,698 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/review.json
2026-05-03 06:14:42,698 INFO ehr_pipeline.runtime:   stage8_review done in 5.83s
2026-05-03 06:14:42,699 INFO ehr_pipeline.pipeline:   applied revision: 'Also has DM II [E:cond:85], MRSA [E:cond:97], and Pseudomona' → 'Also has DM II [E:cond:85].'
2026-05-03 06:14:42,700 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/summary_revised.md
2026-05-03 06:14:42,701 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:14:42,703 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/check_report_revised.json
2026-05-03 06:14:42,704 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:14:42,710 INFO ehr_pipeline.pipeline: Saved input note (2859 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/input_note.txt
2026-05-03 06:14:42,710 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-94414-170244-665535
2026-05-03 06:14:42,712 INFO ehr_pipeline.stages.s1_evidence:   wrote 59 evidence items (24 structured, 35 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/evidence_store.json
2026-05-03 06:14:42,712 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:14:42,713 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    81.70 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    20.28 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    20.66 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    11.68 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     5.83 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   140.16 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.41  (503 / 1217 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462240/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-94414-170244-665535
  note_chars=2859  gold_concepts=11
==================================================================

2026-05-03 06:16:05,173 INFO ehr_pipeline.stages.s2_extract:   extracted 43 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/claims.json
2026-05-03 06:16:05,176 INFO ehr_pipeline.runtime:   stage2_extract done in 82.46s
2026-05-03 06:16:05,177 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 43 claims
2026-05-03 06:19:12,731 INFO ehr_pipeline.stages.s3_verify:   {'verified': 25, 'contradicted': 0, 'unsupported': 18} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/verifications.json
2026-05-03 06:19:12,733 INFO ehr_pipeline.runtime:   stage3_verify done in 187.56s
2026-05-03 06:19:12,734 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:19:12,735 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:19:12,737 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 34, 'medications': 6, 'labs': 4, 'vitals': 0, 'plan': 4}
2026-05-03 06:19:12,737 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:19:12,738 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:20:31,892 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/patient_summary.md (1684 chars, FK grade=5.74, in_band=False)
2026-05-03 06:20:31,894 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 79.16s
2026-05-03 06:20:31,894 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:21:05,193 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/summary.md (1389 chars, ratio=0.49, target=0.20-0.30, in_band=False)
2026-05-03 06:21:05,195 INFO ehr_pipeline.runtime:   stage6_summarize done in 33.30s
2026-05-03 06:21:05,197 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:21:05,200 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=14 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/check_report.json
2026-05-03 06:21:05,200 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:21:05,200 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:21:14,793 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/review.json
2026-05-03 06:21:14,794 INFO ehr_pipeline.runtime:   stage8_review done in 9.59s
2026-05-03 06:21:14,795 INFO ehr_pipeline.pipeline:   applied revision: 'Findings include mild pulmonary hypertension and no pulmonar' → ''
2026-05-03 06:21:14,797 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/summary_revised.md
2026-05-03 06:21:14,799 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:21:14,801 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/check_report_revised.json
2026-05-03 06:21:14,801 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:21:14,805 INFO ehr_pipeline.pipeline: Saved input note (12578 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/input_note.txt
2026-05-03 06:21:14,805 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-21137-101950-1574
2026-05-03 06:21:14,809 INFO ehr_pipeline.stages.s1_evidence:   wrote 143 evidence items (19 structured, 124 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/evidence_store.json
2026-05-03 06:21:14,809 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:21:14,809 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    82.46 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   187.56 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    79.16 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    33.30 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     9.59 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   392.08 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.49  (1389 / 2859 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-94414-170244-665535/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-21137-101950-1574
  note_chars=12578  gold_concepts=17
==================================================================

2026-05-03 06:31:14,846 WARNING ehr_pipeline.ollama_client: LLM JSON attempt 1/4 failed, appending error feedback and retrying: The read operation timed out
2026-05-03 06:34:23,250 INFO ehr_pipeline.stages.s2_extract:   extracted 50 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/claims.json
2026-05-03 06:34:23,253 INFO ehr_pipeline.runtime:   stage2_extract done in 788.45s
2026-05-03 06:34:23,253 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 50 claims
2026-05-03 06:37:54,226 INFO ehr_pipeline.stages.s3_verify:   {'verified': 36, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/verifications.json
2026-05-03 06:37:54,228 INFO ehr_pipeline.runtime:   stage3_verify done in 210.97s
2026-05-03 06:37:54,228 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:37:54,231 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:37:54,233 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 38, 'medications': 14, 'labs': 2, 'vitals': 0, 'plan': 0}
2026-05-03 06:37:54,234 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:37:54,234 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:38:14,819 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/patient_summary.md (1936 chars, FK grade=7.32, in_band=True)
2026-05-03 06:38:14,819 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 20.59s
2026-05-03 06:38:14,820 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:39:21,238 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/summary.md (2837 chars, ratio=0.23, target=0.20-0.30, in_band=True)
2026-05-03 06:39:21,239 INFO ehr_pipeline.runtime:   stage6_summarize done in 66.42s
2026-05-03 06:39:21,241 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:39:21,245 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/check_report.json
2026-05-03 06:39:21,246 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:39:21,246 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:39:31,710 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/review.json
2026-05-03 06:39:31,712 INFO ehr_pipeline.runtime:   stage8_review done in 10.47s
2026-05-03 06:39:31,712 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with complete atrioventricular block [E:con' → 'Patient presents with complete atrioventricular block [E:con'
2026-05-03 06:39:31,714 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/summary_revised.md
2026-05-03 06:39:31,715 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:39:31,719 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/check_report_revised.json
2026-05-03 06:39:31,720 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:39:31,725 INFO ehr_pipeline.pipeline: Saved input note (2275 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/input_note.txt
2026-05-03 06:39:31,725 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-99383-175736-674816
2026-05-03 06:39:31,727 INFO ehr_pipeline.stages.s1_evidence:   wrote 58 evidence items (32 structured, 26 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/evidence_store.json
2026-05-03 06:39:31,727 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:39:31,727 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   788.45 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   210.97 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    20.59 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    66.42 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    10.47 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1096.90 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.23  (2837 / 12578 chars)  [IN BAND ✓]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-21137-101950-1574/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-99383-175736-674816
  note_chars=2275  gold_concepts=5
==================================================================

2026-05-03 06:40:42,039 INFO ehr_pipeline.stages.s2_extract:   extracted 41 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/claims.json
2026-05-03 06:40:42,040 INFO ehr_pipeline.runtime:   stage2_extract done in 70.31s
2026-05-03 06:40:42,041 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 41 claims
2026-05-03 06:42:10,846 INFO ehr_pipeline.stages.s3_verify:   {'verified': 29, 'contradicted': 0, 'unsupported': 12} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/verifications.json
2026-05-03 06:42:10,849 INFO ehr_pipeline.runtime:   stage3_verify done in 88.81s
2026-05-03 06:42:10,849 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:42:10,851 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:42:10,852 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 41, 'medications': 6, 'labs': 3, 'vitals': 2, 'plan': 6}
2026-05-03 06:42:10,852 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:42:10,853 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:42:35,167 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/patient_summary.md (1953 chars, FK grade=7.91, in_band=True)
2026-05-03 06:42:35,168 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 24.32s
2026-05-03 06:42:35,169 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:42:46,170 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/summary.md (1233 chars, ratio=0.54, target=0.20-0.30, in_band=False)
2026-05-03 06:42:46,171 INFO ehr_pipeline.runtime:   stage6_summarize done in 11.00s
2026-05-03 06:42:46,175 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:42:46,177 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/check_report.json
2026-05-03 06:42:46,177 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:42:46,178 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:43:14,328 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/review.json
2026-05-03 06:43:14,329 INFO ehr_pipeline.runtime:   stage8_review done in 28.15s
2026-05-03 06:43:14,329 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with hemorrhagic Dieulafoy lesion of stomac' → 'Patient presents with hemorrhagic Dieulafoy lesion of stomac'
2026-05-03 06:43:14,330 INFO ehr_pipeline.pipeline:   applied revision: 'Comorbidities include acute pancreatitis [E:cond:2][E:note:r' → 'Comorbidities include acute pancreatitis [E:cond:2], septic '
2026-05-03 06:43:14,330 INFO ehr_pipeline.pipeline:   applied revision: 'Other issues include anoxic brain damage [E:cond:9], cardiac' → 'Other issues include anoxic brain damage [E:cond:9] and card'
2026-05-03 06:43:14,332 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/summary_revised.md
2026-05-03 06:43:14,332 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:43:14,334 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/check_report_revised.json
2026-05-03 06:43:14,334 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:43:14,339 INFO ehr_pipeline.pipeline: Saved input note (2578 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/input_note.txt
2026-05-03 06:43:14,340 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-98220-173136-442600
2026-05-03 06:43:14,344 INFO ehr_pipeline.stages.s1_evidence:   wrote 83 evidence items (59 structured, 24 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/evidence_store.json
2026-05-03 06:43:14,344 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:43:14,345 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    70.31 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    88.81 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    24.32 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    11.00 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    28.15 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   222.60 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.54  (1233 / 2275 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99383-175736-674816/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-98220-173136-442600
  note_chars=2578  gold_concepts=6
==================================================================

2026-05-03 06:44:45,415 INFO ehr_pipeline.stages.s2_extract:   extracted 48 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/claims.json
2026-05-03 06:44:45,417 INFO ehr_pipeline.runtime:   stage2_extract done in 91.07s
2026-05-03 06:44:45,418 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 48 claims
2026-05-03 06:49:11,611 INFO ehr_pipeline.stages.s3_verify:   {'verified': 27, 'contradicted': 0, 'unsupported': 21} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/verifications.json
2026-05-03 06:49:11,613 INFO ehr_pipeline.runtime:   stage3_verify done in 266.20s
2026-05-03 06:49:11,613 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:49:11,616 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:49:11,617 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 72, 'medications': 2, 'labs': 1, 'vitals': 1, 'plan': 2}
2026-05-03 06:49:11,618 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:49:11,618 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:49:24,097 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/patient_summary.md (1810 chars, FK grade=7.14, in_band=True)
2026-05-03 06:49:24,098 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 12.48s
2026-05-03 06:49:24,099 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 06:49:50,058 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/summary.md (1215 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 06:49:50,059 INFO ehr_pipeline.runtime:   stage6_summarize done in 25.96s
2026-05-03 06:49:50,060 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:49:50,063 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=11 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/check_report.json
2026-05-03 06:49:50,063 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 06:49:50,064 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 06:50:51,244 INFO ehr_pipeline.stages.s8_review:   concerns=5 recommended_revisions=5 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/review.json
2026-05-03 06:50:51,246 INFO ehr_pipeline.runtime:   stage8_review done in 61.18s
2026-05-03 06:50:51,247 INFO ehr_pipeline.pipeline:   applied revision: 'Malignant neoplasm of ampulla of vater [E:cond:2] and adenoc' → 'Malignant neoplasm of ampulla of vater [E:cond:2].'
2026-05-03 06:50:51,247 INFO ehr_pipeline.pipeline:   applied revision: 'Benign liver/biliary neoplasm [E:cond:1], bile duct obstruct' → 'Benign neoplasm of liver and biliary passages [E:cond:1] and'
2026-05-03 06:50:51,248 INFO ehr_pipeline.pipeline:   applied revision: 'Acute kidney failure with tubular necrosis [E:cond:15] and u' → 'Acute kidney failure with lesion of tubular necrosis [E:cond'
2026-05-03 06:50:51,248 INFO ehr_pipeline.pipeline:   applied revision: 'Anemia [E:cond:23], thrombocytopenia [E:cond:22], HTN [E:not' → ''
2026-05-03 06:50:51,249 INFO ehr_pipeline.pipeline:   applied revision: 'Drug-induced dermatitis [E:cond:25] and rash attributed to Z' → ''
2026-05-03 06:50:51,250 INFO ehr_pipeline.pipeline: Wrote revised summary (5 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/summary_revised.md
2026-05-03 06:50:51,250 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 06:50:51,252 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/check_report_revised.json
2026-05-03 06:50:51,252 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 06:50:51,257 INFO ehr_pipeline.pipeline: Saved input note (3066 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/input_note.txt
2026-05-03 06:50:51,258 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-85464-164726-465683
2026-05-03 06:50:51,260 INFO ehr_pipeline.stages.s1_evidence:   wrote 88 evidence items (41 structured, 47 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/evidence_store.json
2026-05-03 06:50:51,260 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 06:50:51,260 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    91.07 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   266.20 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    12.48 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    25.96 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    61.18 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   456.90 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (1215 / 2578 chars)  [OUT OF BAND ✗]
  S7 det. check : FAIL ✗
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=2  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-98220-173136-442600/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-85464-164726-465683
  note_chars=3066  gold_concepts=8
==================================================================

2026-05-03 06:53:01,971 INFO ehr_pipeline.stages.s2_extract:   extracted 41 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/claims.json
2026-05-03 06:53:01,974 INFO ehr_pipeline.runtime:   stage2_extract done in 130.71s
2026-05-03 06:53:01,975 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 41 claims
2026-05-03 06:59:03,386 INFO ehr_pipeline.stages.s3_verify:   {'verified': 31, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/verifications.json
2026-05-03 06:59:03,388 INFO ehr_pipeline.runtime:   stage3_verify done in 361.41s
2026-05-03 06:59:03,388 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 06:59:03,390 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 06:59:03,391 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 30, 'medications': 7, 'labs': 3, 'vitals': 2, 'plan': 9}
2026-05-03 06:59:03,392 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 06:59:03,392 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 06:59:49,109 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/patient_summary.md (1872 chars, FK grade=7.34, in_band=True)
2026-05-03 06:59:49,110 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 45.72s
2026-05-03 06:59:49,111 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:01:14,660 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/summary.md (1659 chars, ratio=0.54, target=0.20-0.30, in_band=False)
2026-05-03 07:01:14,661 INFO ehr_pipeline.runtime:   stage6_summarize done in 85.55s
2026-05-03 07:01:14,664 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:01:14,667 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/check_report.json
2026-05-03 07:01:14,668 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:01:14,669 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:01:36,164 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/review.json
2026-05-03 07:01:36,165 INFO ehr_pipeline.runtime:   stage8_review done in 21.50s
2026-05-03 07:01:36,166 INFO ehr_pipeline.pipeline:   applied revision: 'Other diagnoses include UTI with suprapubic discomfort [E:co' → 'Other diagnoses include UTI [E:cond:11][E:cond:12] and chron'
2026-05-03 07:01:36,166 INFO ehr_pipeline.pipeline:   applied revision: 'Renal issues include acute kidney failure with tubular necro' → 'Renal issues include acute kidney failure with tubular necro'
2026-05-03 07:01:36,167 INFO ehr_pipeline.pipeline:   applied revision: 'Procedures performed include temporary transvenous pacemaker' → 'Procedures performed include temporary transvenous pacing [E'
2026-05-03 07:01:36,170 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/summary_revised.md
2026-05-03 07:01:36,171 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:01:36,173 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/check_report_revised.json
2026-05-03 07:01:36,173 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:01:36,177 INFO ehr_pipeline.pipeline: Saved input note (2068 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/input_note.txt
2026-05-03 07:01:36,178 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-68589-152895-642898
2026-05-03 07:01:36,179 INFO ehr_pipeline.stages.s1_evidence:   wrote 50 evidence items (45 structured, 5 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/evidence_store.json
2026-05-03 07:01:36,180 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:01:36,180 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   130.71 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   361.41 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    45.72 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    85.55 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    21.50 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   644.90 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.54  (1659 / 3066 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-85464-164726-465683/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-68589-152895-642898
  note_chars=2068  gold_concepts=14
==================================================================

2026-05-03 07:03:37,204 INFO ehr_pipeline.stages.s2_extract:   extracted 28 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/claims.json
2026-05-03 07:03:37,205 INFO ehr_pipeline.runtime:   stage2_extract done in 121.03s
2026-05-03 07:03:37,206 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 28 claims
2026-05-03 07:04:26,968 INFO ehr_pipeline.stages.s3_verify:   {'verified': 6, 'contradicted': 0, 'unsupported': 22} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/verifications.json
2026-05-03 07:04:26,968 INFO ehr_pipeline.runtime:   stage3_verify done in 49.76s
2026-05-03 07:04:26,969 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:04:26,971 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:04:26,973 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 24, 'medications': 0, 'labs': 0, 'vitals': 0, 'plan': 3}
2026-05-03 07:04:26,973 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:04:26,974 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:05:10,930 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/patient_summary.md (1506 chars, FK grade=7.63, in_band=True)
2026-05-03 07:05:10,931 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 43.96s
2026-05-03 07:05:10,931 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:05:18,610 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/summary.md (820 chars, ratio=0.40, target=0.20-0.30, in_band=False)
2026-05-03 07:05:18,611 INFO ehr_pipeline.runtime:   stage6_summarize done in 7.68s
2026-05-03 07:05:18,613 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:05:18,617 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/check_report.json
2026-05-03 07:05:18,617 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:05:18,618 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:05:28,926 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/review.json
2026-05-03 07:05:28,927 INFO ehr_pipeline.runtime:   stage8_review done in 10.31s
2026-05-03 07:05:28,928 INFO ehr_pipeline.pipeline:   applied revision: 'Other cardiac dysrhythmias [E:cond:21][E:cond:22], acquired ' → 'Other cardiac dysrhythmias [E:cond:21][E:cond:22] and acquir'
2026-05-03 07:05:28,929 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/summary_revised.md
2026-05-03 07:05:28,929 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:05:28,930 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/check_report_revised.json
2026-05-03 07:05:28,930 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:05:28,933 INFO ehr_pipeline.pipeline: Saved input note (3955 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/input_note.txt
2026-05-03 07:05:28,934 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-91529-176840-424485
2026-05-03 07:05:28,935 INFO ehr_pipeline.stages.s1_evidence:   wrote 80 evidence items (21 structured, 59 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/evidence_store.json
2026-05-03 07:05:28,935 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:05:28,936 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   121.03 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    49.76 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    43.96 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     7.68 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    10.31 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   232.74 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.40  (820 / 2068 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642898/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-91529-176840-424485
  note_chars=3955  gold_concepts=9
==================================================================

2026-05-03 07:07:25,424 INFO ehr_pipeline.stages.s2_extract:   extracted 42 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/claims.json
2026-05-03 07:07:25,426 INFO ehr_pipeline.runtime:   stage2_extract done in 116.49s
2026-05-03 07:07:25,427 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 42 claims
2026-05-03 07:10:22,195 INFO ehr_pipeline.stages.s3_verify:   {'verified': 34, 'contradicted': 0, 'unsupported': 8} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/verifications.json
2026-05-03 07:10:22,195 INFO ehr_pipeline.runtime:   stage3_verify done in 176.77s
2026-05-03 07:10:22,196 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:10:22,199 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:10:22,200 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 34, 'medications': 8, 'labs': 3, 'vitals': 6, 'plan': 3}
2026-05-03 07:10:22,201 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:10:22,201 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:12:11,973 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/patient_summary.md (1707 chars, FK grade=4.54, in_band=False)
2026-05-03 07:12:11,976 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 109.77s
2026-05-03 07:12:11,977 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:13:49,830 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/summary.md (2329 chars, ratio=0.59, target=0.20-0.30, in_band=False)
2026-05-03 07:13:49,831 INFO ehr_pipeline.runtime:   stage6_summarize done in 97.85s
2026-05-03 07:13:49,833 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:13:49,836 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/check_report.json
2026-05-03 07:13:49,837 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:13:49,837 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:13:56,515 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/review.json
2026-05-03 07:13:56,516 INFO ehr_pipeline.runtime:   stage8_review done in 6.68s
2026-05-03 07:13:56,517 INFO ehr_pipeline.pipeline:   applied revision: 'Current diagnoses include acute myocardial infarction (AMI, ' → 'Current diagnoses include subendocardial infarction [E:cond:'
2026-05-03 07:13:56,520 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/summary_revised.md
2026-05-03 07:13:56,520 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:13:56,522 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/check_report_revised.json
2026-05-03 07:13:56,522 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:13:56,527 INFO ehr_pipeline.pipeline: Saved input note (2034 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/input_note.txt
2026-05-03 07:13:56,528 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-92525-141986-498276
2026-05-03 07:13:56,529 INFO ehr_pipeline.stages.s1_evidence:   wrote 37 evidence items (27 structured, 10 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/evidence_store.json
2026-05-03 07:13:56,529 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:13:56,529 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   116.49 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   176.77 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   109.77 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    97.85 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     6.68 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   507.57 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.59  (2329 / 3955 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91529-176840-424485/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-92525-141986-498276
  note_chars=2034  gold_concepts=8
==================================================================

2026-05-03 07:16:05,848 INFO ehr_pipeline.stages.s2_extract:   extracted 44 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/claims.json
2026-05-03 07:16:05,849 INFO ehr_pipeline.runtime:   stage2_extract done in 129.32s
2026-05-03 07:16:05,850 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 44 claims
2026-05-03 07:18:18,890 INFO ehr_pipeline.stages.s3_verify:   {'verified': 15, 'contradicted': 0, 'unsupported': 29} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/verifications.json
2026-05-03 07:18:18,891 INFO ehr_pipeline.runtime:   stage3_verify done in 133.04s
2026-05-03 07:18:18,891 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:18:18,895 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:18:18,896 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 36, 'medications': 1, 'labs': 2, 'vitals': 1, 'plan': 0}
2026-05-03 07:18:18,896 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:18:18,897 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:19:06,898 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/patient_summary.md (1303 chars, FK grade=6.06, in_band=False)
2026-05-03 07:19:06,899 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 48.00s
2026-05-03 07:19:06,900 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:19:16,351 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/summary.md (670 chars, ratio=0.33, target=0.20-0.30, in_band=False)
2026-05-03 07:19:16,352 INFO ehr_pipeline.runtime:   stage6_summarize done in 9.45s
2026-05-03 07:19:16,353 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:19:16,355 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/check_report.json
2026-05-03 07:19:16,356 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:19:16,356 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:19:30,551 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/review.json
2026-05-03 07:19:30,552 INFO ehr_pipeline.runtime:   stage8_review done in 14.20s
2026-05-03 07:19:30,553 INFO ehr_pipeline.pipeline:   applied revision: 'Basilar artery occlusion/stenosis with cerebral infarction [' → 'Basilar artery occlusion/stenosis with cerebral infarction ['
2026-05-03 07:19:30,553 INFO ehr_pipeline.pipeline:   applied revision: 'Acute on chronic diastolic heart failure [E:cond:2], CHF [E:' → 'Acute on chronic diastolic heart failure [E:cond:2], CHF [E:'
2026-05-03 07:19:30,554 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/summary_revised.md
2026-05-03 07:19:30,555 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:19:30,557 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/check_report_revised.json
2026-05-03 07:19:30,558 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:19:30,562 INFO ehr_pipeline.pipeline: Saved input note (1160 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/input_note.txt
2026-05-03 07:19:30,562 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-73444-198874-514575
2026-05-03 07:19:30,564 INFO ehr_pipeline.stages.s1_evidence:   wrote 46 evidence items (39 structured, 7 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/evidence_store.json
2026-05-03 07:19:30,564 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:19:30,564 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   129.32 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   133.04 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    48.00 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     9.45 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    14.20 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   334.02 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.33  (670 / 2034 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92525-141986-498276/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-73444-198874-514575
  note_chars=1160  gold_concepts=7
==================================================================

2026-05-03 07:20:17,241 INFO ehr_pipeline.stages.s2_extract:   extracted 19 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/claims.json
2026-05-03 07:20:17,242 INFO ehr_pipeline.runtime:   stage2_extract done in 46.68s
2026-05-03 07:20:17,243 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 19 claims
2026-05-03 07:21:15,515 INFO ehr_pipeline.stages.s3_verify:   {'verified': 5, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/verifications.json
2026-05-03 07:21:15,515 INFO ehr_pipeline.runtime:   stage3_verify done in 58.27s
2026-05-03 07:21:15,516 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:21:15,518 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:21:15,519 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 36, 'medications': 0, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-03 07:21:15,520 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:21:15,520 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:21:30,496 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/patient_summary.md (1266 chars, FK grade=7.55, in_band=True)
2026-05-03 07:21:30,497 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.98s
2026-05-03 07:21:30,497 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:21:34,416 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/summary.md (394 chars, ratio=0.34, target=0.20-0.30, in_band=False)
2026-05-03 07:21:34,416 INFO ehr_pipeline.runtime:   stage6_summarize done in 3.92s
2026-05-03 07:21:34,418 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:21:34,419 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/check_report.json
2026-05-03 07:21:34,420 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:21:34,420 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:21:47,172 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/review.json
2026-05-03 07:21:47,175 INFO ehr_pipeline.runtime:   stage8_review done in 12.75s
2026-05-03 07:21:47,175 INFO ehr_pipeline.pipeline:   applied revision: 'Subendocardial infarction [E:cond:1], NSTEMI [E:note:row5145' → 'Subendocardial infarction [E:cond:1], acute respiratory fail'
2026-05-03 07:21:47,179 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/summary_revised.md
2026-05-03 07:21:47,179 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:21:47,181 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/check_report_revised.json
2026-05-03 07:21:47,182 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:21:47,187 INFO ehr_pipeline.pipeline: Saved input note (1788 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/input_note.txt
2026-05-03 07:21:47,188 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-32303-185638-472970
2026-05-03 07:21:47,190 INFO ehr_pipeline.stages.s1_evidence:   wrote 32 evidence items (31 structured, 1 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/evidence_store.json
2026-05-03 07:21:47,190 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:21:47,191 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    46.68 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    58.27 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.98 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     3.92 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.75 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   136.61 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.34  (394 / 1160 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-73444-198874-514575/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-32303-185638-472970
  note_chars=1788  gold_concepts=6
==================================================================

2026-05-03 07:23:36,158 INFO ehr_pipeline.stages.s2_extract:   extracted 29 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/claims.json
2026-05-03 07:23:36,159 INFO ehr_pipeline.runtime:   stage2_extract done in 108.97s
2026-05-03 07:23:36,160 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 29 claims
2026-05-03 07:23:49,460 INFO ehr_pipeline.stages.s3_verify:   {'verified': 1, 'contradicted': 0, 'unsupported': 28} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/verifications.json
2026-05-03 07:23:49,461 INFO ehr_pipeline.runtime:   stage3_verify done in 13.30s
2026-05-03 07:23:49,461 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:23:49,464 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:23:49,465 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 31, 'medications': 0, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-03 07:23:49,466 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:23:49,466 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:24:01,302 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/patient_summary.md (1516 chars, FK grade=11.58, in_band=False)
2026-05-03 07:24:01,303 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 11.84s
2026-05-03 07:24:01,305 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:24:06,626 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/summary.md (642 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 07:24:06,627 INFO ehr_pipeline.runtime:   stage6_summarize done in 5.32s
2026-05-03 07:24:06,629 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:24:06,631 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/check_report.json
2026-05-03 07:24:06,632 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:24:06,633 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:24:12,564 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/review.json
2026-05-03 07:24:12,566 INFO ehr_pipeline.runtime:   stage8_review done in 5.93s
2026-05-03 07:24:12,566 INFO ehr_pipeline.pipeline:   applied revision: 'Patient has septic shock [E:cond:4], severe sepsis [E:cond:1' → 'Patient has septic shock [E:cond:4], severe sepsis [E:cond:1'
2026-05-03 07:24:12,567 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/summary_revised.md
2026-05-03 07:24:12,568 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:24:12,570 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/check_report_revised.json
2026-05-03 07:24:12,571 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:24:12,575 INFO ehr_pipeline.pipeline: Saved input note (2061 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/input_note.txt
2026-05-03 07:24:12,576 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-54348-123562-690291
2026-05-03 07:24:12,577 INFO ehr_pipeline.stages.s1_evidence:   wrote 66 evidence items (42 structured, 24 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/evidence_store.json
2026-05-03 07:24:12,578 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:24:12,578 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   108.97 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    13.30 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    11.84 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     5.32 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     5.93 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   145.37 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (642 / 1788 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32303-185638-472970/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-54348-123562-690291
  note_chars=2061  gold_concepts=10
==================================================================

2026-05-03 07:25:45,549 INFO ehr_pipeline.stages.s2_extract:   extracted 25 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/claims.json
2026-05-03 07:25:45,550 INFO ehr_pipeline.runtime:   stage2_extract done in 92.97s
2026-05-03 07:25:45,551 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 25 claims
2026-05-03 07:26:46,395 INFO ehr_pipeline.stages.s3_verify:   {'verified': 16, 'contradicted': 0, 'unsupported': 9} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/verifications.json
2026-05-03 07:26:46,396 INFO ehr_pipeline.runtime:   stage3_verify done in 60.85s
2026-05-03 07:26:46,397 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:26:46,398 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:26:46,400 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 44, 'medications': 6, 'labs': 1, 'vitals': 2, 'plan': 3}
2026-05-03 07:26:46,400 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:26:46,401 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:27:00,809 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/patient_summary.md (1918 chars, FK grade=8.12, in_band=False)
2026-05-03 07:27:00,810 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.41s
2026-05-03 07:27:00,811 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:27:19,320 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/summary.md (1220 chars, ratio=0.59, target=0.20-0.30, in_band=False)
2026-05-03 07:27:19,321 INFO ehr_pipeline.runtime:   stage6_summarize done in 18.51s
2026-05-03 07:27:19,324 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:27:19,328 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/check_report.json
2026-05-03 07:27:19,329 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:27:19,329 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:27:20,676 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/review.json
2026-05-03 07:27:20,677 INFO ehr_pipeline.runtime:   stage8_review done in 1.35s
2026-05-03 07:27:20,678 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 07:27:20,684 INFO ehr_pipeline.pipeline: Saved input note (2443 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/input_note.txt
2026-05-03 07:27:20,685 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-43126-132026-495137
2026-05-03 07:27:20,686 INFO ehr_pipeline.stages.s1_evidence:   wrote 113 evidence items (89 structured, 24 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/evidence_store.json
2026-05-03 07:27:20,687 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:27:20,687 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    92.97 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    60.85 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.41 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    18.51 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     1.35 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   188.09 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.59  (1220 / 2061 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-54348-123562-690291/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-43126-132026-495137
  note_chars=2443  gold_concepts=8
==================================================================

2026-05-03 07:30:21,923 INFO ehr_pipeline.stages.s2_extract:   extracted 36 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/claims.json
2026-05-03 07:30:21,924 INFO ehr_pipeline.runtime:   stage2_extract done in 181.24s
2026-05-03 07:30:21,925 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 36 claims
2026-05-03 07:32:34,329 INFO ehr_pipeline.stages.s3_verify:   {'verified': 24, 'contradicted': 0, 'unsupported': 12} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/verifications.json
2026-05-03 07:32:34,330 INFO ehr_pipeline.runtime:   stage3_verify done in 132.41s
2026-05-03 07:32:34,331 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:32:34,333 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:32:34,336 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 57, 'medications': 3, 'labs': 2, 'vitals': 0, 'plan': 3}
2026-05-03 07:32:34,337 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:32:34,337 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:32:49,281 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/patient_summary.md (1770 chars, FK grade=8.76, in_band=False)
2026-05-03 07:32:49,282 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.94s
2026-05-03 07:32:49,282 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:33:00,646 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/summary.md (1096 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 07:33:00,648 INFO ehr_pipeline.runtime:   stage6_summarize done in 11.37s
2026-05-03 07:33:00,651 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:33:00,653 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/check_report.json
2026-05-03 07:33:00,654 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:33:00,654 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:33:20,586 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/review.json
2026-05-03 07:33:20,587 INFO ehr_pipeline.runtime:   stage8_review done in 19.93s
2026-05-03 07:33:20,587 INFO ehr_pipeline.pipeline:   applied revision: 'Patient has CLL with large cell transformation [E:note:row49' → 'Patient has CLL in remission [E:note:row495137:1], severe se'
2026-05-03 07:33:20,589 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/summary_revised.md
2026-05-03 07:33:20,590 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:33:20,592 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/check_report_revised.json
2026-05-03 07:33:20,592 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:33:20,596 INFO ehr_pipeline.pipeline: Saved input note (1485 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/input_note.txt
2026-05-03 07:33:20,596 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-41612-108873-496723
2026-05-03 07:33:20,598 INFO ehr_pipeline.stages.s1_evidence:   wrote 43 evidence items (32 structured, 11 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/evidence_store.json
2026-05-03 07:33:20,598 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:33:20,598 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   181.24 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   132.41 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.94 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    11.37 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    19.93 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   359.90 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (1096 / 2443 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495137/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-41612-108873-496723
  note_chars=1485  gold_concepts=12
==================================================================

2026-05-03 07:34:50,906 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/claims.json
2026-05-03 07:34:50,907 INFO ehr_pipeline.runtime:   stage2_extract done in 90.31s
2026-05-03 07:34:50,907 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 07:35:57,188 INFO ehr_pipeline.stages.s3_verify:   {'verified': 20, 'contradicted': 0, 'unsupported': 17} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/verifications.json
2026-05-03 07:35:57,189 INFO ehr_pipeline.runtime:   stage3_verify done in 66.28s
2026-05-03 07:35:57,190 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:35:57,193 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:35:57,194 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 40, 'medications': 2, 'labs': 0, 'vitals': 2, 'plan': 4}
2026-05-03 07:35:57,195 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:35:57,195 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:36:11,214 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/patient_summary.md (1783 chars, FK grade=7.82, in_band=True)
2026-05-03 07:36:11,215 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.02s
2026-05-03 07:36:11,215 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:36:20,344 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/summary.md (765 chars, ratio=0.52, target=0.20-0.30, in_band=False)
2026-05-03 07:36:20,345 INFO ehr_pipeline.runtime:   stage6_summarize done in 9.13s
2026-05-03 07:36:20,346 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:36:20,348 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/check_report.json
2026-05-03 07:36:20,348 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:36:20,349 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:36:27,424 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/review.json
2026-05-03 07:36:27,425 INFO ehr_pipeline.runtime:   stage8_review done in 7.08s
2026-05-03 07:36:27,425 INFO ehr_pipeline.pipeline:   applied revision: 'Sepsis, bacterial pneumonia, acute respiratory failure [E:co' → 'Sepsis, bacterial pneumonia, acute respiratory failure [E:co'
2026-05-03 07:36:27,426 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/summary_revised.md
2026-05-03 07:36:27,426 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:36:27,427 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/check_report_revised.json
2026-05-03 07:36:27,427 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:36:27,431 INFO ehr_pipeline.pipeline: Saved input note (1601 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/input_note.txt
2026-05-03 07:36:27,431 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-32504-149115-415025
2026-05-03 07:36:27,432 INFO ehr_pipeline.stages.s1_evidence:   wrote 46 evidence items (38 structured, 8 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/evidence_store.json
2026-05-03 07:36:27,432 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:36:27,433 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    90.31 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    66.28 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.02 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     9.13 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     7.08 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   186.82 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.52  (765 / 1485 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41612-108873-496723/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-32504-149115-415025
  note_chars=1601  gold_concepts=7
==================================================================

2026-05-03 07:37:53,008 INFO ehr_pipeline.stages.s2_extract:   extracted 33 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/claims.json
2026-05-03 07:37:53,009 INFO ehr_pipeline.runtime:   stage2_extract done in 85.58s
2026-05-03 07:37:53,009 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 33 claims
2026-05-03 07:38:29,864 INFO ehr_pipeline.stages.s3_verify:   {'verified': 13, 'contradicted': 1, 'unsupported': 19} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/verifications.json
2026-05-03 07:38:29,865 INFO ehr_pipeline.runtime:   stage3_verify done in 36.86s
2026-05-03 07:38:29,865 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:38:29,869 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:38:29,870 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 48, 'medications': 0, 'labs': 0, 'vitals': 2, 'plan': 0}
2026-05-03 07:38:29,871 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:38:29,871 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:38:45,154 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/patient_summary.md (1648 chars, FK grade=8.05, in_band=False)
2026-05-03 07:38:45,154 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.28s
2026-05-03 07:38:45,155 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:38:51,106 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/summary.md (568 chars, ratio=0.35, target=0.20-0.30, in_band=False)
2026-05-03 07:38:51,107 INFO ehr_pipeline.runtime:   stage6_summarize done in 5.95s
2026-05-03 07:38:51,108 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:38:51,110 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/check_report.json
2026-05-03 07:38:51,111 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:38:51,112 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:39:03,657 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/review.json
2026-05-03 07:39:03,658 INFO ehr_pipeline.runtime:   stage8_review done in 12.55s
2026-05-03 07:39:03,659 INFO ehr_pipeline.pipeline:   applied revision: 'Acute kidney failure with tubular necrosis [E:cond:3][E:cond' → 'Acute kidney failure with tubular necrosis [E:cond:3][E:cond'
2026-05-03 07:39:03,659 INFO ehr_pipeline.pipeline:   applied revision: 'CHF [E:cond:4][E:cond:16], AFib [E:cond:20], and coronary at' → 'Chronic systolic heart failure [E:cond:4].'
2026-05-03 07:39:03,662 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/summary_revised.md
2026-05-03 07:39:03,664 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:39:03,666 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/check_report_revised.json
2026-05-03 07:39:03,666 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 07:39:03,669 INFO ehr_pipeline.pipeline: Saved input note (17143 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/input_note.txt
2026-05-03 07:39:03,670 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-17041-175730-1473
2026-05-03 07:39:03,673 INFO ehr_pipeline.stages.s1_evidence:   wrote 194 evidence items (37 structured, 157 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/evidence_store.json
2026-05-03 07:39:03,673 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:39:03,674 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    85.58 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    36.86 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.28 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     5.95 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.55 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   156.22 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.35  (568 / 1601 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-32504-149115-415025/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-17041-175730-1473
  note_chars=17143  gold_concepts=18
==================================================================

2026-05-03 07:41:48,093 INFO ehr_pipeline.stages.s2_extract:   extracted 77 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/claims.json
2026-05-03 07:41:48,094 INFO ehr_pipeline.runtime:   stage2_extract done in 164.42s
2026-05-03 07:41:48,094 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 77 claims
2026-05-03 07:45:17,521 INFO ehr_pipeline.stages.s3_verify:   {'verified': 32, 'contradicted': 1, 'unsupported': 44} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/verifications.json
2026-05-03 07:45:17,522 INFO ehr_pipeline.runtime:   stage3_verify done in 209.43s
2026-05-03 07:45:17,522 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:45:17,525 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:45:17,527 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 48, 'medications': 12, 'labs': 8, 'vitals': 0, 'plan': 0}
2026-05-03 07:45:17,527 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:45:17,528 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 07:49:46,940 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/patient_summary.md (1725 chars, FK grade=6.85, in_band=False)
2026-05-03 07:49:46,941 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 269.41s
2026-05-03 07:49:46,942 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 07:52:20,951 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/summary.md (3323 chars, ratio=0.19, target=0.20-0.30, in_band=False)
2026-05-03 07:52:20,953 INFO ehr_pipeline.runtime:   stage6_summarize done in 154.01s
2026-05-03 07:52:20,954 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 07:52:20,958 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=55 violations=5 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/check_report.json
2026-05-03 07:52:20,959 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 07:52:20,959 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 07:52:22,586 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/review.json
2026-05-03 07:52:22,587 INFO ehr_pipeline.runtime:   stage8_review done in 1.63s
2026-05-03 07:52:22,587 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 07:52:22,593 INFO ehr_pipeline.pipeline: Saved input note (2794 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/input_note.txt
2026-05-03 07:52:22,593 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-53474-177016-556185
2026-05-03 07:52:22,595 INFO ehr_pipeline.stages.s1_evidence:   wrote 57 evidence items (25 structured, 32 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/evidence_store.json
2026-05-03 07:52:22,596 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 07:52:22,596 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   164.42 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   209.43 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   269.41 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   154.01 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     1.63 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   798.91 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.19  (3323 / 17143 chars)  [OUT OF BAND ✗]
  S7 det. check : FAIL ✗
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17041-175730-1473/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-53474-177016-556185
  note_chars=2794  gold_concepts=7
==================================================================

2026-05-03 07:56:42,891 INFO ehr_pipeline.stages.s2_extract:   extracted 41 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/claims.json
2026-05-03 07:56:42,892 INFO ehr_pipeline.runtime:   stage2_extract done in 260.30s
2026-05-03 07:56:42,893 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 41 claims
2026-05-03 07:59:53,769 INFO ehr_pipeline.stages.s3_verify:   {'verified': 24, 'contradicted': 0, 'unsupported': 17} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/verifications.json
2026-05-03 07:59:53,770 INFO ehr_pipeline.runtime:   stage3_verify done in 190.88s
2026-05-03 07:59:53,770 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 07:59:53,774 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 07:59:53,775 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 42, 'medications': 2, 'labs': 0, 'vitals': 3, 'plan': 1}
2026-05-03 07:59:53,775 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 07:59:53,776 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:00:45,889 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/patient_summary.md (1582 chars, FK grade=8.47, in_band=False)
2026-05-03 08:00:45,890 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 52.11s
2026-05-03 08:00:45,891 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:01:35,656 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 0.7s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 42326469-b086-4a40-b0fd-a396923bae21)
2026-05-03 08:01:49,990 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/summary.md (901 chars, ratio=0.32, target=0.20-0.30, in_band=False)
2026-05-03 08:01:49,991 INFO ehr_pipeline.runtime:   stage6_summarize done in 64.10s
2026-05-03 08:01:49,992 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:01:49,995 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/check_report.json
2026-05-03 08:01:49,995 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:01:49,996 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:01:54,805 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/review.json
2026-05-03 08:01:54,807 INFO ehr_pipeline.runtime:   stage8_review done in 4.81s
2026-05-03 08:01:54,807 INFO ehr_pipeline.pipeline:   applied revision: 'LENI ordered for today [E:note:row556185:30].' → ''
2026-05-03 08:01:54,809 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/summary_revised.md
2026-05-03 08:01:54,810 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:01:54,812 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/check_report_revised.json
2026-05-03 08:01:54,812 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 08:01:54,815 INFO ehr_pipeline.pipeline: Saved input note (10660 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/input_note.txt
2026-05-03 08:01:54,815 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-43937-146668-1263
2026-05-03 08:01:54,817 INFO ehr_pipeline.stages.s1_evidence:   wrote 103 evidence items (23 structured, 80 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/evidence_store.json
2026-05-03 08:01:54,817 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:01:54,817 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   260.30 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   190.88 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    52.11 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    64.10 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     4.81 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   572.21 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.32  (901 / 2794 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-53474-177016-556185/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-43937-146668-1263
  note_chars=10660  gold_concepts=18
==================================================================

2026-05-03 08:06:19,787 INFO ehr_pipeline.stages.s2_extract:   extracted 93 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/claims.json
2026-05-03 08:06:19,788 INFO ehr_pipeline.runtime:   stage2_extract done in 264.97s
2026-05-03 08:06:19,788 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 93 claims
2026-05-03 08:08:03,965 INFO ehr_pipeline.stages.s3_verify:   {'verified': 39, 'contradicted': 0, 'unsupported': 54} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/verifications.json
2026-05-03 08:08:03,966 INFO ehr_pipeline.runtime:   stage3_verify done in 104.18s
2026-05-03 08:08:03,966 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:08:03,968 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:08:03,969 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 34, 'medications': 22, 'labs': 2, 'vitals': 2, 'plan': 0}
2026-05-03 08:08:03,970 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:08:03,970 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:08:19,657 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/patient_summary.md (1833 chars, FK grade=8.30, in_band=False)
2026-05-03 08:08:19,658 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.69s
2026-05-03 08:08:19,659 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:08:42,388 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/summary.md (3106 chars, ratio=0.29, target=0.20-0.30, in_band=True)
2026-05-03 08:08:42,389 INFO ehr_pipeline.runtime:   stage6_summarize done in 22.73s
2026-05-03 08:08:42,390 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:08:42,394 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=31 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/check_report.json
2026-05-03 08:08:42,394 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:08:42,395 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:08:52,704 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/review.json
2026-05-03 08:08:52,705 INFO ehr_pipeline.runtime:   stage8_review done in 10.31s
2026-05-03 08:08:52,706 INFO ehr_pipeline.pipeline:   applied revision: 'Respiratory status is critical with acute respiratory failur' → 'Respiratory findings include acute respiratory failure [E:co'
2026-05-03 08:08:52,706 INFO ehr_pipeline.pipeline:   applied revision: 'Maintenance medications include:' → 'Maintenance medications include the following:'
2026-05-03 08:08:52,709 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/summary_revised.md
2026-05-03 08:08:52,710 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:08:52,712 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=31 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/check_report_revised.json
2026-05-03 08:08:52,712 INFO ehr_pipeline.pipeline:   revised summary check: passed=False violations=1
2026-05-03 08:08:52,716 INFO ehr_pipeline.pipeline: Saved input note (2432 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/input_note.txt
2026-05-03 08:08:52,717 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-70206-162850-600430
2026-05-03 08:08:52,718 INFO ehr_pipeline.stages.s1_evidence:   wrote 84 evidence items (67 structured, 17 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/evidence_store.json
2026-05-03 08:08:52,719 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:08:52,719 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   264.97 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   104.18 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.69 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    22.73 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    10.31 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   417.88 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.29  (3106 / 10660 chars)  [IN BAND ✓]
  S7 det. check : FAIL ✗
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43937-146668-1263/summary_revised.md  [check FAIL ✗]
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-70206-162850-600430
  note_chars=2432  gold_concepts=9
==================================================================

2026-05-03 08:11:46,372 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.3s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 7e42d2aa-ef82-409b-bb9c-4ce5f845c81b)
2026-05-03 08:14:32,060 INFO ehr_pipeline.stages.s2_extract:   extracted 50 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/claims.json
2026-05-03 08:14:32,061 INFO ehr_pipeline.runtime:   stage2_extract done in 339.34s
2026-05-03 08:14:32,062 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 50 claims
2026-05-03 08:19:46,840 INFO ehr_pipeline.stages.s3_verify:   {'verified': 34, 'contradicted': 0, 'unsupported': 16} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/verifications.json
2026-05-03 08:19:46,841 INFO ehr_pipeline.runtime:   stage3_verify done in 314.78s
2026-05-03 08:19:46,841 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:19:46,846 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:19:46,848 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 58, 'medications': 3, 'labs': 5, 'vitals': 0, 'plan': 0}
2026-05-03 08:19:46,848 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:19:46,849 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:20:45,008 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/patient_summary.md (1617 chars, FK grade=7.65, in_band=True)
2026-05-03 08:20:45,009 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 58.16s
2026-05-03 08:20:45,010 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:21:03,522 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/summary.md (964 chars, ratio=0.40, target=0.20-0.30, in_band=False)
2026-05-03 08:21:03,524 INFO ehr_pipeline.runtime:   stage6_summarize done in 18.51s
2026-05-03 08:21:03,526 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:21:03,530 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/check_report.json
2026-05-03 08:21:03,531 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:21:03,531 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:21:15,904 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/review.json
2026-05-03 08:21:15,904 INFO ehr_pipeline.runtime:   stage8_review done in 12.37s
2026-05-03 08:21:15,905 INFO ehr_pipeline.pipeline:   applied revision: 'Additional findings: stage III pressure ulcers (buttock, low' → 'Additional findings: stage III pressure ulcers (buttock, low'
2026-05-03 08:21:15,906 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/summary_revised.md
2026-05-03 08:21:15,907 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:21:15,909 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/check_report_revised.json
2026-05-03 08:21:15,910 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 08:21:15,915 INFO ehr_pipeline.pipeline: Saved input note (1272 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/input_note.txt
2026-05-03 08:21:15,916 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-70926-112660-521238
2026-05-03 08:21:15,918 INFO ehr_pipeline.stages.s1_evidence:   wrote 20 evidence items (17 structured, 3 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/evidence_store.json
2026-05-03 08:21:15,918 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:21:15,918 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   339.34 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   314.78 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    58.16 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    18.51 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.37 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   743.18 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.40  (964 / 2432 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70206-162850-600430/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-70926-112660-521238
  note_chars=1272  gold_concepts=3
==================================================================

2026-05-03 08:22:48,416 INFO ehr_pipeline.stages.s2_extract:   extracted 32 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/claims.json
2026-05-03 08:22:48,417 INFO ehr_pipeline.runtime:   stage2_extract done in 92.50s
2026-05-03 08:22:48,418 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 32 claims
2026-05-03 08:24:45,676 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 9843f914-12e5-4ce3-a04e-269a9a4de877)
2026-05-03 08:25:10,378 INFO ehr_pipeline.stages.s3_verify:   {'verified': 8, 'contradicted': 0, 'unsupported': 24} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/verifications.json
2026-05-03 08:25:10,379 INFO ehr_pipeline.runtime:   stage3_verify done in 141.96s
2026-05-03 08:25:10,379 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:25:10,382 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:25:10,384 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 23, 'medications': 1, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-03 08:25:10,385 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:25:10,385 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:25:22,960 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/patient_summary.md (1332 chars, FK grade=6.07, in_band=False)
2026-05-03 08:25:22,961 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 12.58s
2026-05-03 08:25:22,962 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:25:28,039 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/summary.md (542 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 08:25:28,040 INFO ehr_pipeline.runtime:   stage6_summarize done in 5.08s
2026-05-03 08:25:28,041 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:25:28,043 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/check_report.json
2026-05-03 08:25:28,044 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:25:28,045 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:25:50,920 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/review.json
2026-05-03 08:25:50,921 INFO ehr_pipeline.runtime:   stage8_review done in 22.88s
2026-05-03 08:25:50,922 INFO ehr_pipeline.pipeline:   applied revision: 'Sepsis, septicemia, and acute respiratory, kidney, and hepat' → 'Sepsis, septicemia, acute respiratory failure, acute kidney '
2026-05-03 08:25:50,922 INFO ehr_pipeline.pipeline:   applied revision: 'Cirrhosis, NASH, acidosis, pleural effusion, UTI, and blood ' → 'Cirrhosis, acidosis, pleural effusion, UTI, and blood in sto'
2026-05-03 08:25:50,922 INFO ehr_pipeline.pipeline:   applied revision: 'HTN, hypercholesterolemia, LBP, depression, anxiety, and dys' → 'Dysthymic disorder [E:cond:11].'
2026-05-03 08:25:50,924 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/summary_revised.md
2026-05-03 08:25:50,926 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:25:50,928 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/check_report_revised.json
2026-05-03 08:25:50,928 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 08:25:50,932 INFO ehr_pipeline.pipeline: Saved input note (2261 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/input_note.txt
2026-05-03 08:25:50,932 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-28126-161069-328226
2026-05-03 08:25:50,934 INFO ehr_pipeline.stages.s1_evidence:   wrote 51 evidence items (29 structured, 22 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/evidence_store.json
2026-05-03 08:25:50,934 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:25:50,934 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    92.50 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   141.96 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    12.58 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     5.08 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    22.88 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   275.00 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (542 / 1272 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-70926-112660-521238/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-28126-161069-328226
  note_chars=2261  gold_concepts=9
==================================================================

2026-05-03 08:31:45,693 INFO ehr_pipeline.stages.s2_extract:   extracted 34 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/claims.json
2026-05-03 08:31:45,694 INFO ehr_pipeline.runtime:   stage2_extract done in 354.76s
2026-05-03 08:31:45,695 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 34 claims
2026-05-03 08:33:36,797 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 09f78640-332d-4862-acef-a7b620e5551c)
2026-05-03 08:37:41,741 INFO ehr_pipeline.stages.s3_verify:   {'verified': 20, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/verifications.json
2026-05-03 08:37:41,741 INFO ehr_pipeline.runtime:   stage3_verify done in 356.05s
2026-05-03 08:37:41,742 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:37:41,744 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:37:41,746 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 36, 'medications': 1, 'labs': 0, 'vitals': 8, 'plan': 1}
2026-05-03 08:37:41,747 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:37:41,747 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:38:08,554 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/patient_summary.md (1819 chars, FK grade=6.27, in_band=False)
2026-05-03 08:38:08,555 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 26.81s
2026-05-03 08:38:08,556 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:38:53,423 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/summary.md (800 chars, ratio=0.35, target=0.20-0.30, in_band=False)
2026-05-03 08:38:53,425 INFO ehr_pipeline.runtime:   stage6_summarize done in 44.87s
2026-05-03 08:38:53,426 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:38:53,429 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/check_report.json
2026-05-03 08:38:53,430 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:38:53,431 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:38:57,359 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/review.json
2026-05-03 08:38:57,360 INFO ehr_pipeline.runtime:   stage8_review done in 3.93s
2026-05-03 08:38:57,360 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 08:38:57,366 INFO ehr_pipeline.pipeline: Saved input note (2394 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/input_note.txt
2026-05-03 08:38:57,367 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-28941-107962-328302
2026-05-03 08:38:57,369 INFO ehr_pipeline.stages.s1_evidence:   wrote 54 evidence items (53 structured, 1 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/evidence_store.json
2026-05-03 08:38:57,369 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:38:57,369 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   354.76 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   356.05 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    26.81 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    44.87 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     3.93 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   786.42 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.35  (800 / 2261 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28126-161069-328226/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-28941-107962-328302
  note_chars=2394  gold_concepts=7
==================================================================

2026-05-03 08:41:30,795 INFO ehr_pipeline.stages.s2_extract:   extracted 41 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/claims.json
2026-05-03 08:41:30,797 INFO ehr_pipeline.runtime:   stage2_extract done in 153.43s
2026-05-03 08:41:30,798 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 41 claims
2026-05-03 08:42:50,786 INFO ehr_pipeline.stages.s3_verify:   {'verified': 3, 'contradicted': 0, 'unsupported': 38} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/verifications.json
2026-05-03 08:42:50,787 INFO ehr_pipeline.runtime:   stage3_verify done in 79.99s
2026-05-03 08:42:50,787 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:42:50,789 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:42:50,792 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 53, 'medications': 0, 'labs': 0, 'vitals': 0, 'plan': 1}
2026-05-03 08:42:50,792 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:42:50,792 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:43:01,235 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/patient_summary.md (1464 chars, FK grade=8.02, in_band=False)
2026-05-03 08:43:01,236 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 10.44s
2026-05-03 08:43:01,237 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:43:09,663 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/summary.md (877 chars, ratio=0.37, target=0.20-0.30, in_band=False)
2026-05-03 08:43:09,667 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.43s
2026-05-03 08:43:09,670 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:43:09,671 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/check_report.json
2026-05-03 08:43:09,671 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:43:09,672 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:43:13,529 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/review.json
2026-05-03 08:43:13,531 INFO ehr_pipeline.runtime:   stage8_review done in 3.86s
2026-05-03 08:43:13,531 INFO ehr_pipeline.pipeline:   applied revision: 'Acute respiratory failure [E:cond:3][E:note:row328302:1].' → 'Acute respiratory failure [E:cond:3].'
2026-05-03 08:43:13,533 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/summary_revised.md
2026-05-03 08:43:13,534 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:43:13,537 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/check_report_revised.json
2026-05-03 08:43:13,537 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 08:43:13,541 INFO ehr_pipeline.pipeline: Saved input note (2510 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/input_note.txt
2026-05-03 08:43:13,541 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-60337-121846-509076
2026-05-03 08:43:13,543 INFO ehr_pipeline.stages.s1_evidence:   wrote 69 evidence items (42 structured, 27 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/evidence_store.json
2026-05-03 08:43:13,543 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:43:13,543 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   153.43 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    79.99 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    10.44 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.43 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     3.86 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   256.16 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.37  (877 / 2394 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-28941-107962-328302/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-60337-121846-509076
  note_chars=2510  gold_concepts=11
==================================================================

2026-05-03 08:45:09,263 INFO ehr_pipeline.stages.s2_extract:   extracted 33 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/claims.json
2026-05-03 08:45:09,264 INFO ehr_pipeline.runtime:   stage2_extract done in 115.72s
2026-05-03 08:45:09,265 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 33 claims
2026-05-03 08:49:18,986 INFO ehr_pipeline.stages.s3_verify:   {'verified': 19, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/verifications.json
2026-05-03 08:49:18,987 INFO ehr_pipeline.runtime:   stage3_verify done in 249.72s
2026-05-03 08:49:18,987 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:49:18,989 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:49:18,991 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 46, 'medications': 4, 'labs': 2, 'vitals': 2, 'plan': 0}
2026-05-03 08:49:18,991 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:49:18,992 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 08:51:47,388 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/patient_summary.md (1786 chars, FK grade=7.37, in_band=True)
2026-05-03 08:51:47,389 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 148.40s
2026-05-03 08:51:47,389 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 08:51:56,275 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/summary.md (1093 chars, ratio=0.44, target=0.20-0.30, in_band=False)
2026-05-03 08:51:56,276 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.89s
2026-05-03 08:51:56,277 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:51:56,279 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/check_report.json
2026-05-03 08:51:56,280 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 08:51:56,280 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 08:54:15,335 INFO ehr_pipeline.stages.s8_review:   concerns=5 recommended_revisions=5 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/review.json
2026-05-03 08:54:15,336 INFO ehr_pipeline.runtime:   stage8_review done in 139.06s
2026-05-03 08:54:15,336 INFO ehr_pipeline.pipeline:   applied revision: 'Multiple myeloma [E:cond:1][E:note:row509076:1], acute on ch' → 'Multiple myeloma [E:cond:1], acute on chronic diastolic hear'
2026-05-03 08:54:15,336 INFO ehr_pipeline.pipeline:   applied revision: 'Severe sepsis [E:cond:7] with unspecified septicemia [E:cond' → 'Severe sepsis [E:cond:7] with unspecified septicemia [E:cond'
2026-05-03 08:54:15,337 INFO ehr_pipeline.pipeline:   applied revision: 'Anoxic brain damage [E:cond:11], neutropenia [E:cond:21], an' → 'Anoxic brain damage [E:cond:11].'
2026-05-03 08:54:15,338 INFO ehr_pipeline.pipeline:   applied revision: 'Pleural effusion [E:cond:13], hyperlipidemia [E:cond:17], an' → 'Pleural effusion [E:cond:13].'
2026-05-03 08:54:15,338 INFO ehr_pipeline.pipeline:   applied revision: 'Hypertensive heart and kidney disease [E:cond:8], cardiomyop' → 'Hypertensive heart and kidney disease [E:cond:8], cardiomyop'
2026-05-03 08:54:15,340 INFO ehr_pipeline.pipeline: Wrote revised summary (5 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/summary_revised.md
2026-05-03 08:54:15,340 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 08:54:15,341 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/check_report_revised.json
2026-05-03 08:54:15,342 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 08:54:15,345 INFO ehr_pipeline.pipeline: Saved input note (2521 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/input_note.txt
2026-05-03 08:54:15,345 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-66714-150541-472627
2026-05-03 08:54:15,346 INFO ehr_pipeline.stages.s1_evidence:   wrote 79 evidence items (47 structured, 32 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/evidence_store.json
2026-05-03 08:54:15,347 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 08:54:15,347 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   115.72 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   249.72 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   148.40 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.89 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │   139.06 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   661.79 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.44  (1093 / 2510 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=5  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60337-121846-509076/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-66714-150541-472627
  note_chars=2521  gold_concepts=10
==================================================================

2026-05-03 08:56:38,848 INFO ehr_pipeline.stages.s2_extract:   extracted 55 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/claims.json
2026-05-03 08:56:38,849 INFO ehr_pipeline.runtime:   stage2_extract done in 143.50s
2026-05-03 08:56:38,850 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 55 claims
2026-05-03 08:59:06,974 INFO ehr_pipeline.stages.s3_verify:   {'verified': 41, 'contradicted': 1, 'unsupported': 13} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/verifications.json
2026-05-03 08:59:06,975 INFO ehr_pipeline.runtime:   stage3_verify done in 148.13s
2026-05-03 08:59:06,976 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 08:59:06,978 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 08:59:06,981 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 65, 'medications': 16, 'labs': 5, 'vitals': 0, 'plan': 1}
2026-05-03 08:59:06,981 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 08:59:06,981 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 09:02:10,066 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/patient_summary.md (1744 chars, FK grade=8.74, in_band=False)
2026-05-03 09:02:10,066 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 183.09s
2026-05-03 09:02:10,067 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 09:03:35,449 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/summary.md (1180 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 09:03:35,451 INFO ehr_pipeline.runtime:   stage6_summarize done in 85.38s
2026-05-03 09:03:35,453 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:03:35,457 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/check_report.json
2026-05-03 09:03:35,457 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 09:03:35,458 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 09:03:59,818 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/review.json
2026-05-03 09:03:59,819 INFO ehr_pipeline.runtime:   stage8_review done in 24.36s
2026-05-03 09:03:59,819 INFO ehr_pipeline.pipeline:   applied revision: 'CK elevated [E:note:row472627:3] then negative [E:note:row47' → 'CK elevated [E:note:row472627:3] then neg [E:note:row472627:'
2026-05-03 09:03:59,820 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/summary_revised.md
2026-05-03 09:03:59,821 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:03:59,823 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/check_report_revised.json
2026-05-03 09:03:59,824 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 09:03:59,827 INFO ehr_pipeline.pipeline: Saved input note (1109 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/input_note.txt
2026-05-03 09:03:59,828 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-67512-105739-511563
2026-05-03 09:03:59,829 INFO ehr_pipeline.stages.s1_evidence:   wrote 38 evidence items (19 structured, 19 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/evidence_store.json
2026-05-03 09:03:59,830 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 09:03:59,830 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   143.50 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   148.13 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   183.09 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    85.38 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    24.36 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   584.47 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (1180 / 2521 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-66714-150541-472627/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-67512-105739-511563
  note_chars=1109  gold_concepts=7
==================================================================

2026-05-03 09:05:31,387 INFO ehr_pipeline.stages.s2_extract:   extracted 33 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/claims.json
2026-05-03 09:05:31,389 INFO ehr_pipeline.runtime:   stage2_extract done in 91.56s
2026-05-03 09:05:31,389 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 33 claims
2026-05-03 09:10:43,405 INFO ehr_pipeline.stages.s3_verify:   {'verified': 31, 'contradicted': 0, 'unsupported': 2} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/verifications.json
2026-05-03 09:10:43,406 INFO ehr_pipeline.runtime:   stage3_verify done in 312.02s
2026-05-03 09:10:43,407 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 09:10:43,409 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 09:10:43,411 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 37, 'medications': 4, 'labs': 3, 'vitals': 5, 'plan': 0}
2026-05-03 09:10:43,411 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 09:10:43,412 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 09:11:00,270 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/patient_summary.md (1382 chars, FK grade=4.87, in_band=False)
2026-05-03 09:11:00,271 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 16.86s
2026-05-03 09:11:00,271 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 09:11:13,558 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/summary.md (755 chars, ratio=0.68, target=0.20-0.30, in_band=False)
2026-05-03 09:11:13,559 INFO ehr_pipeline.runtime:   stage6_summarize done in 13.29s
2026-05-03 09:11:13,561 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:11:13,564 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/check_report.json
2026-05-03 09:11:13,564 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 09:11:13,565 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 09:11:32,041 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/review.json
2026-05-03 09:11:32,041 INFO ehr_pipeline.runtime:   stage8_review done in 18.48s
2026-05-03 09:11:32,042 INFO ehr_pipeline.pipeline:   applied revision: 'ESRD [E:cond:4], acute RF [E:note:row511563:19], dCHF [E:not' → 'ESRD [E:cond:4], dCHF [E:cond:3], Hep C cirrhosis [E:cond:7,'
2026-05-03 09:11:32,043 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/summary_revised.md
2026-05-03 09:11:32,044 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:11:32,045 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=8 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/check_report_revised.json
2026-05-03 09:11:32,045 INFO ehr_pipeline.pipeline:   revised summary check: passed=False violations=1
2026-05-03 09:11:32,050 INFO ehr_pipeline.pipeline: Saved input note (2143 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/input_note.txt
2026-05-03 09:11:32,051 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-50004-131407-447958
2026-05-03 09:11:32,052 INFO ehr_pipeline.stages.s1_evidence:   wrote 46 evidence items (23 structured, 23 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/evidence_store.json
2026-05-03 09:11:32,052 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 09:11:32,053 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    91.56 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   312.02 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    16.86 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    13.29 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    18.48 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   452.21 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.68  (755 / 1109 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-67512-105739-511563/summary_revised.md  [check FAIL ✗]
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-50004-131407-447958
  note_chars=2143  gold_concepts=8
==================================================================

2026-05-03 09:13:05,484 INFO ehr_pipeline.stages.s2_extract:   extracted 36 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/claims.json
2026-05-03 09:13:05,485 INFO ehr_pipeline.runtime:   stage2_extract done in 93.43s
2026-05-03 09:13:05,485 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 36 claims
2026-05-03 09:14:24,591 INFO ehr_pipeline.stages.s3_verify:   {'verified': 23, 'contradicted': 1, 'unsupported': 12} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/verifications.json
2026-05-03 09:14:24,592 INFO ehr_pipeline.runtime:   stage3_verify done in 79.11s
2026-05-03 09:14:24,592 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 09:14:24,595 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 09:14:24,596 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 25, 'medications': 5, 'labs': 7, 'vitals': 8, 'plan': 0}
2026-05-03 09:14:24,597 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 09:14:24,597 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 09:14:42,203 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/patient_summary.md (1888 chars, FK grade=9.44, in_band=False)
2026-05-03 09:14:42,204 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.61s
2026-05-03 09:14:42,205 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 09:19:21,039 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/summary.md (1093 chars, ratio=0.51, target=0.20-0.30, in_band=False)
2026-05-03 09:19:21,041 INFO ehr_pipeline.runtime:   stage6_summarize done in 278.84s
2026-05-03 09:19:21,043 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:19:21,045 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/check_report.json
2026-05-03 09:19:21,046 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 09:19:21,047 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 09:19:38,625 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/review.json
2026-05-03 09:19:38,626 INFO ehr_pipeline.runtime:   stage8_review done in 17.58s
2026-05-03 09:19:38,627 INFO ehr_pipeline.pipeline:   applied revision: 'Other issues: SIRS with organ dysfunction [E:cond:2], malign' → 'Other issues: SIRS with organ dysfunction [E:cond:2], malign'
2026-05-03 09:19:38,627 INFO ehr_pipeline.pipeline:   applied revision: 'Procedures include hemodialysis [E:proc:4] and mechanical ve' → ''
2026-05-03 09:19:38,629 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/summary_revised.md
2026-05-03 09:19:38,630 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:19:38,633 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/check_report_revised.json
2026-05-03 09:19:38,633 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 09:19:38,636 INFO ehr_pipeline.pipeline: Saved input note (2628 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/input_note.txt
2026-05-03 09:19:38,637 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-47974-163366-626355
2026-05-03 09:19:38,638 INFO ehr_pipeline.stages.s1_evidence:   wrote 73 evidence items (27 structured, 46 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/evidence_store.json
2026-05-03 09:19:38,638 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 09:19:38,639 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    93.43 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    79.11 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.61 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   278.84 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    17.58 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   486.57 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.51  (1093 / 2143 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-50004-131407-447958/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-47974-163366-626355
  note_chars=2628  gold_concepts=6
==================================================================

2026-05-03 09:29:38,676 WARNING ehr_pipeline.ollama_client: LLM JSON attempt 1/4 failed, appending error feedback and retrying: The read operation timed out
2026-05-03 09:32:10,172 INFO ehr_pipeline.stages.s2_extract:   extracted 50 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/claims.json
2026-05-03 09:32:10,172 INFO ehr_pipeline.runtime:   stage2_extract done in 751.53s
2026-05-03 09:32:10,173 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 50 claims
2026-05-03 09:39:57,320 INFO ehr_pipeline.stages.s3_verify:   {'verified': 39, 'contradicted': 1, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/verifications.json
2026-05-03 09:39:57,321 INFO ehr_pipeline.runtime:   stage3_verify done in 467.15s
2026-05-03 09:39:57,321 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 09:39:57,324 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 09:39:57,326 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 44, 'medications': 11, 'labs': 2, 'vitals': 2, 'plan': 5}
2026-05-03 09:39:57,326 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 09:39:57,326 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 09:41:10,540 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/patient_summary.md (2119 chars, FK grade=6.71, in_band=False)
2026-05-03 09:41:10,541 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 73.21s
2026-05-03 09:41:10,541 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 09:41:30,098 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/summary.md (1463 chars, ratio=0.56, target=0.20-0.30, in_band=False)
2026-05-03 09:41:30,099 INFO ehr_pipeline.runtime:   stage6_summarize done in 19.56s
2026-05-03 09:41:30,100 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:41:30,103 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=15 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/check_report.json
2026-05-03 09:41:30,104 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 09:41:30,105 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 09:41:43,518 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/review.json
2026-05-03 09:41:43,520 INFO ehr_pipeline.runtime:   stage8_review done in 13.42s
2026-05-03 09:41:43,520 INFO ehr_pipeline.pipeline:   applied revision: 'Other: Demerol 25mg [E:note:row626355:10], Ativan 0.5mg [E:n' → 'Other: Demerol 25mg [E:note:row626355:10], Ativan .5mg [E:no'
2026-05-03 09:41:43,521 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with severe sepsis, septic shock, and unspe' → 'Patient presents with severe sepsis, septic shock, and unspe'
2026-05-03 09:41:43,523 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/summary_revised.md
2026-05-03 09:41:43,525 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:41:43,527 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=15 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/check_report_revised.json
2026-05-03 09:41:43,528 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 09:41:43,530 INFO ehr_pipeline.pipeline: Saved input note (1993 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/input_note.txt
2026-05-03 09:41:43,531 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-60316-171649-545713
2026-05-03 09:41:43,532 INFO ehr_pipeline.stages.s1_evidence:   wrote 66 evidence items (24 structured, 42 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/evidence_store.json
2026-05-03 09:41:43,533 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 09:41:43,533 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   751.53 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   467.15 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    73.21 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    19.56 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    13.42 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1324.88 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.56  (1463 / 2628 chars)  [OUT OF BAND ✗]
  S7 det. check : FAIL ✗
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47974-163366-626355/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-60316-171649-545713
  note_chars=1993  gold_concepts=9
==================================================================

2026-05-03 09:42:50,690 INFO ehr_pipeline.stages.s2_extract:   extracted 29 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/claims.json
2026-05-03 09:42:50,692 INFO ehr_pipeline.runtime:   stage2_extract done in 67.16s
2026-05-03 09:42:50,693 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 29 claims
2026-05-03 09:46:22,369 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.2s: [HTTP 500] Ollama API failed: Internal Server Error (ref: 6739be9e-18aa-459b-a798-bc9cd12f16eb)
2026-05-03 09:46:22,371 WARNING ehr_pipeline.ollama_client: LLM request failed (attempt 1/4), retrying in 1.4s: [HTTP 500] Ollama API failed: Internal Server Error (ref: df236f45-02e4-472f-9c05-932f8f8a8d4c)
2026-05-03 09:46:29,602 INFO ehr_pipeline.stages.s3_verify:   {'verified': 27, 'contradicted': 0, 'unsupported': 2} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/verifications.json
2026-05-03 09:46:29,603 INFO ehr_pipeline.runtime:   stage3_verify done in 218.91s
2026-05-03 09:46:29,604 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 09:46:29,606 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 09:46:29,607 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 39, 'medications': 3, 'labs': 1, 'vitals': 4, 'plan': 1}
2026-05-03 09:46:29,608 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 09:46:29,608 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 09:46:41,294 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/patient_summary.md (1455 chars, FK grade=5.11, in_band=False)
2026-05-03 09:46:41,295 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 11.69s
2026-05-03 09:46:41,296 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 09:46:51,124 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/summary.md (848 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 09:46:51,125 INFO ehr_pipeline.runtime:   stage6_summarize done in 9.83s
2026-05-03 09:46:51,126 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:46:51,128 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=15 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/check_report.json
2026-05-03 09:46:51,128 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 09:46:51,129 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 09:47:03,004 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/review.json
2026-05-03 09:47:03,005 INFO ehr_pipeline.runtime:   stage8_review done in 11.88s
2026-05-03 09:47:03,005 INFO ehr_pipeline.pipeline:   applied revision: 'Malignant hepatic flexure mass with obstruction/bleeding [E:' → 'Malignant neoplasm of hepatic flexure [E:cond:1].'
2026-05-03 09:47:03,006 INFO ehr_pipeline.pipeline:   applied revision: 'Failed extubation [E:note:row545713:8][E:note:row545713:24].' → ''
2026-05-03 09:47:03,008 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/summary_revised.md
2026-05-03 09:47:03,009 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:47:03,010 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=14 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/check_report_revised.json
2026-05-03 09:47:03,011 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 09:47:03,014 INFO ehr_pipeline.pipeline: Saved input note (3966 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/input_note.txt
2026-05-03 09:47:03,015 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-76514-125586-629067
2026-05-03 09:47:03,017 INFO ehr_pipeline.stages.s1_evidence:   wrote 86 evidence items (30 structured, 56 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/evidence_store.json
2026-05-03 09:47:03,017 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 09:47:03,017 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    67.16 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   218.91 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    11.69 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     9.83 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    11.88 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   319.47 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (848 / 1993 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60316-171649-545713/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-76514-125586-629067
  note_chars=3966  gold_concepts=12
==================================================================

2026-05-03 09:49:28,313 INFO ehr_pipeline.stages.s2_extract:   extracted 50 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/claims.json
2026-05-03 09:49:28,313 INFO ehr_pipeline.runtime:   stage2_extract done in 145.30s
2026-05-03 09:49:28,314 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 50 claims
2026-05-03 09:55:52,200 INFO ehr_pipeline.stages.s3_verify:   {'verified': 39, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/verifications.json
2026-05-03 09:55:52,201 INFO ehr_pipeline.runtime:   stage3_verify done in 383.89s
2026-05-03 09:55:52,201 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 09:55:52,203 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 09:55:52,206 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 44, 'medications': 8, 'labs': 1, 'vitals': 13, 'plan': 1}
2026-05-03 09:55:52,206 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 09:55:52,207 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 09:56:08,187 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/patient_summary.md (1847 chars, FK grade=7.24, in_band=True)
2026-05-03 09:56:08,188 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.98s
2026-05-03 09:56:08,188 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 09:56:22,728 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/summary.md (1395 chars, ratio=0.35, target=0.20-0.30, in_band=False)
2026-05-03 09:56:22,730 INFO ehr_pipeline.runtime:   stage6_summarize done in 14.54s
2026-05-03 09:56:22,732 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:56:22,735 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/check_report.json
2026-05-03 09:56:22,735 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 09:56:22,735 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 09:56:30,202 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/review.json
2026-05-03 09:56:30,202 INFO ehr_pipeline.runtime:   stage8_review done in 7.47s
2026-05-03 09:56:30,203 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with acute respiratory failure [E:cond:2], ' → 'Patient presents with acute respiratory failure [E:cond:2], '
2026-05-03 09:56:30,205 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/summary_revised.md
2026-05-03 09:56:30,205 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 09:56:30,208 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/check_report_revised.json
2026-05-03 09:56:30,209 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 09:56:30,212 INFO ehr_pipeline.pipeline: Saved input note (1810 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/input_note.txt
2026-05-03 09:56:30,213 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-49068-105351-489371
2026-05-03 09:56:30,215 INFO ehr_pipeline.stages.s1_evidence:   wrote 53 evidence items (38 structured, 15 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/evidence_store.json
2026-05-03 09:56:30,215 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 09:56:30,215 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   145.30 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   383.89 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.98 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    14.54 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     7.47 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   567.18 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.35  (1395 / 3966 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76514-125586-629067/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-49068-105351-489371
  note_chars=1810  gold_concepts=5
==================================================================

2026-05-03 09:59:24,901 INFO ehr_pipeline.stages.s2_extract:   extracted 27 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/claims.json
2026-05-03 09:59:24,902 INFO ehr_pipeline.runtime:   stage2_extract done in 174.69s
2026-05-03 09:59:24,903 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 27 claims
2026-05-03 10:01:21,124 INFO ehr_pipeline.stages.s3_verify:   {'verified': 19, 'contradicted': 0, 'unsupported': 8} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/verifications.json
2026-05-03 10:01:21,125 INFO ehr_pipeline.runtime:   stage3_verify done in 116.22s
2026-05-03 10:01:21,125 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 10:01:21,127 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 10:01:21,129 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 46, 'medications': 3, 'labs': 3, 'vitals': 2, 'plan': 1}
2026-05-03 10:01:21,130 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 10:01:21,130 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 10:01:42,015 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/patient_summary.md (1933 chars, FK grade=6.45, in_band=False)
2026-05-03 10:01:42,016 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 20.89s
2026-05-03 10:01:42,017 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 10:01:54,301 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/summary.md (828 chars, ratio=0.46, target=0.20-0.30, in_band=False)
2026-05-03 10:01:54,302 INFO ehr_pipeline.runtime:   stage6_summarize done in 12.28s
2026-05-03 10:01:54,303 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:01:54,305 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/check_report.json
2026-05-03 10:01:54,307 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 10:01:54,308 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 10:02:46,935 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/review.json
2026-05-03 10:02:46,936 INFO ehr_pipeline.runtime:   stage8_review done in 52.63s
2026-05-03 10:02:46,936 INFO ehr_pipeline.pipeline:   applied revision: 'Acute renal failure [E:cond:3][E:note:row489371:10], spontan' → 'Acute renal failure [E:cond:3] and GI hemorrhage [E:cond:7].'
2026-05-03 10:02:46,937 INFO ehr_pipeline.pipeline:   applied revision: 'DM [E:note:row489371:1][E:note:row489371:4], Afib [E:cond:20' → ''
2026-05-03 10:02:46,939 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/summary_revised.md
2026-05-03 10:02:46,940 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:02:46,942 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/check_report_revised.json
2026-05-03 10:02:46,942 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 10:02:46,945 INFO ehr_pipeline.pipeline: Saved input note (2031 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/input_note.txt
2026-05-03 10:02:46,946 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-68589-152895-642741
2026-05-03 10:02:46,947 INFO ehr_pipeline.stages.s1_evidence:   wrote 65 evidence items (45 structured, 20 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/evidence_store.json
2026-05-03 10:02:46,947 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 10:02:46,948 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   174.69 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   116.22 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    20.89 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    12.28 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    52.63 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   376.72 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.46  (828 / 1810 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=2  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49068-105351-489371/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-68589-152895-642741
  note_chars=2031  gold_concepts=12
==================================================================

2026-05-03 10:06:03,344 INFO ehr_pipeline.stages.s2_extract:   extracted 39 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/claims.json
2026-05-03 10:06:03,345 INFO ehr_pipeline.runtime:   stage2_extract done in 196.40s
2026-05-03 10:06:03,346 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 39 claims
2026-05-03 10:10:09,740 INFO ehr_pipeline.stages.s3_verify:   {'verified': 18, 'contradicted': 0, 'unsupported': 21} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/verifications.json
2026-05-03 10:10:09,741 INFO ehr_pipeline.runtime:   stage3_verify done in 246.40s
2026-05-03 10:10:09,741 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 10:10:09,744 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 10:10:09,746 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 34, 'medications': 1, 'labs': 0, 'vitals': 2, 'plan': 2}
2026-05-03 10:10:09,746 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 10:10:09,746 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 10:11:20,885 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/patient_summary.md (1693 chars, FK grade=9.11, in_band=False)
2026-05-03 10:11:20,886 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 71.14s
2026-05-03 10:11:20,886 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 10:11:31,087 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/summary.md (912 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 10:11:31,088 INFO ehr_pipeline.runtime:   stage6_summarize done in 10.20s
2026-05-03 10:11:31,090 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:11:31,093 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/check_report.json
2026-05-03 10:11:31,093 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 10:11:31,094 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 10:11:43,217 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/review.json
2026-05-03 10:11:43,218 INFO ehr_pipeline.runtime:   stage8_review done in 12.12s
2026-05-03 10:11:43,218 INFO ehr_pipeline.pipeline:   applied revision: 'Subdural hemorrhage and other intracranial hemorrhage follow' → 'Subdural hemorrhage and other intracranial hemorrhage follow'
2026-05-03 10:11:43,219 INFO ehr_pipeline.pipeline:   applied revision: 'Symptoms include 3d HA, dizziness, n/v, and 3 witnessed LOC ' → 'Symptoms include 3d HA, dizziness, and n/v [E:note:row642741'
2026-05-03 10:11:43,221 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/summary_revised.md
2026-05-03 10:11:43,222 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:11:43,224 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/check_report_revised.json
2026-05-03 10:11:43,225 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 10:11:43,229 INFO ehr_pipeline.pipeline: Saved input note (1889 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/input_note.txt
2026-05-03 10:11:43,229 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-91913-121738-523651
2026-05-03 10:11:43,231 INFO ehr_pipeline.stages.s1_evidence:   wrote 53 evidence items (32 structured, 21 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/evidence_store.json
2026-05-03 10:11:43,231 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 10:11:43,231 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   196.40 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   246.40 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    71.14 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    10.20 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.12 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   536.26 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (912 / 2031 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68589-152895-642741/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-91913-121738-523651
  note_chars=1889  gold_concepts=12
==================================================================

2026-05-03 10:13:50,182 INFO ehr_pipeline.stages.s2_extract:   extracted 51 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/claims.json
2026-05-03 10:13:50,183 INFO ehr_pipeline.runtime:   stage2_extract done in 126.95s
2026-05-03 10:13:50,183 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 51 claims
2026-05-03 10:21:54,180 INFO ehr_pipeline.stages.s3_verify:   {'verified': 36, 'contradicted': 1, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/verifications.json
2026-05-03 10:21:54,181 INFO ehr_pipeline.runtime:   stage3_verify done in 484.00s
2026-05-03 10:21:54,181 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 10:21:54,185 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 10:21:54,186 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 52, 'medications': 7, 'labs': 3, 'vitals': 0, 'plan': 4}
2026-05-03 10:21:54,187 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 10:21:54,187 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 10:23:45,231 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/patient_summary.md (1825 chars, FK grade=6.74, in_band=False)
2026-05-03 10:23:45,232 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 111.05s
2026-05-03 10:23:45,233 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 10:29:12,220 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/summary.md (1182 chars, ratio=0.63, target=0.20-0.30, in_band=False)
2026-05-03 10:29:12,221 INFO ehr_pipeline.runtime:   stage6_summarize done in 326.99s
2026-05-03 10:29:12,223 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:29:12,226 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/check_report.json
2026-05-03 10:29:12,227 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 10:29:12,228 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 10:29:19,392 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/review.json
2026-05-03 10:29:19,393 INFO ehr_pipeline.runtime:   stage8_review done in 7.16s
2026-05-03 10:29:19,393 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 10:29:19,402 INFO ehr_pipeline.pipeline: Saved input note (3215 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/input_note.txt
2026-05-03 10:29:19,403 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-88078-105497-729882
2026-05-03 10:29:19,405 INFO ehr_pipeline.stages.s1_evidence:   wrote 86 evidence items (59 structured, 27 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/evidence_store.json
2026-05-03 10:29:19,405 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 10:29:19,405 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   126.95 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   484.00 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   111.05 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   326.99 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     7.16 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1056.16 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.63  (1182 / 1889 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-91913-121738-523651/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-88078-105497-729882
  note_chars=3215  gold_concepts=12
==================================================================

2026-05-03 10:39:19,442 WARNING ehr_pipeline.ollama_client: LLM JSON attempt 1/4 failed, appending error feedback and retrying: The read operation timed out
2026-05-03 10:43:37,076 INFO ehr_pipeline.stages.s2_extract:   extracted 25 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/claims.json
2026-05-03 10:43:37,077 INFO ehr_pipeline.runtime:   stage2_extract done in 857.67s
2026-05-03 10:43:37,078 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 25 claims
2026-05-03 10:45:08,008 INFO ehr_pipeline.stages.s3_verify:   {'verified': 14, 'contradicted': 1, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/verifications.json
2026-05-03 10:45:08,008 INFO ehr_pipeline.runtime:   stage3_verify done in 90.93s
2026-05-03 10:45:08,009 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 10:45:08,014 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 10:45:08,016 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 35, 'medications': 6, 'labs': 0, 'vitals': 1, 'plan': 0}
2026-05-03 10:45:08,016 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 10:45:08,017 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 10:45:25,446 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/patient_summary.md (1526 chars, FK grade=6.47, in_band=False)
2026-05-03 10:45:25,447 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.43s
2026-05-03 10:45:25,447 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 10:47:22,768 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/summary.md (1489 chars, ratio=0.46, target=0.20-0.30, in_band=False)
2026-05-03 10:47:22,769 INFO ehr_pipeline.runtime:   stage6_summarize done in 117.32s
2026-05-03 10:47:22,771 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:47:22,773 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/check_report.json
2026-05-03 10:47:22,774 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 10:47:22,775 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 10:49:00,148 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/review.json
2026-05-03 10:49:00,149 INFO ehr_pipeline.runtime:   stage8_review done in 97.37s
2026-05-03 10:49:00,151 INFO ehr_pipeline.pipeline:   applied revision: 'Patient status post unwitnessed fall onto concrete [E:note:r' → 'Patient status post fall [E:note:row729882:1] resulting in t'
2026-05-03 10:49:00,154 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/summary_revised.md
2026-05-03 10:49:00,154 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 10:49:00,156 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/check_report_revised.json
2026-05-03 10:49:00,156 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 10:49:00,160 INFO ehr_pipeline.pipeline: Saved input note (2633 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/input_note.txt
2026-05-03 10:49:00,161 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-52296-112991-422448
2026-05-03 10:49:00,164 INFO ehr_pipeline.stages.s1_evidence:   wrote 125 evidence items (89 structured, 36 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/evidence_store.json
2026-05-03 10:49:00,164 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 10:49:00,165 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   857.67 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    90.93 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.43 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   117.32 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    97.37 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1180.74 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.46  (1489 / 3215 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-729882/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-52296-112991-422448
  note_chars=2633  gold_concepts=6
==================================================================

2026-05-03 10:55:09,063 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/claims.json
2026-05-03 10:55:09,065 INFO ehr_pipeline.runtime:   stage2_extract done in 368.90s
2026-05-03 10:55:09,066 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 11:12:16,702 INFO ehr_pipeline.stages.s3_verify:   {'verified': 28, 'contradicted': 0, 'unsupported': 9} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/verifications.json
2026-05-03 11:12:16,704 INFO ehr_pipeline.runtime:   stage3_verify done in 1027.64s
2026-05-03 11:12:16,704 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 11:12:16,706 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 11:12:16,709 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 50, 'medications': 6, 'labs': 1, 'vitals': 10, 'plan': 1}
2026-05-03 11:12:16,709 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 11:12:16,709 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 11:12:59,193 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/patient_summary.md (2037 chars, FK grade=6.74, in_band=False)
2026-05-03 11:12:59,194 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 42.48s
2026-05-03 11:12:59,194 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 11:14:52,991 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/summary.md (1098 chars, ratio=0.42, target=0.20-0.30, in_band=False)
2026-05-03 11:14:52,993 INFO ehr_pipeline.runtime:   stage6_summarize done in 113.80s
2026-05-03 11:14:52,995 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 11:14:52,999 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/check_report.json
2026-05-03 11:14:53,000 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 11:14:53,000 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 11:16:07,225 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/review.json
2026-05-03 11:16:07,226 INFO ehr_pipeline.runtime:   stage8_review done in 74.23s
2026-05-03 11:16:07,226 INFO ehr_pipeline.pipeline:   applied revision: 'Hypoxemia [E:note:row422448:17] and left arm swelling [E:not' → 'SpO2 maintained in high 90s on 50% O2 [E:note:row422448:17] '
2026-05-03 11:16:07,227 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/summary_revised.md
2026-05-03 11:16:07,228 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 11:16:07,232 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/check_report_revised.json
2026-05-03 11:16:07,232 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 11:16:07,237 INFO ehr_pipeline.pipeline: Saved input note (6615 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/input_note.txt
2026-05-03 11:16:07,237 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-17997-186252-1197
2026-05-03 11:16:07,240 INFO ehr_pipeline.stages.s1_evidence:   wrote 111 evidence items (11 structured, 100 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/evidence_store.json
2026-05-03 11:16:07,240 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 11:16:07,241 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   368.90 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │  1027.64 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    42.48 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   113.80 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    74.23 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1627.06 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.42  (1098 / 2633 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422448/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-17997-186252-1197
  note_chars=6615  gold_concepts=11
==================================================================

2026-05-03 11:23:14,984 INFO ehr_pipeline.stages.s2_extract:   extracted 84 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/claims.json
2026-05-03 11:23:14,987 INFO ehr_pipeline.runtime:   stage2_extract done in 427.75s
2026-05-03 11:23:14,988 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 84 claims
2026-05-03 11:30:23,081 INFO ehr_pipeline.stages.s3_verify:   {'verified': 65, 'contradicted': 0, 'unsupported': 19} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/verifications.json
2026-05-03 11:30:23,082 INFO ehr_pipeline.runtime:   stage3_verify done in 428.09s
2026-05-03 11:30:23,083 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 11:30:23,085 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 11:30:23,087 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 30, 'medications': 30, 'labs': 6, 'vitals': 2, 'plan': 0}
2026-05-03 11:30:23,087 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 11:30:23,088 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 11:35:10,103 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/patient_summary.md (2203 chars, FK grade=10.38, in_band=False)
2026-05-03 11:35:10,104 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 287.02s
2026-05-03 11:35:10,105 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 11:37:13,519 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/summary.md (2627 chars, ratio=0.40, target=0.20-0.30, in_band=False)
2026-05-03 11:37:13,519 INFO ehr_pipeline.runtime:   stage6_summarize done in 123.41s
2026-05-03 11:37:13,522 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 11:37:13,524 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=22 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/check_report.json
2026-05-03 11:37:13,525 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 11:37:13,525 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 11:37:24,243 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/review.json
2026-05-03 11:37:24,243 INFO ehr_pipeline.runtime:   stage8_review done in 10.72s
2026-05-03 11:37:24,244 INFO ehr_pipeline.pipeline:   applied revision: 'Current issues include a urinary tract infection with Klebsi' → 'Current issues include a urinary tract infection [E:cond:5]['
2026-05-03 11:37:24,246 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/summary_revised.md
2026-05-03 11:37:24,246 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 11:37:24,248 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=22 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/check_report_revised.json
2026-05-03 11:37:24,249 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 11:37:24,253 INFO ehr_pipeline.pipeline: Saved input note (2702 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/input_note.txt
2026-05-03 11:37:24,253 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-74701-182133-728280
2026-05-03 11:37:24,255 INFO ehr_pipeline.stages.s1_evidence:   wrote 69 evidence items (53 structured, 16 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/evidence_store.json
2026-05-03 11:37:24,255 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 11:37:24,255 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   427.75 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   428.09 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   287.02 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   123.41 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    10.72 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1277.00 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.40  (2627 / 6615 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-17997-186252-1197/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-74701-182133-728280
  note_chars=2702  gold_concepts=5
==================================================================

2026-05-03 11:47:24,295 WARNING ehr_pipeline.ollama_client: LLM JSON attempt 1/4 failed, appending error feedback and retrying: The read operation timed out
2026-05-03 11:50:15,726 INFO ehr_pipeline.stages.s2_extract:   extracted 58 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/claims.json
2026-05-03 11:50:15,754 INFO ehr_pipeline.runtime:   stage2_extract done in 771.50s
2026-05-03 11:50:15,760 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 58 claims
2026-05-03 11:52:45,755 INFO ehr_pipeline.stages.s3_verify:   {'verified': 25, 'contradicted': 0, 'unsupported': 33} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/verifications.json
2026-05-03 11:52:45,758 INFO ehr_pipeline.runtime:   stage3_verify done in 150.00s
2026-05-03 11:52:45,759 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 11:52:45,762 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 11:52:45,765 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 61, 'medications': 4, 'labs': 2, 'vitals': 4, 'plan': 0}
2026-05-03 11:52:45,765 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 11:52:45,766 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 11:53:14,015 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/patient_summary.md (1447 chars, FK grade=6.25, in_band=False)
2026-05-03 11:53:14,016 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 28.25s
2026-05-03 11:53:14,017 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 11:54:05,982 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/summary.md (1002 chars, ratio=0.37, target=0.20-0.30, in_band=False)
2026-05-03 11:54:05,983 INFO ehr_pipeline.runtime:   stage6_summarize done in 51.97s
2026-05-03 11:54:05,989 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 11:54:05,991 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/check_report.json
2026-05-03 11:54:05,992 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 11:54:05,993 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 11:54:33,930 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/review.json
2026-05-03 11:54:33,934 INFO ehr_pipeline.runtime:   stage8_review done in 27.94s
2026-05-03 11:54:33,934 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with septic shock [E:cond:10], severe sepsi' → 'Patient presents with septic shock [E:cond:10], severe sepsi'
2026-05-03 11:54:33,936 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/summary_revised.md
2026-05-03 11:54:33,936 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 11:54:33,938 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/check_report_revised.json
2026-05-03 11:54:33,939 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 11:54:33,953 INFO ehr_pipeline.pipeline: Saved input note (2626 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/input_note.txt
2026-05-03 11:54:33,954 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-77013-141363-443428
2026-05-03 11:54:33,960 INFO ehr_pipeline.stages.s1_evidence:   wrote 106 evidence items (73 structured, 33 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/evidence_store.json
2026-05-03 11:54:33,961 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 11:54:33,962 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   771.50 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   150.00 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    28.25 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    51.97 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    27.94 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1029.66 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.37  (1002 / 2702 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-74701-182133-728280/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-77013-141363-443428
  note_chars=2626  gold_concepts=7
==================================================================

2026-05-03 12:02:53,916 INFO ehr_pipeline.stages.s2_extract:   extracted 45 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/claims.json
2026-05-03 12:02:53,919 INFO ehr_pipeline.runtime:   stage2_extract done in 499.96s
2026-05-03 12:02:53,920 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 45 claims
2026-05-03 12:15:03,526 INFO ehr_pipeline.stages.s3_verify:   {'verified': 32, 'contradicted': 0, 'unsupported': 13} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/verifications.json
2026-05-03 12:15:03,530 INFO ehr_pipeline.runtime:   stage3_verify done in 729.61s
2026-05-03 12:15:03,530 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 12:15:03,533 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 12:15:03,536 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 52, 'medications': 5, 'labs': 3, 'vitals': 3, 'plan': 3}
2026-05-03 12:15:03,536 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 12:15:03,537 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 12:15:35,260 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/patient_summary.md (1739 chars, FK grade=8.98, in_band=False)
2026-05-03 12:15:35,262 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 31.73s
2026-05-03 12:15:35,262 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 12:17:30,716 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/summary.md (1294 chars, ratio=0.49, target=0.20-0.30, in_band=False)
2026-05-03 12:17:30,721 INFO ehr_pipeline.runtime:   stage6_summarize done in 115.46s
2026-05-03 12:17:30,723 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:17:30,728 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/check_report.json
2026-05-03 12:17:30,729 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 12:17:30,730 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 12:21:44,313 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/review.json
2026-05-03 12:21:44,315 INFO ehr_pipeline.runtime:   stage8_review done in 253.59s
2026-05-03 12:21:44,315 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with acute respiratory failure [E:cond:3][E' → 'Patient presents with acute respiratory failure [E:cond:3][E'
2026-05-03 12:21:44,316 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/summary_revised.md
2026-05-03 12:21:44,317 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:21:44,318 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/check_report_revised.json
2026-05-03 12:21:44,318 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 12:21:44,326 INFO ehr_pipeline.pipeline: Saved input note (16139 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/input_note.txt
2026-05-03 12:21:44,327 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-92277-173474-1282
2026-05-03 12:21:44,333 INFO ehr_pipeline.stages.s1_evidence:   wrote 159 evidence items (24 structured, 135 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/evidence_store.json
2026-05-03 12:21:44,333 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 12:21:44,333 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   499.96 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   729.61 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    31.73 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   115.46 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │   253.59 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1630.35 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.49  (1294 / 2626 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-77013-141363-443428/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-92277-173474-1282
  note_chars=16139  gold_concepts=20
==================================================================

2026-05-03 12:25:24,749 INFO ehr_pipeline.stages.s2_extract:   extracted 87 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/claims.json
2026-05-03 12:25:24,752 INFO ehr_pipeline.runtime:   stage2_extract done in 220.42s
2026-05-03 12:25:24,753 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 87 claims
2026-05-03 12:35:40,832 INFO ehr_pipeline.stages.s3_verify:   {'verified': 39, 'contradicted': 1, 'unsupported': 47} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/verifications.json
2026-05-03 12:35:40,836 INFO ehr_pipeline.runtime:   stage3_verify done in 616.08s
2026-05-03 12:35:40,837 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 12:35:40,840 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 12:35:40,843 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 41, 'medications': 12, 'labs': 1, 'vitals': 6, 'plan': 0}
2026-05-03 12:35:40,844 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 12:35:40,844 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 12:36:36,030 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/patient_summary.md (1633 chars, FK grade=7.49, in_band=True)
2026-05-03 12:36:36,034 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 55.19s
2026-05-03 12:36:36,035 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 12:37:01,348 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/summary.md (3355 chars, ratio=0.21, target=0.20-0.30, in_band=True)
2026-05-03 12:37:01,349 INFO ehr_pipeline.runtime:   stage6_summarize done in 25.31s
2026-05-03 12:37:01,351 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:37:01,357 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=25 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/check_report.json
2026-05-03 12:37:01,358 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 12:37:01,359 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 12:37:08,172 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/review.json
2026-05-03 12:37:08,174 INFO ehr_pipeline.runtime:   stage8_review done in 6.82s
2026-05-03 12:37:08,174 INFO ehr_pipeline.pipeline:   applied revision: 'There is a documented other specified procedure as the cause' → 'The patient experienced a complication following a specified'
2026-05-03 12:37:08,176 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/summary_revised.md
2026-05-03 12:37:08,177 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:37:08,181 INFO ehr_pipeline.stages.s7_check:   passed=False sentences=25 violations=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/check_report_revised.json
2026-05-03 12:37:08,181 INFO ehr_pipeline.pipeline:   revised summary check: passed=False violations=1
2026-05-03 12:37:08,197 INFO ehr_pipeline.pipeline: Saved input note (1157 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/input_note.txt
2026-05-03 12:37:08,198 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-46320-113335-462346
2026-05-03 12:37:08,203 INFO ehr_pipeline.stages.s1_evidence:   wrote 303 evidence items (301 structured, 2 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/evidence_store.json
2026-05-03 12:37:08,204 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 12:37:08,204 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   220.42 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   616.08 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    55.19 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    25.31 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     6.82 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   923.84 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.21  (3355 / 16139 chars)  [IN BAND ✓]
  S7 det. check : FAIL ✗
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-92277-173474-1282/summary_revised.md  [check FAIL ✗]
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-46320-113335-462346
  note_chars=1157  gold_concepts=5
==================================================================

2026-05-03 12:39:19,711 INFO ehr_pipeline.stages.s2_extract:   extracted 50 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/claims.json
2026-05-03 12:39:19,713 INFO ehr_pipeline.runtime:   stage2_extract done in 131.51s
2026-05-03 12:39:19,714 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 50 claims
2026-05-03 12:45:26,949 INFO ehr_pipeline.stages.s3_verify:   {'verified': 13, 'contradicted': 0, 'unsupported': 37} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/verifications.json
2026-05-03 12:45:26,951 INFO ehr_pipeline.runtime:   stage3_verify done in 367.24s
2026-05-03 12:45:26,951 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 12:45:26,954 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 12:45:26,957 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 58, 'medications': 0, 'labs': 0, 'vitals': 1, 'plan': 0}
2026-05-03 12:45:26,957 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 12:45:26,958 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 12:48:01,886 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/patient_summary.md (1196 chars, FK grade=6.48, in_band=False)
2026-05-03 12:48:01,890 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 154.93s
2026-05-03 12:48:01,890 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 12:48:05,851 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/summary.md (408 chars, ratio=0.35, target=0.20-0.30, in_band=False)
2026-05-03 12:48:05,852 INFO ehr_pipeline.runtime:   stage6_summarize done in 3.96s
2026-05-03 12:48:05,857 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:48:05,861 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/check_report.json
2026-05-03 12:48:05,862 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 12:48:05,862 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 12:48:28,117 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/review.json
2026-05-03 12:48:28,120 INFO ehr_pipeline.runtime:   stage8_review done in 22.26s
2026-05-03 12:48:28,121 INFO ehr_pipeline.pipeline:   applied revision: 'Acute osteomyelitis [E:cond:1], intraspinal abscess [E:cond:' → 'Acute osteomyelitis [E:cond:1], intraspinal abscess [E:cond:'
2026-05-03 12:48:28,123 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/summary_revised.md
2026-05-03 12:48:28,123 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:48:28,126 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/check_report_revised.json
2026-05-03 12:48:28,127 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 12:48:28,135 INFO ehr_pipeline.pipeline: Saved input note (2752 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/input_note.txt
2026-05-03 12:48:28,136 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-96621-138277-705450
2026-05-03 12:48:28,139 INFO ehr_pipeline.stages.s1_evidence:   wrote 44 evidence items (19 structured, 25 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/evidence_store.json
2026-05-03 12:48:28,140 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 12:48:28,140 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   131.51 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   367.24 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │   154.93 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     3.96 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    22.26 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   679.91 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.35  (408 / 1157 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462346/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-96621-138277-705450
  note_chars=2752  gold_concepts=7
==================================================================

2026-05-03 12:53:12,473 INFO ehr_pipeline.stages.s2_extract:   extracted 27 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/claims.json
2026-05-03 12:53:12,474 INFO ehr_pipeline.runtime:   stage2_extract done in 284.33s
2026-05-03 12:53:12,475 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 27 claims
2026-05-03 12:56:13,733 INFO ehr_pipeline.stages.s3_verify:   {'verified': 16, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/verifications.json
2026-05-03 12:56:13,735 INFO ehr_pipeline.runtime:   stage3_verify done in 181.26s
2026-05-03 12:56:13,736 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 12:56:13,738 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 12:56:13,740 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 25, 'medications': 2, 'labs': 1, 'vitals': 3, 'plan': 3}
2026-05-03 12:56:13,741 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 12:56:13,741 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 12:56:28,169 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/patient_summary.md (1575 chars, FK grade=6.69, in_band=False)
2026-05-03 12:56:28,170 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.43s
2026-05-03 12:56:28,170 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 12:56:47,923 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/summary.md (983 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 12:56:47,925 INFO ehr_pipeline.runtime:   stage6_summarize done in 19.75s
2026-05-03 12:56:47,928 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:56:47,931 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/check_report.json
2026-05-03 12:56:47,931 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 12:56:47,932 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 12:56:53,191 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/review.json
2026-05-03 12:56:53,195 INFO ehr_pipeline.runtime:   stage8_review done in 5.26s
2026-05-03 12:56:53,198 INFO ehr_pipeline.pipeline:   applied revision: 'History of left shoulder surgery [E:note:row705450:7].' → 'History of surgical operation with implant complication [E:c'
2026-05-03 12:56:53,202 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/summary_revised.md
2026-05-03 12:56:53,207 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:56:53,218 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=11 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/check_report_revised.json
2026-05-03 12:56:53,232 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 12:56:53,279 INFO ehr_pipeline.pipeline: Saved input note (2643 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/input_note.txt
2026-05-03 12:56:53,283 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-41795-138132-683600
2026-05-03 12:56:53,295 INFO ehr_pipeline.stages.s1_evidence:   wrote 66 evidence items (57 structured, 9 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/evidence_store.json
2026-05-03 12:56:53,301 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.02s
2026-05-03 12:56:53,361 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   284.33 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   181.26 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.43 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    19.75 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     5.26 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   505.05 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (983 / 2752 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-96621-138277-705450/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-41795-138132-683600
  note_chars=2643  gold_concepts=6
==================================================================

2026-05-03 12:57:51,654 INFO ehr_pipeline.stages.s2_extract:   extracted 16 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/claims.json
2026-05-03 12:57:51,656 INFO ehr_pipeline.runtime:   stage2_extract done in 58.30s
2026-05-03 12:57:51,658 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 16 claims
2026-05-03 12:58:09,942 INFO ehr_pipeline.stages.s3_verify:   {'verified': 6, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/verifications.json
2026-05-03 12:58:09,943 INFO ehr_pipeline.runtime:   stage3_verify done in 18.28s
2026-05-03 12:58:09,943 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 12:58:09,946 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 12:58:09,948 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 32, 'medications': 0, 'labs': 0, 'vitals': 1, 'plan': 0}
2026-05-03 12:58:09,948 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 12:58:09,949 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 12:58:23,882 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/patient_summary.md (1557 chars, FK grade=6.97, in_band=False)
2026-05-03 12:58:23,883 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 13.93s
2026-05-03 12:58:23,884 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 12:58:39,959 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/summary.md (1443 chars, ratio=0.55, target=0.20-0.30, in_band=False)
2026-05-03 12:58:39,960 INFO ehr_pipeline.runtime:   stage6_summarize done in 16.08s
2026-05-03 12:58:39,963 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 12:58:39,965 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=15 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/check_report.json
2026-05-03 12:58:39,965 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 12:58:39,966 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:04:09,487 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/review.json
2026-05-03 13:04:09,491 INFO ehr_pipeline.runtime:   stage8_review done in 329.52s
2026-05-03 13:04:09,491 INFO ehr_pipeline.pipeline:   applied revision: 'COPD with acute exacerbation [E:cond:3][E:cond:4].' → 'Obstructive chronic bronchitis with acute exacerbation [E:co'
2026-05-03 13:04:09,493 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/summary_revised.md
2026-05-03 13:04:09,493 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:04:09,495 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=15 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/check_report_revised.json
2026-05-03 13:04:09,496 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:04:09,507 INFO ehr_pipeline.pipeline: Saved input note (1644 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/input_note.txt
2026-05-03 13:04:09,507 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-46320-113335-462509
2026-05-03 13:04:09,513 INFO ehr_pipeline.stages.s1_evidence:   wrote 313 evidence items (301 structured, 12 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/evidence_store.json
2026-05-03 13:04:09,513 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 13:04:09,514 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.02 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    58.30 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    18.28 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    13.93 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    16.08 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │   329.52 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   436.14 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.55  (1443 / 2643 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41795-138132-683600/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-46320-113335-462509
  note_chars=1644  gold_concepts=9
==================================================================

2026-05-03 13:11:46,091 INFO ehr_pipeline.stages.s2_extract:   extracted 48 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/claims.json
2026-05-03 13:11:46,095 INFO ehr_pipeline.runtime:   stage2_extract done in 456.58s
2026-05-03 13:11:46,096 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 48 claims
2026-05-03 13:17:42,787 INFO ehr_pipeline.stages.s3_verify:   {'verified': 22, 'contradicted': 0, 'unsupported': 26} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/verifications.json
2026-05-03 13:17:42,790 INFO ehr_pipeline.runtime:   stage3_verify done in 356.69s
2026-05-03 13:17:42,792 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 13:17:42,794 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 13:17:42,800 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 63, 'medications': 4, 'labs': 0, 'vitals': 1, 'plan': 0}
2026-05-03 13:17:42,801 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.01s
2026-05-03 13:17:42,801 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 13:21:51,412 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/patient_summary.md (1419 chars, FK grade=8.28, in_band=False)
2026-05-03 13:21:51,413 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 248.61s
2026-05-03 13:21:51,415 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 13:22:08,394 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/summary.md (708 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 13:22:08,396 INFO ehr_pipeline.runtime:   stage6_summarize done in 16.98s
2026-05-03 13:22:08,404 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:22:08,407 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/check_report.json
2026-05-03 13:22:08,408 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 13:22:08,408 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:22:23,160 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/review.json
2026-05-03 13:22:23,161 INFO ehr_pipeline.runtime:   stage8_review done in 14.75s
2026-05-03 13:22:23,162 INFO ehr_pipeline.pipeline:   applied revision: 'Acute respiratory failure [E:cond:43] with bilateral pleural' → 'Acute respiratory failure [E:cond:43] and pleural effusions '
2026-05-03 13:22:23,162 INFO ehr_pipeline.pipeline:   applied revision: 'DM2 [E:note:row462509:2], HTN [E:note:row462509:2], and chro' → 'DM2 [E:cond:85] and chronic diastolic heart failure [E:cond:'
2026-05-03 13:22:23,168 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/summary_revised.md
2026-05-03 13:22:23,169 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:22:23,172 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/check_report_revised.json
2026-05-03 13:22:23,173 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:22:23,181 INFO ehr_pipeline.pipeline: Saved input note (3467 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/input_note.txt
2026-05-03 13:22:23,183 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-20421-168753-346921
2026-05-03 13:22:23,187 INFO ehr_pipeline.stages.s1_evidence:   wrote 75 evidence items (33 structured, 42 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/evidence_store.json
2026-05-03 13:22:23,188 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 13:22:23,188 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   456.58 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   356.69 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.01 │ ok     │
  │ stage9_patient_summary                                     │   248.61 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    16.98 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    14.75 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1093.64 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (708 / 1644 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46320-113335-462509/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-20421-168753-346921
  note_chars=3467  gold_concepts=5
==================================================================

2026-05-03 13:29:01,312 INFO ehr_pipeline.stages.s2_extract:   extracted 61 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/claims.json
2026-05-03 13:29:01,314 INFO ehr_pipeline.runtime:   stage2_extract done in 398.13s
2026-05-03 13:29:01,315 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 61 claims
2026-05-03 13:31:29,859 INFO ehr_pipeline.stages.s3_verify:   {'verified': 40, 'contradicted': 0, 'unsupported': 21} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/verifications.json
2026-05-03 13:31:29,860 INFO ehr_pipeline.runtime:   stage3_verify done in 148.55s
2026-05-03 13:31:29,860 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 13:31:29,863 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 13:31:29,866 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 53, 'medications': 4, 'labs': 4, 'vitals': 4, 'plan': 6}
2026-05-03 13:31:29,866 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 13:31:29,867 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 13:32:22,273 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/patient_summary.md (1984 chars, FK grade=6.08, in_band=False)
2026-05-03 13:32:22,274 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 52.41s
2026-05-03 13:32:22,275 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 13:32:46,831 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/summary.md (1922 chars, ratio=0.55, target=0.20-0.30, in_band=False)
2026-05-03 13:32:46,833 INFO ehr_pipeline.runtime:   stage6_summarize done in 24.56s
2026-05-03 13:32:46,835 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:32:46,839 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/check_report.json
2026-05-03 13:32:46,840 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 13:32:46,841 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:33:27,128 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/review.json
2026-05-03 13:33:27,129 INFO ehr_pipeline.runtime:   stage8_review done in 40.29s
2026-05-03 13:33:27,129 INFO ehr_pipeline.pipeline:   applied revision: 'Consider transition to a kinear bed [E:note:row346921:42].' → 'Consider change to a kinear bed [E:note:row346921:42].'
2026-05-03 13:33:27,131 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/summary_revised.md
2026-05-03 13:33:27,131 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:33:27,135 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/check_report_revised.json
2026-05-03 13:33:27,135 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:33:27,142 INFO ehr_pipeline.pipeline: Saved input note (2594 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/input_note.txt
2026-05-03 13:33:27,144 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-78481-143054-640463
2026-05-03 13:33:27,146 INFO ehr_pipeline.stages.s1_evidence:   wrote 73 evidence items (45 structured, 28 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/evidence_store.json
2026-05-03 13:33:27,146 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 13:33:27,147 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   398.13 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   148.55 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    52.41 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    24.56 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    40.29 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   663.94 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.55  (1922 / 3467 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-20421-168753-346921/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-78481-143054-640463
  note_chars=2594  gold_concepts=9
==================================================================

2026-05-03 13:35:12,270 INFO ehr_pipeline.stages.s2_extract:   extracted 38 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/claims.json
2026-05-03 13:35:12,271 INFO ehr_pipeline.runtime:   stage2_extract done in 105.12s
2026-05-03 13:35:12,272 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 38 claims
2026-05-03 13:37:29,926 INFO ehr_pipeline.stages.s3_verify:   {'verified': 27, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/verifications.json
2026-05-03 13:37:29,927 INFO ehr_pipeline.runtime:   stage3_verify done in 137.66s
2026-05-03 13:37:29,928 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 13:37:29,931 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 13:37:29,933 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 55, 'medications': 8, 'labs': 1, 'vitals': 2, 'plan': 3}
2026-05-03 13:37:29,933 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 13:37:29,934 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 13:38:10,165 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/patient_summary.md (1920 chars, FK grade=6.19, in_band=False)
2026-05-03 13:38:10,166 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 40.23s
2026-05-03 13:38:10,166 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 13:38:56,347 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/summary.md (1350 chars, ratio=0.52, target=0.20-0.30, in_band=False)
2026-05-03 13:38:56,348 INFO ehr_pipeline.runtime:   stage6_summarize done in 46.18s
2026-05-03 13:38:56,349 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:38:56,351 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/check_report.json
2026-05-03 13:38:56,351 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 13:38:56,351 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:39:27,273 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/review.json
2026-05-03 13:39:27,275 INFO ehr_pipeline.runtime:   stage8_review done in 30.92s
2026-05-03 13:39:27,275 INFO ehr_pipeline.pipeline:   applied revision: 'Additional findings include C. difficile infection [E:cond:1' → 'Additional findings include C. difficile infection [E:cond:1'
2026-05-03 13:39:27,276 INFO ehr_pipeline.pipeline:   applied revision: 'Surgical issues include incisional hernia [E:cond:1], persis' → 'Surgical issues include incisional hernia [E:cond:1], persis'
2026-05-03 13:39:27,277 INFO ehr_pipeline.pipeline:   applied revision: 'Other diagnoses include tachycardia [E:note:row640463:2], SB' → ''
2026-05-03 13:39:27,281 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/summary_revised.md
2026-05-03 13:39:27,282 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:39:27,284 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/check_report_revised.json
2026-05-03 13:39:27,284 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:39:27,292 INFO ehr_pipeline.pipeline: Saved input note (2114 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/input_note.txt
2026-05-03 13:39:27,293 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-97330-197571-437958
2026-05-03 13:39:27,295 INFO ehr_pipeline.stages.s1_evidence:   wrote 56 evidence items (36 structured, 20 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/evidence_store.json
2026-05-03 13:39:27,296 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 13:39:27,296 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   105.12 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   137.66 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    40.23 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    46.18 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    30.92 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   360.12 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.52  (1350 / 2594 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-78481-143054-640463/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-97330-197571-437958
  note_chars=2114  gold_concepts=8
==================================================================

2026-05-03 13:42:11,478 INFO ehr_pipeline.stages.s2_extract:   extracted 29 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/claims.json
2026-05-03 13:42:11,479 INFO ehr_pipeline.runtime:   stage2_extract done in 164.18s
2026-05-03 13:42:11,480 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 29 claims
2026-05-03 13:43:43,326 INFO ehr_pipeline.stages.s3_verify:   {'verified': 14, 'contradicted': 0, 'unsupported': 15} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/verifications.json
2026-05-03 13:43:43,327 INFO ehr_pipeline.runtime:   stage3_verify done in 91.85s
2026-05-03 13:43:43,327 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 13:43:43,331 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 13:43:43,332 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 41, 'medications': 1, 'labs': 1, 'vitals': 0, 'plan': 6}
2026-05-03 13:43:43,333 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 13:43:43,334 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 13:43:55,333 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/patient_summary.md (1518 chars, FK grade=6.92, in_band=False)
2026-05-03 13:43:55,334 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 12.00s
2026-05-03 13:43:55,335 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 13:44:06,294 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/summary.md (966 chars, ratio=0.46, target=0.20-0.30, in_band=False)
2026-05-03 13:44:06,295 INFO ehr_pipeline.runtime:   stage6_summarize done in 10.96s
2026-05-03 13:44:06,298 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:44:06,302 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/check_report.json
2026-05-03 13:44:06,303 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 13:44:06,303 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:44:16,265 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/review.json
2026-05-03 13:44:16,266 INFO ehr_pipeline.runtime:   stage8_review done in 9.96s
2026-05-03 13:44:16,266 INFO ehr_pipeline.pipeline:   applied revision: 'Multiple fractures: lower femur [E:cond:1][E:note:row437958:' → 'Multiple fractures: lower femur [E:cond:1][E:note:row437958:'
2026-05-03 13:44:16,268 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/summary_revised.md
2026-05-03 13:44:16,269 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:44:16,270 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/check_report_revised.json
2026-05-03 13:44:16,271 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:44:16,278 INFO ehr_pipeline.pipeline: Saved input note (4893 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/input_note.txt
2026-05-03 13:44:16,279 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-46105-126246-529623
2026-05-03 13:44:16,281 INFO ehr_pipeline.stages.s1_evidence:   wrote 76 evidence items (26 structured, 50 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/evidence_store.json
2026-05-03 13:44:16,282 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 13:44:16,283 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   164.18 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    91.85 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    12.00 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    10.96 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     9.96 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   288.96 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.46  (966 / 2114 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-97330-197571-437958/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-46105-126246-529623
  note_chars=4893  gold_concepts=11
==================================================================

2026-05-03 13:46:01,519 INFO ehr_pipeline.stages.s2_extract:   extracted 49 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/claims.json
2026-05-03 13:46:01,520 INFO ehr_pipeline.runtime:   stage2_extract done in 105.24s
2026-05-03 13:46:01,521 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 49 claims
2026-05-03 13:47:33,270 INFO ehr_pipeline.stages.s3_verify:   {'verified': 33, 'contradicted': 0, 'unsupported': 16} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/verifications.json
2026-05-03 13:47:33,271 INFO ehr_pipeline.runtime:   stage3_verify done in 91.75s
2026-05-03 13:47:33,271 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 13:47:33,275 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 13:47:33,277 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 49, 'medications': 4, 'labs': 1, 'vitals': 4, 'plan': 0}
2026-05-03 13:47:33,278 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 13:47:33,278 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 13:47:47,299 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/patient_summary.md (1678 chars, FK grade=8.03, in_band=False)
2026-05-03 13:47:47,300 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.02s
2026-05-03 13:47:47,301 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 13:48:09,723 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/summary.md (1892 chars, ratio=0.39, target=0.20-0.30, in_band=False)
2026-05-03 13:48:09,725 INFO ehr_pipeline.runtime:   stage6_summarize done in 22.42s
2026-05-03 13:48:09,726 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:48:09,731 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=16 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/check_report.json
2026-05-03 13:48:09,731 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 13:48:09,732 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:51:02,575 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/review.json
2026-05-03 13:51:02,576 INFO ehr_pipeline.runtime:   stage8_review done in 172.84s
2026-05-03 13:51:02,577 INFO ehr_pipeline.pipeline:   applied revision: 'Received one tide dose of vancomycin and a standing dose [E:' → 'Received one TID dose of vancomycin and a standing dose [E:n'
2026-05-03 13:51:02,579 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/summary_revised.md
2026-05-03 13:51:02,579 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:51:02,582 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=16 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/check_report_revised.json
2026-05-03 13:51:02,582 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:51:02,588 INFO ehr_pipeline.pipeline: Saved input note (2733 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/input_note.txt
2026-05-03 13:51:02,589 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-47829-175022-600943
2026-05-03 13:51:02,592 INFO ehr_pipeline.stages.s1_evidence:   wrote 65 evidence items (35 structured, 30 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/evidence_store.json
2026-05-03 13:51:02,592 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 13:51:02,593 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   105.24 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    91.75 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.02 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    22.42 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │   172.84 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   406.29 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.39  (1892 / 4893 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-46105-126246-529623/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-47829-175022-600943
  note_chars=2733  gold_concepts=9
==================================================================

2026-05-03 13:53:12,831 INFO ehr_pipeline.stages.s2_extract:   extracted 30 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/claims.json
2026-05-03 13:53:12,833 INFO ehr_pipeline.runtime:   stage2_extract done in 130.24s
2026-05-03 13:53:12,833 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 30 claims
2026-05-03 13:54:01,342 INFO ehr_pipeline.stages.s3_verify:   {'verified': 17, 'contradicted': 0, 'unsupported': 13} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/verifications.json
2026-05-03 13:54:01,344 INFO ehr_pipeline.runtime:   stage3_verify done in 48.51s
2026-05-03 13:54:01,344 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 13:54:01,348 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 13:54:01,350 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 36, 'medications': 2, 'labs': 3, 'vitals': 2, 'plan': 1}
2026-05-03 13:54:01,350 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 13:54:01,351 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 13:54:16,526 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/patient_summary.md (1842 chars, FK grade=6.79, in_band=False)
2026-05-03 13:54:16,528 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.18s
2026-05-03 13:54:16,529 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 13:54:27,174 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/summary.md (1024 chars, ratio=0.37, target=0.20-0.30, in_band=False)
2026-05-03 13:54:27,175 INFO ehr_pipeline.runtime:   stage6_summarize done in 10.65s
2026-05-03 13:54:27,179 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:54:27,180 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/check_report.json
2026-05-03 13:54:27,181 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 13:54:27,181 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 13:54:40,484 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/review.json
2026-05-03 13:54:40,486 INFO ehr_pipeline.runtime:   stage8_review done in 13.30s
2026-05-03 13:54:40,486 INFO ehr_pipeline.pipeline:   applied revision: 'Also noted: hypotension [E:cond:11], corneal ulcer [E:cond:1' → 'Also noted: hypotension [E:cond:11], corneal ulcer [E:cond:1'
2026-05-03 13:54:40,489 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/summary_revised.md
2026-05-03 13:54:40,490 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 13:54:40,492 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/check_report_revised.json
2026-05-03 13:54:40,492 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 13:54:40,498 INFO ehr_pipeline.pipeline: Saved input note (2071 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/input_note.txt
2026-05-03 13:54:40,499 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-64407-175035-619126
2026-05-03 13:54:40,502 INFO ehr_pipeline.stages.s1_evidence:   wrote 49 evidence items (23 structured, 26 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/evidence_store.json
2026-05-03 13:54:40,502 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 13:54:40,503 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   130.24 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    48.51 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.18 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    10.65 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    13.30 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   217.89 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.37  (1024 / 2733 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-47829-175022-600943/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-64407-175035-619126
  note_chars=2071  gold_concepts=8
==================================================================

2026-05-03 13:57:05,078 INFO ehr_pipeline.stages.s2_extract:   extracted 51 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/claims.json
2026-05-03 13:57:05,079 INFO ehr_pipeline.runtime:   stage2_extract done in 144.58s
2026-05-03 13:57:05,081 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 51 claims
2026-05-03 14:00:47,191 INFO ehr_pipeline.stages.s3_verify:   {'verified': 35, 'contradicted': 0, 'unsupported': 16} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/verifications.json
2026-05-03 14:00:47,192 INFO ehr_pipeline.runtime:   stage3_verify done in 222.11s
2026-05-03 14:00:47,192 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:00:47,196 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:00:47,198 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 34, 'medications': 1, 'labs': 3, 'vitals': 8, 'plan': 9}
2026-05-03 14:00:47,198 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:00:47,199 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:01:16,575 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/patient_summary.md (2072 chars, FK grade=6.72, in_band=False)
2026-05-03 14:01:16,576 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 29.38s
2026-05-03 14:01:16,577 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:02:35,999 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/summary.md (1088 chars, ratio=0.53, target=0.20-0.30, in_band=False)
2026-05-03 14:02:36,001 INFO ehr_pipeline.runtime:   stage6_summarize done in 79.42s
2026-05-03 14:02:36,003 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:02:36,007 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=18 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/check_report.json
2026-05-03 14:02:36,007 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:02:36,008 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:02:41,953 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/review.json
2026-05-03 14:02:41,954 INFO ehr_pipeline.runtime:   stage8_review done in 5.95s
2026-05-03 14:02:41,954 INFO ehr_pipeline.pipeline:   applied revision: 'Delirium [E:cond:8], acidosis [E:cond:9], and hyperpotassemi' → 'Delirium [E:cond:8] and acidosis [E:cond:9]; hyperpotassemia'
2026-05-03 14:02:41,956 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/summary_revised.md
2026-05-03 14:02:41,957 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:02:41,959 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=18 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/check_report_revised.json
2026-05-03 14:02:41,960 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:02:41,963 INFO ehr_pipeline.pipeline: Saved input note (2785 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/input_note.txt
2026-05-03 14:02:41,964 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-86585-123444-546150
2026-05-03 14:02:41,965 INFO ehr_pipeline.stages.s1_evidence:   wrote 45 evidence items (18 structured, 27 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/evidence_store.json
2026-05-03 14:02:41,966 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:02:41,966 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   144.58 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   222.11 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    29.38 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    79.42 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     5.95 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   481.45 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.53  (1088 / 2071 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64407-175035-619126/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-86585-123444-546150
  note_chars=2785  gold_concepts=14
==================================================================

2026-05-03 14:05:27,244 INFO ehr_pipeline.stages.s2_extract:   extracted 42 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/claims.json
2026-05-03 14:05:27,246 INFO ehr_pipeline.runtime:   stage2_extract done in 165.28s
2026-05-03 14:05:27,246 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 42 claims
2026-05-03 14:07:21,104 INFO ehr_pipeline.stages.s3_verify:   {'verified': 28, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/verifications.json
2026-05-03 14:07:21,107 INFO ehr_pipeline.runtime:   stage3_verify done in 113.86s
2026-05-03 14:07:21,108 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:07:21,111 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:07:21,114 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 28, 'medications': 6, 'labs': 2, 'vitals': 4, 'plan': 5}
2026-05-03 14:07:21,114 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:07:21,115 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:08:29,464 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/patient_summary.md (1737 chars, FK grade=7.94, in_band=True)
2026-05-03 14:08:29,467 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 68.35s
2026-05-03 14:08:29,469 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:09:09,953 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/summary.md (1300 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 14:09:09,954 INFO ehr_pipeline.runtime:   stage6_summarize done in 40.49s
2026-05-03 14:09:09,957 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:09:09,959 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=14 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/check_report.json
2026-05-03 14:09:09,960 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:09:09,961 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:10:12,102 INFO ehr_pipeline.stages.s8_review:   concerns=4 recommended_revisions=4 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/review.json
2026-05-03 14:10:12,103 INFO ehr_pipeline.runtime:   stage8_review done in 62.14s
2026-05-03 14:10:12,103 INFO ehr_pipeline.pipeline:   applied revision: 'History of CABG [E:note:row546150:1], I-CMP [E:note:row54615' → 'History of coronary atherosclerosis [E:cond:7], atrial fibri'
2026-05-03 14:10:12,104 INFO ehr_pipeline.pipeline:   applied revision: 'Chronic kidney disease [E:cond:10] and chronic anemia [E:not' → 'Chronic kidney disease [E:cond:10] and anemia [E:note:row546'
2026-05-03 14:10:12,105 INFO ehr_pipeline.pipeline:   applied revision: 'Stage II pressure ulcer [E:cond:13] and impaired skin integr' → 'Stage II pressure ulcer [E:cond:13].'
2026-05-03 14:10:12,105 INFO ehr_pipeline.pipeline:   applied revision: 'Patient is a smoker [E:note:row546150:27].' → ''
2026-05-03 14:10:12,108 INFO ehr_pipeline.pipeline: Wrote revised summary (4 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/summary_revised.md
2026-05-03 14:10:12,108 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:10:12,111 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=13 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/check_report_revised.json
2026-05-03 14:10:12,111 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:10:12,119 INFO ehr_pipeline.pipeline: Saved input note (3548 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/input_note.txt
2026-05-03 14:10:12,120 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-43126-132026-495933
2026-05-03 14:10:12,124 INFO ehr_pipeline.stages.s1_evidence:   wrote 123 evidence items (89 structured, 34 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/evidence_store.json
2026-05-03 14:10:12,125 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 14:10:12,125 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   165.28 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   113.86 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    68.35 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    40.49 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    62.14 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   450.13 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (1300 / 2785 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-86585-123444-546150/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-43126-132026-495933
  note_chars=3548  gold_concepts=4
==================================================================

2026-05-03 14:12:52,233 INFO ehr_pipeline.stages.s2_extract:   extracted 49 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/claims.json
2026-05-03 14:12:52,235 INFO ehr_pipeline.runtime:   stage2_extract done in 160.11s
2026-05-03 14:12:52,236 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 49 claims
2026-05-03 14:19:30,665 INFO ehr_pipeline.stages.s3_verify:   {'verified': 38, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/verifications.json
2026-05-03 14:19:30,668 INFO ehr_pipeline.runtime:   stage3_verify done in 398.43s
2026-05-03 14:19:30,669 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:19:30,671 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:19:30,675 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 64, 'medications': 6, 'labs': 1, 'vitals': 1, 'plan': 0}
2026-05-03 14:19:30,675 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:19:30,677 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:20:02,960 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/patient_summary.md (2103 chars, FK grade=8.83, in_band=False)
2026-05-03 14:20:02,965 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 32.29s
2026-05-03 14:20:02,965 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:21:48,625 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/summary.md (1509 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 14:21:48,626 INFO ehr_pipeline.runtime:   stage6_summarize done in 105.66s
2026-05-03 14:21:48,628 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:21:48,630 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/check_report.json
2026-05-03 14:21:48,631 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:21:48,631 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:22:12,160 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/review.json
2026-05-03 14:22:12,162 INFO ehr_pipeline.runtime:   stage8_review done in 23.53s
2026-05-03 14:22:12,163 INFO ehr_pipeline.pipeline:   applied revision: 'Hematologic/oncologic history includes CLL [E:cond:29][E:con' → 'Hematologic/oncologic history includes CLL in remission [E:c'
2026-05-03 14:22:12,165 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/summary_revised.md
2026-05-03 14:22:12,166 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:22:12,169 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/check_report_revised.json
2026-05-03 14:22:12,170 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:22:12,176 INFO ehr_pipeline.pipeline: Saved input note (1275 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/input_note.txt
2026-05-03 14:22:12,177 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-99883-150755-651791
2026-05-03 14:22:12,180 INFO ehr_pipeline.stages.s1_evidence:   wrote 31 evidence items (16 structured, 15 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/evidence_store.json
2026-05-03 14:22:12,180 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:22:12,181 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   160.11 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   398.43 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    32.29 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │   105.66 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    23.53 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   720.04 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (1509 / 3548 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-43126-132026-495933/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-99883-150755-651791
  note_chars=1275  gold_concepts=8
==================================================================

2026-05-03 14:22:50,361 INFO ehr_pipeline.stages.s2_extract:   extracted 17 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/claims.json
2026-05-03 14:22:50,362 INFO ehr_pipeline.runtime:   stage2_extract done in 38.18s
2026-05-03 14:22:50,363 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 17 claims
2026-05-03 14:26:54,497 INFO ehr_pipeline.stages.s3_verify:   {'verified': 11, 'contradicted': 0, 'unsupported': 6} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/verifications.json
2026-05-03 14:26:54,499 INFO ehr_pipeline.runtime:   stage3_verify done in 244.14s
2026-05-03 14:26:54,500 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:26:54,502 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:26:54,504 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 16, 'medications': 5, 'labs': 1, 'vitals': 0, 'plan': 3}
2026-05-03 14:26:54,505 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:26:54,505 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:27:12,190 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/patient_summary.md (1442 chars, FK grade=6.46, in_band=False)
2026-05-03 14:27:12,191 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.69s
2026-05-03 14:27:12,192 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:27:29,764 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/summary.md (776 chars, ratio=0.61, target=0.20-0.30, in_band=False)
2026-05-03 14:27:29,766 INFO ehr_pipeline.runtime:   stage6_summarize done in 17.57s
2026-05-03 14:27:29,769 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:27:29,772 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/check_report.json
2026-05-03 14:27:29,773 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:27:29,774 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:27:34,631 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/review.json
2026-05-03 14:27:34,633 INFO ehr_pipeline.runtime:   stage8_review done in 4.86s
2026-05-03 14:27:34,633 INFO ehr_pipeline.pipeline:   applied revision: 'Patient reports increased wheezing/asthma [E:cond:4].' → 'Patient has asthma exacerbation [E:cond:4].'
2026-05-03 14:27:34,636 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/summary_revised.md
2026-05-03 14:27:34,638 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:27:34,640 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/check_report_revised.json
2026-05-03 14:27:34,641 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:27:34,648 INFO ehr_pipeline.pipeline: Saved input note (2210 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/input_note.txt
2026-05-03 14:27:34,649 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-82313-116027-681825
2026-05-03 14:27:34,652 INFO ehr_pipeline.stages.s1_evidence:   wrote 51 evidence items (45 structured, 6 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/evidence_store.json
2026-05-03 14:27:34,653 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:27:34,654 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    38.18 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   244.14 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.69 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    17.57 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     4.86 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   322.45 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.61  (776 / 1275 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-99883-150755-651791/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-82313-116027-681825
  note_chars=2210  gold_concepts=9
==================================================================

2026-05-03 14:28:30,344 INFO ehr_pipeline.stages.s2_extract:   extracted 27 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/claims.json
2026-05-03 14:28:30,346 INFO ehr_pipeline.runtime:   stage2_extract done in 55.69s
2026-05-03 14:28:30,347 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 27 claims
2026-05-03 14:28:55,939 INFO ehr_pipeline.stages.s3_verify:   {'verified': 5, 'contradicted': 0, 'unsupported': 22} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/verifications.json
2026-05-03 14:28:55,941 INFO ehr_pipeline.runtime:   stage3_verify done in 25.59s
2026-05-03 14:28:55,942 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:28:55,943 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:28:55,944 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 47, 'medications': 0, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-03 14:28:55,944 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:28:55,945 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:29:04,335 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/patient_summary.md (1181 chars, FK grade=7.83, in_band=True)
2026-05-03 14:29:04,336 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 8.39s
2026-05-03 14:29:04,337 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:29:10,785 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/summary.md (744 chars, ratio=0.34, target=0.20-0.30, in_band=False)
2026-05-03 14:29:10,786 INFO ehr_pipeline.runtime:   stage6_summarize done in 6.45s
2026-05-03 14:29:10,787 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:29:10,790 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/check_report.json
2026-05-03 14:29:10,790 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:29:10,791 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:29:15,731 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/review.json
2026-05-03 14:29:15,731 INFO ehr_pipeline.runtime:   stage8_review done in 4.94s
2026-05-03 14:29:15,732 INFO ehr_pipeline.pipeline:   applied revision: 'Acute kidney failure [E:cond:3], hyperosmolality/hypernatrem' → 'Acute kidney failure [E:cond:3], complications due to renal '
2026-05-03 14:29:15,733 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/summary_revised.md
2026-05-03 14:29:15,734 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:29:15,736 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/check_report_revised.json
2026-05-03 14:29:15,736 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:29:15,740 INFO ehr_pipeline.pipeline: Saved input note (1640 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/input_note.txt
2026-05-03 14:29:15,740 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-60739-180716-643550
2026-05-03 14:29:15,742 INFO ehr_pipeline.stages.s1_evidence:   wrote 74 evidence items (65 structured, 9 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/evidence_store.json
2026-05-03 14:29:15,742 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:29:15,743 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    55.69 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    25.59 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │     8.39 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     6.45 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     4.94 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   101.08 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.34  (744 / 2210 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-82313-116027-681825/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-60739-180716-643550
  note_chars=1640  gold_concepts=9
==================================================================

2026-05-03 14:33:14,612 INFO ehr_pipeline.stages.s2_extract:   extracted 34 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/claims.json
2026-05-03 14:33:14,615 INFO ehr_pipeline.runtime:   stage2_extract done in 238.87s
2026-05-03 14:33:14,617 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 34 claims
2026-05-03 14:33:57,946 INFO ehr_pipeline.stages.s3_verify:   {'verified': 13, 'contradicted': 0, 'unsupported': 21} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/verifications.json
2026-05-03 14:33:57,947 INFO ehr_pipeline.runtime:   stage3_verify done in 43.33s
2026-05-03 14:33:57,947 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:33:57,951 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:33:57,953 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 39, 'medications': 2, 'labs': 2, 'vitals': 1, 'plan': 0}
2026-05-03 14:33:57,954 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:33:57,954 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:34:14,202 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/patient_summary.md (1752 chars, FK grade=8.58, in_band=False)
2026-05-03 14:34:14,204 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 16.25s
2026-05-03 14:34:14,205 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:34:25,770 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/summary.md (736 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 14:34:25,771 INFO ehr_pipeline.runtime:   stage6_summarize done in 11.57s
2026-05-03 14:34:25,773 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:34:25,774 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/check_report.json
2026-05-03 14:34:25,775 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:34:25,775 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:35:23,218 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/review.json
2026-05-03 14:35:23,219 INFO ehr_pipeline.runtime:   stage8_review done in 57.44s
2026-05-03 14:35:23,220 INFO ehr_pipeline.pipeline:   applied revision: 'Diverticulitis with hemorrhage [E:cond:1][E:cond:2], acute o' → 'Diverticulitis with hemorrhage [E:cond:1][E:cond:2], acute o'
2026-05-03 14:35:23,223 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/summary_revised.md
2026-05-03 14:35:23,224 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:35:23,226 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=6 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/check_report_revised.json
2026-05-03 14:35:23,227 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:35:23,235 INFO ehr_pipeline.pipeline: Saved input note (1454 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/input_note.txt
2026-05-03 14:35:23,236 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-88078-105497-730292
2026-05-03 14:35:23,240 INFO ehr_pipeline.stages.s1_evidence:   wrote 67 evidence items (59 structured, 8 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/evidence_store.json
2026-05-03 14:35:23,240 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:35:23,241 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   238.87 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    43.33 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    16.25 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    11.57 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    57.44 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   367.47 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (736 / 1640 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60739-180716-643550/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-88078-105497-730292
  note_chars=1454  gold_concepts=10
==================================================================

2026-05-03 14:36:08,061 INFO ehr_pipeline.stages.s2_extract:   extracted 24 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/claims.json
2026-05-03 14:36:08,068 INFO ehr_pipeline.runtime:   stage2_extract done in 44.83s
2026-05-03 14:36:08,070 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 24 claims
2026-05-03 14:39:02,292 INFO ehr_pipeline.stages.s3_verify:   {'verified': 8, 'contradicted': 0, 'unsupported': 16} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/verifications.json
2026-05-03 14:39:02,293 INFO ehr_pipeline.runtime:   stage3_verify done in 174.22s
2026-05-03 14:39:02,294 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:39:02,297 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:39:02,298 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 30, 'medications': 3, 'labs': 0, 'vitals': 2, 'plan': 1}
2026-05-03 14:39:02,299 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:39:02,299 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:39:46,733 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/patient_summary.md (1956 chars, FK grade=7.70, in_band=True)
2026-05-03 14:39:46,738 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 44.44s
2026-05-03 14:39:46,739 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:39:59,136 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/summary.md (730 chars, ratio=0.50, target=0.20-0.30, in_band=False)
2026-05-03 14:39:59,137 INFO ehr_pipeline.runtime:   stage6_summarize done in 12.40s
2026-05-03 14:39:59,139 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:39:59,142 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/check_report.json
2026-05-03 14:39:59,142 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:39:59,143 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:41:45,674 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/review.json
2026-05-03 14:41:45,675 INFO ehr_pipeline.runtime:   stage8_review done in 106.53s
2026-05-03 14:41:45,676 INFO ehr_pipeline.pipeline:   applied revision: 'Lung contusion [E:cond:1][E:cond:2], pneumonia [E:cond:3][E:' → 'Lung contusion [E:cond:1][E:cond:2], pneumonia [E:cond:3][E:'
2026-05-03 14:41:45,677 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/summary_revised.md
2026-05-03 14:41:45,677 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:41:45,680 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/check_report_revised.json
2026-05-03 14:41:45,680 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:41:45,690 INFO ehr_pipeline.pipeline: Saved input note (6001 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/input_note.txt
2026-05-03 14:41:45,692 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-64798-160505-695419
2026-05-03 14:41:45,696 INFO ehr_pipeline.stages.s1_evidence:   wrote 121 evidence items (49 structured, 72 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/evidence_store.json
2026-05-03 14:41:45,697 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:41:45,697 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    44.83 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   174.22 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    44.44 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    12.40 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │   106.53 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   382.43 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.50  (730 / 1454 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-88078-105497-730292/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-64798-160505-695419
  note_chars=6001  gold_concepts=4
==================================================================

2026-05-03 14:45:08,217 INFO ehr_pipeline.stages.s2_extract:   extracted 66 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/claims.json
2026-05-03 14:45:08,220 INFO ehr_pipeline.runtime:   stage2_extract done in 202.52s
2026-05-03 14:45:08,221 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 66 claims
2026-05-03 14:49:40,499 INFO ehr_pipeline.stages.s3_verify:   {'verified': 44, 'contradicted': 0, 'unsupported': 22} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/verifications.json
2026-05-03 14:49:40,501 INFO ehr_pipeline.runtime:   stage3_verify done in 272.28s
2026-05-03 14:49:40,502 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:49:40,503 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:49:40,506 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 66, 'medications': 9, 'labs': 11, 'vitals': 4, 'plan': 0}
2026-05-03 14:49:40,507 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:49:40,507 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:49:55,245 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/patient_summary.md (1939 chars, FK grade=6.63, in_band=False)
2026-05-03 14:49:55,246 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.74s
2026-05-03 14:49:55,247 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:50:14,855 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/summary.md (2364 chars, ratio=0.39, target=0.20-0.30, in_band=False)
2026-05-03 14:50:14,856 INFO ehr_pipeline.runtime:   stage6_summarize done in 19.61s
2026-05-03 14:50:14,858 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:50:14,863 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=24 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/check_report.json
2026-05-03 14:50:14,864 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 14:50:14,865 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:50:42,791 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/review.json
2026-05-03 14:50:42,793 INFO ehr_pipeline.runtime:   stage8_review done in 27.93s
2026-05-03 14:50:42,793 INFO ehr_pipeline.pipeline:   applied revision: 'Respiratory status is critical with acute respiratory failur' → 'Respiratory findings include acute respiratory failure [E:co'
2026-05-03 14:50:42,797 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/summary_revised.md
2026-05-03 14:50:42,798 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:50:42,801 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=24 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/check_report_revised.json
2026-05-03 14:50:42,802 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:50:42,811 INFO ehr_pipeline.pipeline: Saved input note (3231 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/input_note.txt
2026-05-03 14:50:42,812 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-62795-173748-671542
2026-05-03 14:50:42,818 INFO ehr_pipeline.stages.s1_evidence:   wrote 199 evidence items (159 structured, 40 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/evidence_store.json
2026-05-03 14:50:42,819 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 14:50:42,819 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   202.52 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   272.28 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.74 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    19.61 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    27.93 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   537.09 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.39  (2364 / 6001 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-64798-160505-695419/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-62795-173748-671542
  note_chars=3231  gold_concepts=5
==================================================================

2026-05-03 14:52:01,232 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/claims.json
2026-05-03 14:52:01,234 INFO ehr_pipeline.runtime:   stage2_extract done in 78.41s
2026-05-03 14:52:01,236 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 14:53:42,505 INFO ehr_pipeline.stages.s3_verify:   {'verified': 30, 'contradicted': 0, 'unsupported': 7} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/verifications.json
2026-05-03 14:53:42,507 INFO ehr_pipeline.runtime:   stage3_verify done in 101.27s
2026-05-03 14:53:42,508 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 14:53:42,511 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 14:53:42,514 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 74, 'medications': 8, 'labs': 5, 'vitals': 1, 'plan': 2}
2026-05-03 14:53:42,515 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 14:53:42,515 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 14:54:12,566 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/patient_summary.md (1807 chars, FK grade=7.55, in_band=True)
2026-05-03 14:54:12,566 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 30.05s
2026-05-03 14:54:12,567 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 14:54:24,820 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/summary.md (1530 chars, ratio=0.47, target=0.20-0.30, in_band=False)
2026-05-03 14:54:24,821 INFO ehr_pipeline.runtime:   stage6_summarize done in 12.25s
2026-05-03 14:54:24,827 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:54:24,829 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/check_report.json
2026-05-03 14:54:24,829 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 14:54:24,830 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 14:54:46,432 INFO ehr_pipeline.stages.s8_review:   concerns=3 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/review.json
2026-05-03 14:54:46,435 INFO ehr_pipeline.runtime:   stage8_review done in 21.60s
2026-05-03 14:54:46,435 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presents with multiple comorbidities including alcoh' → 'Patient presents with comorbidities including alcoholic cirr'
2026-05-03 14:54:46,436 INFO ehr_pipeline.pipeline:   applied revision: 'Surgical complications include a pathologic vertebral fractu' → 'Findings include a pathologic vertebral fracture [E:cond:17]'
2026-05-03 14:54:46,436 INFO ehr_pipeline.pipeline:   applied revision: 'Other findings include spinal stenosis [E:cond:67][E:cond:68' → 'Other findings include pleural effusion [E:cond:9][E:cond:10'
2026-05-03 14:54:46,438 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/summary_revised.md
2026-05-03 14:54:46,439 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 14:54:46,441 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/check_report_revised.json
2026-05-03 14:54:46,442 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 14:54:46,450 INFO ehr_pipeline.pipeline: Saved input note (2297 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/input_note.txt
2026-05-03 14:54:46,451 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-80658-117314-669605
2026-05-03 14:54:46,453 INFO ehr_pipeline.stages.s1_evidence:   wrote 59 evidence items (32 structured, 27 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/evidence_store.json
2026-05-03 14:54:46,453 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 14:54:46,453 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    78.41 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   101.27 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    30.05 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    12.25 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    21.60 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   243.61 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.47  (1530 / 3231 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=3  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-62795-173748-671542/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-80658-117314-669605
  note_chars=2297  gold_concepts=8
==================================================================

2026-05-03 14:56:42,626 INFO ehr_pipeline.stages.s2_extract:   extracted 37 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/claims.json
2026-05-03 14:56:42,629 INFO ehr_pipeline.runtime:   stage2_extract done in 116.18s
2026-05-03 14:56:42,630 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 37 claims
2026-05-03 15:03:26,735 INFO ehr_pipeline.stages.s3_verify:   {'verified': 23, 'contradicted': 0, 'unsupported': 14} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/verifications.json
2026-05-03 15:03:26,752 INFO ehr_pipeline.runtime:   stage3_verify done in 404.12s
2026-05-03 15:03:26,797 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:03:27,056 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:03:27,328 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 44, 'medications': 7, 'labs': 1, 'vitals': 0, 'plan': 1}
2026-05-03 15:03:27,404 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.35s
2026-05-03 15:03:27,450 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:10:31,974 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/patient_summary.md (2044 chars, FK grade=8.02, in_band=False)
2026-05-03 15:10:31,976 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 424.53s
2026-05-03 15:10:31,976 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:10:44,948 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/summary.md (1013 chars, ratio=0.44, target=0.20-0.30, in_band=False)
2026-05-03 15:10:44,948 INFO ehr_pipeline.runtime:   stage6_summarize done in 12.97s
2026-05-03 15:10:44,949 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:10:44,952 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/check_report.json
2026-05-03 15:10:44,952 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:10:44,952 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:12:47,213 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/review.json
2026-05-03 15:12:47,214 INFO ehr_pipeline.runtime:   stage8_review done in 122.26s
2026-05-03 15:12:47,215 INFO ehr_pipeline.pipeline:   applied revision: 'Acute respiratory failure [E:cond:2], ILD/IPF/NSIP [E:note:r' → 'Acute respiratory failure [E:cond:2] and postinflammatory pu'
2026-05-03 15:12:47,215 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/summary_revised.md
2026-05-03 15:12:47,216 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:12:47,223 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/check_report_revised.json
2026-05-03 15:12:47,224 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:12:47,230 INFO ehr_pipeline.pipeline: Saved input note (1857 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/input_note.txt
2026-05-03 15:12:47,230 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-52296-112991-422543
2026-05-03 15:12:47,234 INFO ehr_pipeline.stages.s1_evidence:   wrote 107 evidence items (89 structured, 18 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/evidence_store.json
2026-05-03 15:12:47,234 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:12:47,235 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   116.18 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   404.12 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.35 │ ok     │
  │ stage9_patient_summary                                     │   424.53 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    12.97 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │   122.26 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │  1080.41 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.44  (1013 / 2297 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-80658-117314-669605/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-52296-112991-422543
  note_chars=1857  gold_concepts=8
==================================================================

2026-05-03 15:13:48,077 INFO ehr_pipeline.stages.s2_extract:   extracted 32 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/claims.json
2026-05-03 15:13:48,078 INFO ehr_pipeline.runtime:   stage2_extract done in 60.84s
2026-05-03 15:13:48,078 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 32 claims
2026-05-03 15:16:40,924 INFO ehr_pipeline.stages.s3_verify:   {'verified': 24, 'contradicted': 0, 'unsupported': 8} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/verifications.json
2026-05-03 15:16:40,924 INFO ehr_pipeline.runtime:   stage3_verify done in 172.85s
2026-05-03 15:16:40,924 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:16:40,926 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:16:40,927 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 47, 'medications': 4, 'labs': 0, 'vitals': 8, 'plan': 5}
2026-05-03 15:16:40,927 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:16:40,928 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:16:56,179 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/patient_summary.md (2151 chars, FK grade=7.71, in_band=True)
2026-05-03 15:16:56,179 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.25s
2026-05-03 15:16:56,179 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:17:04,886 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/summary.md (1007 chars, ratio=0.54, target=0.20-0.30, in_band=False)
2026-05-03 15:17:04,888 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.71s
2026-05-03 15:17:04,894 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:17:04,897 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/check_report.json
2026-05-03 15:17:04,901 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 15:17:04,906 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:17:15,503 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/review.json
2026-05-03 15:17:15,504 INFO ehr_pipeline.runtime:   stage8_review done in 10.60s
2026-05-03 15:17:15,504 INFO ehr_pipeline.pipeline:   applied revision: 'Patient presented with altered mental status [E:note:row4225' → 'Patient presented with fevers [E:note:row422543:3], hypotens'
2026-05-03 15:17:15,505 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/summary_revised.md
2026-05-03 15:17:15,505 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:17:15,506 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=7 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/check_report_revised.json
2026-05-03 15:17:15,506 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:17:15,509 INFO ehr_pipeline.pipeline: Saved input note (2908 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/input_note.txt
2026-05-03 15:17:15,509 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-49496-112342-514701
2026-05-03 15:17:15,511 INFO ehr_pipeline.stages.s1_evidence:   wrote 64 evidence items (33 structured, 31 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/evidence_store.json
2026-05-03 15:17:15,511 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:17:15,511 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    60.84 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   172.85 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.25 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.71 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    10.60 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   268.26 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.54  (1007 / 1857 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-52296-112991-422543/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-49496-112342-514701
  note_chars=2908  gold_concepts=12
==================================================================

2026-05-03 15:24:31,754 INFO ehr_pipeline.stages.s2_extract:   extracted 41 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/claims.json
2026-05-03 15:24:31,754 INFO ehr_pipeline.runtime:   stage2_extract done in 436.24s
2026-05-03 15:24:31,755 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 41 claims
2026-05-03 15:25:34,845 INFO ehr_pipeline.stages.s3_verify:   {'verified': 20, 'contradicted': 0, 'unsupported': 21} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/verifications.json
2026-05-03 15:25:34,845 INFO ehr_pipeline.runtime:   stage3_verify done in 63.09s
2026-05-03 15:25:34,845 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:25:34,846 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:25:34,847 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 45, 'medications': 2, 'labs': 0, 'vitals': 1, 'plan': 2}
2026-05-03 15:25:34,847 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:25:34,848 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:26:44,011 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/patient_summary.md (1689 chars, FK grade=9.07, in_band=False)
2026-05-03 15:26:44,012 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 69.16s
2026-05-03 15:26:44,012 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:27:01,767 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/summary.md (1043 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 15:27:01,767 INFO ehr_pipeline.runtime:   stage6_summarize done in 17.75s
2026-05-03 15:27:01,768 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:27:01,770 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/check_report.json
2026-05-03 15:27:01,770 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:27:01,771 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:28:40,865 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/review.json
2026-05-03 15:28:40,867 INFO ehr_pipeline.runtime:   stage8_review done in 99.10s
2026-05-03 15:28:40,867 INFO ehr_pipeline.pipeline:   applied revision: 'Other findings include rapid Afib [E:note:row514701:7], tota' → 'Other findings include tachycardia (HR 130-150) [E:note:row5'
2026-05-03 15:28:40,868 INFO ehr_pipeline.pipeline:   applied revision: 'and progressive metabolic acidosis [E:cond:12].' → 'and acidosis [E:cond:12].'
2026-05-03 15:28:40,868 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/summary_revised.md
2026-05-03 15:28:40,868 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:28:40,870 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/check_report_revised.json
2026-05-03 15:28:40,870 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:28:40,875 INFO ehr_pipeline.pipeline: Saved input note (1851 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/input_note.txt
2026-05-03 15:28:40,876 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-27022-196712-355983
2026-05-03 15:28:40,878 INFO ehr_pipeline.stages.s1_evidence:   wrote 116 evidence items (95 structured, 21 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/evidence_store.json
2026-05-03 15:28:40,878 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:28:40,878 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   436.24 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    63.09 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    69.16 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    17.75 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    99.10 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   685.35 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (1043 / 2908 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-49496-112342-514701/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-27022-196712-355983
  note_chars=1851  gold_concepts=4
==================================================================

2026-05-03 15:30:01,403 INFO ehr_pipeline.stages.s2_extract:   extracted 33 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/claims.json
2026-05-03 15:30:01,405 INFO ehr_pipeline.runtime:   stage2_extract done in 80.53s
2026-05-03 15:30:01,405 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 33 claims
2026-05-03 15:31:57,290 INFO ehr_pipeline.stages.s3_verify:   {'verified': 16, 'contradicted': 0, 'unsupported': 17} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/verifications.json
2026-05-03 15:31:57,292 INFO ehr_pipeline.runtime:   stage3_verify done in 115.89s
2026-05-03 15:31:57,293 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:31:57,294 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:31:57,296 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 53, 'medications': 2, 'labs': 0, 'vitals': 3, 'plan': 0}
2026-05-03 15:31:57,296 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:31:57,297 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:32:21,826 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/patient_summary.md (1488 chars, FK grade=6.28, in_band=False)
2026-05-03 15:32:21,827 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 24.53s
2026-05-03 15:32:21,827 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:32:33,808 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/summary.md (742 chars, ratio=0.40, target=0.20-0.30, in_band=False)
2026-05-03 15:32:33,809 INFO ehr_pipeline.runtime:   stage6_summarize done in 11.98s
2026-05-03 15:32:33,812 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:32:33,815 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/check_report.json
2026-05-03 15:32:33,815 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:32:33,818 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:32:54,765 INFO ehr_pipeline.stages.s8_review:   concerns=4 recommended_revisions=3 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/review.json
2026-05-03 15:32:54,767 INFO ehr_pipeline.runtime:   stage8_review done in 20.95s
2026-05-03 15:32:54,767 INFO ehr_pipeline.pipeline:   applied revision: 'Biliary cirrhosis [E:cond:1][E:cond:2], PSC [E:note:row35598' → 'Biliary cirrhosis [E:cond:1][E:cond:2].'
2026-05-03 15:32:54,768 INFO ehr_pipeline.pipeline:   applied revision: 'Bleeding esophageal varices [E:cond:5][E:cond:6] with meleno' → 'Esophageal varices with bleeding [E:cond:5][E:cond:6].'
2026-05-03 15:32:54,768 INFO ehr_pipeline.pipeline:   applied revision: 'CHF [E:cond:29][E:cond:30], coronary atherosclerosis [E:cond' → 'Congestive heart failure [E:cond:29][E:cond:30].'
2026-05-03 15:32:54,768 INFO ehr_pipeline.pipeline: Wrote revised summary (3 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/summary_revised.md
2026-05-03 15:32:54,769 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:32:54,769 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/check_report_revised.json
2026-05-03 15:32:54,770 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:32:54,774 INFO ehr_pipeline.pipeline: Saved input note (2534 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/input_note.txt
2026-05-03 15:32:54,774 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-41125-127965-574617
2026-05-03 15:32:54,776 INFO ehr_pipeline.stages.s1_evidence:   wrote 60 evidence items (17 structured, 43 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/evidence_store.json
2026-05-03 15:32:54,776 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:32:54,777 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    80.53 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   115.89 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    24.53 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    11.98 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    20.95 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   253.88 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.40  (742 / 1851 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=3  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-27022-196712-355983/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-41125-127965-574617
  note_chars=2534  gold_concepts=8
==================================================================

2026-05-03 15:34:37,169 INFO ehr_pipeline.stages.s2_extract:   extracted 47 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/claims.json
2026-05-03 15:34:37,170 INFO ehr_pipeline.runtime:   stage2_extract done in 102.39s
2026-05-03 15:34:37,171 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 47 claims
2026-05-03 15:36:03,418 INFO ehr_pipeline.stages.s3_verify:   {'verified': 36, 'contradicted': 0, 'unsupported': 11} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/verifications.json
2026-05-03 15:36:03,419 INFO ehr_pipeline.runtime:   stage3_verify done in 86.25s
2026-05-03 15:36:03,419 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:36:03,420 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:36:03,421 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 27, 'medications': 8, 'labs': 8, 'vitals': 4, 'plan': 1}
2026-05-03 15:36:03,421 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:36:03,422 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:36:19,099 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/patient_summary.md (1809 chars, FK grade=5.68, in_band=False)
2026-05-03 15:36:19,100 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 15.68s
2026-05-03 15:36:19,100 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:37:02,659 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/summary.md (1341 chars, ratio=0.53, target=0.20-0.30, in_band=False)
2026-05-03 15:37:02,659 INFO ehr_pipeline.runtime:   stage6_summarize done in 43.56s
2026-05-03 15:37:02,660 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:37:02,661 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=17 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/check_report.json
2026-05-03 15:37:02,661 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:37:02,662 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:37:05,235 INFO ehr_pipeline.stages.s8_review:   concerns=0 recommended_revisions=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/review.json
2026-05-03 15:37:05,240 INFO ehr_pipeline.runtime:   stage8_review done in 2.58s
2026-05-03 15:37:05,246 INFO ehr_pipeline.pipeline: No recommended revisions from Stage 8; original summary is final.
2026-05-03 15:37:05,251 INFO ehr_pipeline.pipeline: Saved input note (2122 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/input_note.txt
2026-05-03 15:37:05,272 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-60106-136013-660723
2026-05-03 15:37:05,290 INFO ehr_pipeline.stages.s1_evidence:   wrote 47 evidence items (32 structured, 15 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/evidence_store.json
2026-05-03 15:37:05,294 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.02s
2026-05-03 15:37:05,299 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   102.39 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    86.25 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    15.68 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    43.56 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     2.58 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   250.46 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.53  (1341 / 2534 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-41125-127965-574617/summary.md
  revised summ. : (none — no applicable revisions)
  benchmarking  : using original summary for metrics

==================================================================
  CASE: mimic-60106-136013-660723
  note_chars=2122  gold_concepts=7
==================================================================

2026-05-03 15:38:54,958 INFO ehr_pipeline.stages.s2_extract:   extracted 49 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/claims.json
2026-05-03 15:38:54,959 INFO ehr_pipeline.runtime:   stage2_extract done in 109.66s
2026-05-03 15:38:54,960 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 49 claims
2026-05-03 15:42:19,713 INFO ehr_pipeline.stages.s3_verify:   {'verified': 22, 'contradicted': 0, 'unsupported': 27} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/verifications.json
2026-05-03 15:42:19,714 INFO ehr_pipeline.runtime:   stage3_verify done in 204.75s
2026-05-03 15:42:19,714 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:42:19,715 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:42:19,716 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 40, 'medications': 3, 'labs': 0, 'vitals': 7, 'plan': 3}
2026-05-03 15:42:19,716 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:42:19,717 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:42:52,663 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/patient_summary.md (1806 chars, FK grade=6.35, in_band=False)
2026-05-03 15:42:52,665 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 32.95s
2026-05-03 15:42:52,665 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:43:09,683 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/summary.md (957 chars, ratio=0.45, target=0.20-0.30, in_band=False)
2026-05-03 15:43:09,684 INFO ehr_pipeline.runtime:   stage6_summarize done in 17.02s
2026-05-03 15:43:09,685 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:43:09,686 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/check_report.json
2026-05-03 15:43:09,686 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:43:09,686 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:43:15,069 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/review.json
2026-05-03 15:43:15,069 INFO ehr_pipeline.runtime:   stage8_review done in 5.38s
2026-05-03 15:43:15,070 INFO ehr_pipeline.pipeline:   applied revision: 'Tube feed on hold pending morning nerve biopsy [E:note:row66' → 'Tube feed on hold pending possible morning nerve biopsy [E:n'
2026-05-03 15:43:15,071 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/summary_revised.md
2026-05-03 15:43:15,071 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:43:15,072 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/check_report_revised.json
2026-05-03 15:43:15,073 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:43:15,076 INFO ehr_pipeline.pipeline: Saved input note (2784 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/input_note.txt
2026-05-03 15:43:15,076 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-76541-139921-737066
2026-05-03 15:43:15,078 INFO ehr_pipeline.stages.s1_evidence:   wrote 46 evidence items (38 structured, 8 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/evidence_store.json
2026-05-03 15:43:15,078 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:43:15,078 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.02 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   109.66 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   204.75 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    32.95 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    17.02 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │     5.38 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   369.79 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.45  (957 / 2122 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-60106-136013-660723/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-76541-139921-737066
  note_chars=2784  gold_concepts=9
==================================================================

2026-05-03 15:44:21,311 INFO ehr_pipeline.stages.s2_extract:   extracted 29 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/claims.json
2026-05-03 15:44:21,312 INFO ehr_pipeline.runtime:   stage2_extract done in 66.23s
2026-05-03 15:44:21,312 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 29 claims
2026-05-03 15:44:55,076 INFO ehr_pipeline.stages.s3_verify:   {'verified': 11, 'contradicted': 0, 'unsupported': 18} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/verifications.json
2026-05-03 15:44:55,076 INFO ehr_pipeline.runtime:   stage3_verify done in 33.76s
2026-05-03 15:44:55,077 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:44:55,078 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:44:55,079 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 42, 'medications': 2, 'labs': 0, 'vitals': 0, 'plan': 0}
2026-05-03 15:44:55,079 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:44:55,080 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:45:13,870 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/patient_summary.md (1519 chars, FK grade=7.09, in_band=True)
2026-05-03 15:45:13,870 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 18.79s
2026-05-03 15:45:13,871 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:45:54,757 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/summary.md (1003 chars, ratio=0.36, target=0.20-0.30, in_band=False)
2026-05-03 15:45:54,757 INFO ehr_pipeline.runtime:   stage6_summarize done in 40.89s
2026-05-03 15:45:54,758 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:45:54,760 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/check_report.json
2026-05-03 15:45:54,760 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:45:54,760 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:46:52,293 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/review.json
2026-05-03 15:46:52,294 INFO ehr_pipeline.runtime:   stage8_review done in 57.53s
2026-05-03 15:46:52,294 INFO ehr_pipeline.pipeline:   applied revision: 'Acute alcoholic hepatitis, alcoholic cirrhosis, and hepatic ' → 'Acute alcoholic hepatitis and hepatic encephalopathy [E:cond'
2026-05-03 15:46:52,295 INFO ehr_pipeline.pipeline:   applied revision: 'Other issues include ascites, UTI, coagulation defects, prot' → 'Other issues include ascites, UTI, coagulation defects, prot'
2026-05-03 15:46:52,295 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/summary_revised.md
2026-05-03 15:46:52,296 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:46:52,296 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=12 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/check_report_revised.json
2026-05-03 15:46:52,297 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:46:52,301 INFO ehr_pipeline.pipeline: Saved input note (2976 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/input_note.txt
2026-05-03 15:46:52,301 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-83607-156758-631634
2026-05-03 15:46:52,303 INFO ehr_pipeline.stages.s1_evidence:   wrote 63 evidence items (42 structured, 21 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/evidence_store.json
2026-05-03 15:46:52,303 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:46:52,303 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    66.23 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    33.76 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    18.79 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    40.89 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    57.53 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   217.21 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.36  (1003 / 2784 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-76541-139921-737066/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-83607-156758-631634
  note_chars=2976  gold_concepts=5
==================================================================

2026-05-03 15:48:39,818 INFO ehr_pipeline.stages.s2_extract:   extracted 51 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/claims.json
2026-05-03 15:48:39,823 INFO ehr_pipeline.runtime:   stage2_extract done in 107.52s
2026-05-03 15:48:39,824 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 51 claims
2026-05-03 15:51:38,927 INFO ehr_pipeline.stages.s3_verify:   {'verified': 22, 'contradicted': 0, 'unsupported': 29} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/verifications.json
2026-05-03 15:51:38,928 INFO ehr_pipeline.runtime:   stage3_verify done in 179.10s
2026-05-03 15:51:38,928 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:51:38,929 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:51:38,931 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 52, 'medications': 1, 'labs': 2, 'vitals': 5, 'plan': 0}
2026-05-03 15:51:38,932 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:51:38,932 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:51:51,608 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/patient_summary.md (1351 chars, FK grade=7.69, in_band=True)
2026-05-03 15:51:51,609 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 12.68s
2026-05-03 15:51:51,609 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:52:02,580 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/summary.md (1048 chars, ratio=0.35, target=0.20-0.30, in_band=False)
2026-05-03 15:52:02,580 INFO ehr_pipeline.runtime:   stage6_summarize done in 10.97s
2026-05-03 15:52:02,581 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:52:02,583 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/check_report.json
2026-05-03 15:52:02,583 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 15:52:02,583 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:52:46,954 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/review.json
2026-05-03 15:52:46,955 INFO ehr_pipeline.runtime:   stage8_review done in 44.37s
2026-05-03 15:52:46,955 INFO ehr_pipeline.pipeline:   applied revision: 'Other acute issues include acute respiratory failure [E:cond' → 'Other acute issues include acute respiratory failure [E:cond'
2026-05-03 15:52:46,956 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/summary_revised.md
2026-05-03 15:52:46,956 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:52:46,957 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/check_report_revised.json
2026-05-03 15:52:46,957 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:52:46,962 INFO ehr_pipeline.pipeline: Saved input note (865 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/input_note.txt
2026-05-03 15:52:46,963 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-25326-191645-386337
2026-05-03 15:52:46,965 INFO ehr_pipeline.stages.s1_evidence:   wrote 84 evidence items (81 structured, 3 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/evidence_store.json
2026-05-03 15:52:46,965 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:52:46,965 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   107.52 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   179.10 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    12.68 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    10.97 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    44.37 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   354.65 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.35  (1048 / 2976 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=1)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-83607-156758-631634/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-25326-191645-386337
  note_chars=865  gold_concepts=10
==================================================================

2026-05-03 15:54:37,098 INFO ehr_pipeline.stages.s2_extract:   extracted 23 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/claims.json
2026-05-03 15:54:37,100 INFO ehr_pipeline.runtime:   stage2_extract done in 110.13s
2026-05-03 15:54:37,100 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 23 claims
2026-05-03 15:55:17,602 INFO ehr_pipeline.stages.s3_verify:   {'verified': 7, 'contradicted': 1, 'unsupported': 15} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/verifications.json
2026-05-03 15:55:17,602 INFO ehr_pipeline.runtime:   stage3_verify done in 40.50s
2026-05-03 15:55:17,602 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 15:55:17,604 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 15:55:17,605 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 43, 'medications': 0, 'labs': 0, 'vitals': 2, 'plan': 0}
2026-05-03 15:55:17,605 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 15:55:17,605 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 15:55:33,643 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/patient_summary.md (1367 chars, FK grade=5.60, in_band=False)
2026-05-03 15:55:33,645 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 16.04s
2026-05-03 15:55:33,645 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 15:55:38,561 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/summary.md (353 chars, ratio=0.41, target=0.20-0.30, in_band=False)
2026-05-03 15:55:38,563 INFO ehr_pipeline.runtime:   stage6_summarize done in 4.92s
2026-05-03 15:55:38,569 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:55:38,573 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/check_report.json
2026-05-03 15:55:38,576 INFO ehr_pipeline.runtime:   stage7_check done in 0.01s
2026-05-03 15:55:38,580 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 15:55:51,401 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/review.json
2026-05-03 15:55:51,405 INFO ehr_pipeline.runtime:   stage8_review done in 12.83s
2026-05-03 15:55:51,406 INFO ehr_pipeline.pipeline:   applied revision: 'Severe sepsis [E:cond:5][E:cond:6], MSSA septicemia [E:cond:' → 'Severe sepsis [E:cond:5][E:cond:6], MSSA septicemia [E:cond:'
2026-05-03 15:55:51,407 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/summary_revised.md
2026-05-03 15:55:51,407 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 15:55:51,408 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=5 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/check_report_revised.json
2026-05-03 15:55:51,408 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 15:55:51,414 INFO ehr_pipeline.pipeline: Saved input note (3841 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/input_note.txt
2026-05-03 15:55:51,415 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-56635-192782-481041
2026-05-03 15:55:51,417 INFO ehr_pipeline.stages.s1_evidence:   wrote 96 evidence items (44 structured, 52 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/evidence_store.json
2026-05-03 15:55:51,417 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 15:55:51,417 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   110.13 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │    40.50 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    16.04 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     4.92 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.01 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    12.83 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   184.43 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.41  (353 / 865 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : FAIL ✗ (high-severity concern)  (high=1  medium=0  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-25326-191645-386337/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-56635-192782-481041
  note_chars=3841  gold_concepts=15
==================================================================

2026-05-03 15:57:55,137 INFO ehr_pipeline.stages.s2_extract:   extracted 57 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/claims.json
2026-05-03 15:57:55,143 INFO ehr_pipeline.runtime:   stage2_extract done in 123.73s
2026-05-03 15:57:55,144 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 57 claims
2026-05-03 16:00:21,224 INFO ehr_pipeline.stages.s3_verify:   {'verified': 35, 'contradicted': 0, 'unsupported': 22} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/verifications.json
2026-05-03 16:00:21,225 INFO ehr_pipeline.runtime:   stage3_verify done in 146.08s
2026-05-03 16:00:21,225 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 16:00:21,226 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 16:00:21,227 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 62, 'medications': 6, 'labs': 0, 'vitals': 7, 'plan': 1}
2026-05-03 16:00:21,227 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 16:00:21,228 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 16:00:39,050 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/patient_summary.md (1729 chars, FK grade=6.57, in_band=False)
2026-05-03 16:00:39,050 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 17.82s
2026-05-03 16:00:39,051 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 16:01:20,776 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/summary.md (1467 chars, ratio=0.38, target=0.20-0.30, in_band=False)
2026-05-03 16:01:20,779 INFO ehr_pipeline.runtime:   stage6_summarize done in 41.73s
2026-05-03 16:01:20,781 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 16:01:20,783 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/check_report.json
2026-05-03 16:01:20,783 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 16:01:20,783 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 16:01:48,012 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/review.json
2026-05-03 16:01:48,012 INFO ehr_pipeline.runtime:   stage8_review done in 27.23s
2026-05-03 16:01:48,013 INFO ehr_pipeline.pipeline:   applied revision: 'Additional findings include R groin hematoma [E:cond:7], gen' → 'Additional findings include hematoma complicating a procedur'
2026-05-03 16:01:48,013 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/summary_revised.md
2026-05-03 16:01:48,013 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 16:01:48,015 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=10 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/check_report_revised.json
2026-05-03 16:01:48,015 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 16:01:48,018 INFO ehr_pipeline.pipeline: Saved input note (1297 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/input_note.txt
2026-05-03 16:01:48,018 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-68135-163192-486433
2026-05-03 16:01:48,020 INFO ehr_pipeline.stages.s1_evidence:   wrote 54 evidence items (36 structured, 18 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/evidence_store.json
2026-05-03 16:01:48,020 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.00s
2026-05-03 16:01:48,020 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   123.73 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   146.08 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    17.82 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    41.73 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    27.23 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   356.59 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.38  (1467 / 3841 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-56635-192782-481041/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-68135-163192-486433
  note_chars=1297  gold_concepts=3
==================================================================

2026-05-03 16:03:09,736 INFO ehr_pipeline.stages.s2_extract:   extracted 22 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/claims.json
2026-05-03 16:03:09,737 INFO ehr_pipeline.runtime:   stage2_extract done in 81.72s
2026-05-03 16:03:09,738 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 22 claims
2026-05-03 16:05:50,547 INFO ehr_pipeline.stages.s3_verify:   {'verified': 12, 'contradicted': 0, 'unsupported': 10} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/verifications.json
2026-05-03 16:05:50,548 INFO ehr_pipeline.runtime:   stage3_verify done in 160.81s
2026-05-03 16:05:50,548 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 16:05:50,550 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 16:05:50,550 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 37, 'medications': 0, 'labs': 3, 'vitals': 2, 'plan': 2}
2026-05-03 16:05:50,551 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 16:05:50,551 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 16:06:04,829 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/patient_summary.md (1494 chars, FK grade=6.92, in_band=False)
2026-05-03 16:06:04,830 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 14.28s
2026-05-03 16:06:04,830 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 16:06:12,837 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/summary.md (552 chars, ratio=0.43, target=0.20-0.30, in_band=False)
2026-05-03 16:06:12,838 INFO ehr_pipeline.runtime:   stage6_summarize done in 8.01s
2026-05-03 16:06:12,839 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 16:06:12,840 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=9 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/check_report.json
2026-05-03 16:06:12,840 INFO ehr_pipeline.runtime:   stage7_check done in 0.00s
2026-05-03 16:06:12,841 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 16:07:41,325 INFO ehr_pipeline.stages.s8_review:   concerns=2 recommended_revisions=2 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/review.json
2026-05-03 16:07:41,327 INFO ehr_pipeline.runtime:   stage8_review done in 88.49s
2026-05-03 16:07:41,327 INFO ehr_pipeline.pipeline:   applied revision: 'VAP, acute respiratory failure, and respirator dependence [E' → 'VAP and respirator dependence [E:cond:7][E:cond:11].'
2026-05-03 16:07:41,327 INFO ehr_pipeline.pipeline:   applied revision: 'DM type II [E:cond:24].' → ''
2026-05-03 16:07:41,328 INFO ehr_pipeline.pipeline: Wrote revised summary (2 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/summary_revised.md
2026-05-03 16:07:41,329 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 16:07:41,331 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=8 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/check_report_revised.json
2026-05-03 16:07:41,331 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0
2026-05-03 16:07:41,403 INFO ehr_pipeline.pipeline: Saved input note (6460 chars) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/input_note.txt
2026-05-03 16:07:41,443 INFO ehr_pipeline.stages.s1_evidence: Stage 1: building evidence store for case mimic-9461-156692-597
2026-05-03 16:07:41,450 INFO ehr_pipeline.stages.s1_evidence:   wrote 90 evidence items (20 structured, 70 note sentences) to /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/evidence_store.json
2026-05-03 16:07:41,453 INFO ehr_pipeline.runtime:   stage1_evidence done in 0.01s
2026-05-03 16:07:41,454 INFO ehr_pipeline.stages.s2_extract: Stage 2: extracting claims from notes

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.00 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │    81.72 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   160.81 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    14.28 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │     8.01 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.00 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    88.49 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   353.30 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.43  (552 / 1297 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=2  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-68135-163192-486433/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  CASE: mimic-9461-156692-597
  note_chars=6460  gold_concepts=12
==================================================================

2026-05-03 16:09:57,870 INFO ehr_pipeline.stages.s2_extract:   extracted 53 claims, wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/claims.json
2026-05-03 16:09:57,872 INFO ehr_pipeline.runtime:   stage2_extract done in 136.42s
2026-05-03 16:09:57,872 INFO ehr_pipeline.stages.s3_verify: Stage 3: verifying 53 claims
2026-05-03 16:13:13,489 INFO ehr_pipeline.stages.s3_verify:   {'verified': 34, 'contradicted': 0, 'unsupported': 19} -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/verifications.json
2026-05-03 16:13:13,490 INFO ehr_pipeline.runtime:   stage3_verify done in 195.62s
2026-05-03 16:13:13,491 INFO ehr_pipeline.verification: Stage 4 (context agent) disabled by caller; using raw verifications
2026-05-03 16:13:13,492 INFO ehr_pipeline.stages.s5_fact_sheet: Stage 5: compiling verified fact sheet
2026-05-03 16:13:13,493 INFO ehr_pipeline.stages.s5_fact_sheet:   fact sheet sections: {'hpi': 0, 'active_problems': 32, 'medications': 9, 'labs': 5, 'vitals': 3, 'plan': 0}
2026-05-03 16:13:13,493 INFO ehr_pipeline.runtime:   stage5_fact_sheet done in 0.00s
2026-05-03 16:13:13,494 INFO ehr_pipeline.stages.s9_patient_summary: Stage 9: generating patient summary (target FK grade 7-8)
2026-05-03 16:13:53,363 INFO ehr_pipeline.stages.s9_patient_summary:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/patient_summary.md (1805 chars, FK grade=7.71, in_band=True)
2026-05-03 16:13:53,365 INFO ehr_pipeline.runtime:   stage9_patient_summary done in 39.87s
2026-05-03 16:13:53,365 INFO ehr_pipeline.stages.s6_summarize: Stage 6: generating summary markdown
2026-05-03 16:14:10,812 INFO ehr_pipeline.stages.s6_summarize:   wrote /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/summary.md (2452 chars, ratio=0.38, target=0.20-0.30, in_band=False)
2026-05-03 16:14:10,854 INFO ehr_pipeline.runtime:   stage6_summarize done in 17.49s
2026-05-03 16:14:10,909 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 16:14:10,948 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=19 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/check_report.json
2026-05-03 16:14:11,008 INFO ehr_pipeline.runtime:   stage7_check done in 0.10s
2026-05-03 16:14:11,046 INFO ehr_pipeline.stages.s8_review: Stage 8: final LLM review
2026-05-03 16:14:53,975 INFO ehr_pipeline.stages.s8_review:   concerns=1 recommended_revisions=1 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/review.json
2026-05-03 16:14:53,976 INFO ehr_pipeline.runtime:   stage8_review done in 42.93s
2026-05-03 16:14:53,977 INFO ehr_pipeline.pipeline:   applied revision: 'Patient underwent angioplasty with two distal stent placemen' → 'Patient underwent angioplasty [E:note:row597:46], involving '
2026-05-03 16:14:53,977 INFO ehr_pipeline.pipeline: Wrote revised summary (1 revision(s) applied) -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/summary_revised.md
2026-05-03 16:14:53,978 INFO ehr_pipeline.stages.s7_check: Stage 7: deterministic check
2026-05-03 16:14:53,980 INFO ehr_pipeline.stages.s7_check:   passed=True sentences=19 violations=0 -> /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/check_report_revised.json
2026-05-03 16:14:53,980 INFO ehr_pipeline.pipeline:   revised summary check: passed=True violations=0

  ┌────────────────────────────────────────────────────────────┬──────────┬────────┐
  │ Stage                                                      │  Time(s) │ Status │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ S1  Evidence store      [deterministic]                    │     0.01 │ ok     │
  │ S2  Claim extraction    [LLM: gemma4:31b]                  │   136.42 │ ok     │
  │ S3  Claim verification  [LLM: gemma4:31b]                  │   195.62 │ ok     │
  │ S4  Context agent       [LLM: gemma4:31b]                  │     0.00 │ SKIP   │
  │ S5  Fact sheet          [deterministic]                    │     0.00 │ ok     │
  │ stage9_patient_summary                                     │    39.87 │ ok     │
  │ S6  Summary generation  [LLM: gemma4:31b]                  │    17.49 │ ok     │
  │ S7  Deterministic check [deterministic]                    │     0.10 │ ok     │
  │ S8  Final LLM review    [LLM: gemma4:31b]                  │    42.93 │ ok     │
  ├────────────────────────────────────────────────────────────┼──────────┼────────┤
  │ TOTAL                                                      │   432.44 │        │
  └────────────────────────────────────────────────────────────┴──────────┴────────┘
  compression: 0.38  (2452 / 6460 chars)  [OUT OF BAND ✗]
  S7 det. check : PASS ✓
  S8 LLM review : PASS ✓  (high=0  medium=1  low=0)
  input note    : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/input_note.txt
  summary       : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/summary.md
  revised summ. : /Users/natejly/Documents/GitHub/LLMS/outputs/mimic-9461-156692-597/summary_revised.md  [check PASS ✓]
  benchmarking  : using revised summary for metrics

==================================================================
  DONE: 100 cases  (0 cached, 100 fresh)
==================================================================

## Recover results from cache (run this if the kernel crashed)

If the benchmark loop was interrupted, run the cell below to reload all
completed cases from their cached `audit.json` outputs. It rebuilds the
`results` list so the scoring cells can proceed normally.

In [19]:
results = []
recovered = 0
skipped = 0
for case in sampled:
    out_dir = pipeline_config.output_dir(case.case_id)
    cached = _load_cached_result(case, out_dir)
    if cached is not None:
        results.append(cached)
        recovered += 1
    else:
        skipped += 1

print(f"Recovered {recovered} cached results, {skipped} cases have no cached output.")
if results:
    print(f"First case: {results[0]['case_id']}  compression={results[0]['compression_ratio']:.2f}")
print("Run the scoring cells below to compute metrics.")

Recovered 100 cached results, 0 cases have no cached output.
First case: mimic-72907-165405-520384  compression=0.42
Run the scoring cells below to compute metrics.

## Inspect one generated summary vs reference

In [20]:
if results:
    r = results[0]
    print(f"--- {r['case_id']} ---\n")
    print(
        f"compression: {r['summary_chars']}/{r['note_chars']} = {r['compression_ratio']:.2f}"
        f" (target {SUMMARY_MIN_RATIO:.2f}-{SUMMARY_MAX_RATIO:.2f}, in_band={r['compression_in_band']})\n"
    )
    print("=== REFERENCE ===\n")
    print(r["reference"])
    print("\n=== PREDICTION ===\n")
    print(r["prediction"][:3000] or "(empty)")

--- mimic-72907-165405-520384 ---

compression: 1445/3404 = 0.42 (target 0.20-0.30, in_band=False)

=== REFERENCE ===

## HPI
77.0-year-old female.
## Active Problems
- Abdominal Pain.
- Sepsis.
- Septicemia.
- Pain.
- Grimaces.
- Respiratory Failure.
- Kidney Failure.
- Atrial Fibrillation.
## EHR Diagnoses
- Other postoperative infection.
- Disseminated candidiasis.
- Severe sepsis.
- Septic shock.
- Other suppurative peritonitis.
- Acute and subacute necrosis of liver.
- Acute kidney failure with lesion of tubular necrosis.
- Necrotizing fasciitis.
- Acute vascular insufficiency of intestine.
- None.
- Acidosis.
- Acute salpingitis and oophoritis.
- Candidiasis of other urogenital sites.
- Acute inflammatory diseases of uterus, except cervix.
- Unspecified essential hypertension.
- Depressive disorder, not elsewhere classified.
- Unspecified acquired hypothyroidism.
- Other specified surgical operations and procedures causing abnormal patient reaction, or later complication, without mention of misadventure at time of operation.
## Procedures
- Open and other left hemicolectomy.
- Other partial resection of small intestine.
- Temporary ileostomy.
- Open and other resection of transverse colon.
- Open and other sigmoidectomy.
- Open and other right hemicolectomy.
- Other and unspecified subtotal abdominal hysterectomy.
- Other removal of both ovaries and tubes at same operative episode.
- Venous catheterization, not elsewhere classified.
- Arterial catheterization.
- Continuous invasive mechanical ventilation for 96 consecutive hours or more.
- Hemodialysis.
- Venous catheterization for renal dialysis.
- Parenteral infusion of concentrated nutritional substances.
- Other gastrostomy.
- Other enterostomy.
## Disposition
Patient expired during this admission.


=== PREDICTION ===

## HPI
_Not documented._

## Active Problems
Patient presents with severe sepsis [E:cond:3], septic shock [E:cond:4], and disseminated candidiasis [E:cond:2]. Complications include other postoperative infection [E:cond:1], other suppurative peritonitis [E:cond:5], necrotizing fasciitis [E:cond:8], and acute vascular insufficiency of intestine [E:cond:9]. Organ dysfunction is noted with acute kidney failure with tubular necrosis [E:cond:7], acute and subacute liver necrosis [E:cond:6], and acidosis [E:cond:11]. Additional diagnoses include acute salpingitis and oophoritis [E:cond:12], candidiasis of other urogenital sites [E:cond:13], and acute inflammatory diseases of uterus [E:cond:14]. Chronic conditions include essential hypertension [E:cond:15]. _Not documented._

## Medications
Amioderone gtt ongoing at 0.5mg/min [E:note:row520384:11]. Levophed has been discontinued [E:note:row520384:7].

## Labs
_Not documented._

## Plan
_Not documented._

## Compute ROUGE and entity metrics per case

In [23]:
rows = []
for r in results:
    prediction = strip_citations_for_metrics(r["prediction"])
    if not prediction.strip():
        continue
    note_chars = max(int(r.get("note_chars", 0)), 1)
    summary_chars = len(prediction)
    compression_ratio = summary_chars / note_chars
    row = {
        "case_id": r["case_id"],
        "check_passed": r["check_passed"],
        "context_agent_on": r["context_agent_on"],
        "compression_ratio": compression_ratio,
        "compression_in_band": SUMMARY_MIN_RATIO <= compression_ratio <= SUMMARY_MAX_RATIO,
        "total_seconds": r["total_seconds"],
    }
    row.update(metrics.rouge_scores(prediction, r["reference"]))
    row.update(metrics.entity_recall_precision(
        prediction=prediction,
        reference=r["reference"],
        gold_entities=r["gold_entities"],
    ))
    # Stage 9 — patient summary readability (Flesch-Kincaid grade target 7-8).
    # Re-score from the saved markdown so the metric matches what the UI shows.
    patient_md = r.get("patient_summary", "")
    if patient_md.strip():
        fk = metrics.flesch_kincaid_grade(patient_md)
        row["patient_fk_grade"] = fk["fk_grade"]
        row["patient_fk_in_target"] = fk["fk_in_target_band"]
        row["patient_fk_words"] = fk["fk_words"]
        row["patient_fk_sentences"] = fk["fk_sentences"]
        row["patient_chars"] = r.get("patient_chars", len(patient_md))
    else:
        row["patient_fk_grade"] = None
        row["patient_fk_in_target"] = False
        row["patient_fk_words"] = 0
        row["patient_fk_sentences"] = 0
        row["patient_chars"] = 0
    rows.append(row)

rouge_df = pd.DataFrame(rows)
rouge_df

2026-05-03 16:26:59,931 INFO absl: Using default tokenizer.
2026-05-03 16:26:59,990 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,020 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,025 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,037 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,060 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,070 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,077 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,081 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,090 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,103 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,110 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,113 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,121 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,127 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,131 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,144 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,149 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,166 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,170 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,175 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,180 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,188 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,194 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,199 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,207 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,242 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,252 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,259 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,268 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,273 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,278 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,301 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,326 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,330 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,339 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,344 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,352 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,359 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,364 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,373 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,377 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,383 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,386 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,394 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,404 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,409 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,413 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,429 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,434 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,445 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,454 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,456 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,461 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,469 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,476 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,483 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,486 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,490 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,495 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,499 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,504 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,509 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,515 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,520 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,530 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,542 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,549 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,556 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,565 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,578 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,606 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,611 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,619 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,647 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,653 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,661 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,668 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,676 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,680 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,684 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,689 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,701 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,706 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,713 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,720 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,730 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,743 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,766 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,771 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,784 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,790 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,798 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,803 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,808 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,813 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,821 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,828 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,837 INFO absl: Using default tokenizer.
2026-05-03 16:27:00,842 INFO absl: Using default tokenizer.

,case_id,check_passed,context_agent_on,compression_ratio,compression_in_band,total_seconds,rouge1_f,rouge2_f,rougeL_f,entity_precision,...,entity_f1,entity_tp,entity_fp,entity_fn,entity_gold,patient_fk_grade,patient_fk_in_target,patient_fk_words,patient_fk_sentences,patient_chars
0,mimic-72907-165405-520384,True,False,0.227380,True,266.204719,0.431095,0.234875,0.275618,1.0,...,0.561404,16,0,25,41,7.13,True,166,17,1385
1,mimic-29307-175627-318233,True,False,0.369898,False,270.373864,0.191781,0.055556,0.150685,1.0,...,0.160000,2,0,21,23,6.51,False,177,18,1490
2,mimic-47927-161682-717576,True,False,0.233796,True,407.149022,0.408377,0.201058,0.314136,1.0,...,0.651163,14,0,15,29,5.63,False,187,28,1714
3,mimic-77013-141363-444743,True,False,0.247259,True,294.464266,0.168950,0.055046,0.109589,1.0,...,0.340426,8,0,31,39,8.70,True,216,25,2129
4,mimic-54229-165594-598031,True,False,0.301241,False,231.680493,0.214433,0.062112,0.115464,1.0,...,0.641509,17,0,19,36,6.10,False,205,24,2133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,mimic-83607-156758-631634,True,False,0.232527,True,354.648615,0.284900,0.103152,0.148148,1.0,...,0.566667,17,0,26,43,7.69,True,159,12,1351
96,mimic-25326-191645-386337,True,False,0.263584,True,184.428249,0.066815,0.031320,0.062361,1.0,...,0.235294,6,0,39,45,5.60,False,148,14,1367
97,mimic-56635-192782-481041,True,False,0.255663,True,356.589775,0.353887,0.134771,0.160858,1.0,...,0.515152,17,0,32,49,6.57,False,179,16,1729
98,mimic-68135-163192-486433,True,False,0.252120,True,353.303235,0.198413,0.064000,0.111111,1.0,...,0.307692,6,0,27,33,6.92,False,178,17,1494
99,mimic-9461-156692-597,True,False,0.276006,True,432.437589,0.428571,0.271795,0.239796,1.0,...,0.875000,21,0,6,27,7.71,True,173,25,1805

## BERTScore (batched, downloads `roberta-large` the first time)

In [24]:
non_empty = [r for r in results if strip_citations_for_metrics(r["prediction"]).strip()]
preds = [strip_citations_for_metrics(r["prediction"]) for r in non_empty]
refs = [r["reference"] for r in non_empty]
case_ids = [r["case_id"] for r in non_empty]

if preds:
    bert_rows = metrics.bertscore_batch(preds, refs, model_type=BERTSCORE_MODEL)
    bert_df = pd.DataFrame(bert_rows, index=case_ids)
    bert_df.index.name = "case_id"
    bert_df = bert_df.reset_index()
else:
    bert_df = pd.DataFrame(columns=["case_id", "bertscore_p", "bertscore_r", "bertscore_f1"])

bert_df

2026-05-03 16:27:07,036 INFO httpx: HTTP Request: HEAD https://huggingface.co/roberta-large/resolve/main/config.json "HTTP/1.1 200 OK"
2026-05-03 16:27:07,076 INFO httpx: HTTP Request: HEAD https://huggingface.co/roberta-large/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-05-03 16:27:07,123 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/roberta-large/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-05-03 16:27:07,156 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-large/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-05-03 16:27:07,194 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/roberta-large/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-05-03 16:27:07,229 INFO httpx: HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-large/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-05-03 16:27:07,484 INFO httpx: HTTP Request: HEAD https://huggingface.co/roberta-large/resolve/main/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

                      case_id  bertscore_p  bertscore_r  bertscore_f1
0   mimic-72907-165405-520384     0.834571     0.812012      0.823137
1   mimic-29307-175627-318233     0.818140     0.809801      0.813949
2   mimic-47927-161682-717576     0.852225     0.826957      0.839401
3   mimic-77013-141363-444743     0.787992     0.788629      0.788310
4   mimic-54229-165594-598031     0.798852     0.793593      0.796214
..                        ...          ...          ...           ...
95  mimic-83607-156758-631634     0.825362     0.798174      0.811540
96  mimic-25326-191645-386337     0.825136     0.777330      0.800520
97  mimic-56635-192782-481041     0.822166     0.810080      0.816078
98  mimic-68135-163192-486433     0.839166     0.792648      0.815244
99      mimic-9461-156692-597     0.801054     0.839547      0.819849

[100 rows x 4 columns]

## Combined per-case metrics

In [25]:
if not rouge_df.empty and not bert_df.empty:
    full = rouge_df.merge(bert_df, on="case_id", how="left")
else:
    full = rouge_df.copy()

metric_cols = [c for c in (
    "rouge1_f", "rouge2_f", "rougeL_f",
    "bertscore_p", "bertscore_r", "bertscore_f1",
    "entity_precision", "entity_recall", "entity_f1",
    "compression_ratio",
    "patient_fk_grade",
) if c in full.columns]

display_cols = ["case_id", "check_passed", "context_agent_on", "compression_in_band",
                *metric_cols, "patient_fk_in_target",
                "entity_tp", "entity_fn", "entity_gold", "total_seconds"]
full[[c for c in display_cols if c in full.columns]].round(3)

,case_id,check_passed,context_agent_on,compression_in_band,rouge1_f,rouge2_f,rougeL_f,bertscore_p,bertscore_r,bertscore_f1,entity_precision,entity_recall,entity_f1,compression_ratio,patient_fk_grade,patient_fk_in_target,entity_tp,entity_fn,entity_gold,total_seconds
0,mimic-72907-165405-520384,True,False,True,0.431,0.235,0.276,0.835,0.812,0.823,1.0,0.390,0.561,0.227,7.13,True,16,25,41,266.205
1,mimic-29307-175627-318233,True,False,False,0.192,0.056,0.151,0.818,0.810,0.814,1.0,0.087,0.160,0.370,6.51,False,2,21,23,270.374
2,mimic-47927-161682-717576,True,False,True,0.408,0.201,0.314,0.852,0.827,0.839,1.0,0.483,0.651,0.234,5.63,False,14,15,29,407.149
3,mimic-77013-141363-444743,True,False,True,0.169,0.055,0.110,0.788,0.789,0.788,1.0,0.205,0.340,0.247,8.70,True,8,31,39,294.464
4,mimic-54229-165594-598031,True,False,False,0.214,0.062,0.115,0.799,0.794,0.796,1.0,0.472,0.642,0.301,6.10,False,17,19,36,231.680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,mimic-83607-156758-631634,True,False,True,0.285,0.103,0.148,0.825,0.798,0.812,1.0,0.395,0.567,0.233,7.69,True,17,26,43,354.649
96,mimic-25326-191645-386337,True,False,True,0.067,0.031,0.062,0.825,0.777,0.801,1.0,0.133,0.235,0.264,5.60,False,6,39,45,184.428
97,mimic-56635-192782-481041,True,False,True,0.354,0.135,0.161,0.822,0.810,0.816,1.0,0.347,0.515,0.256,6.57,False,17,32,49,356.590
98,mimic-68135-163192-486433,True,False,True,0.198,0.064,0.111,0.839,0.793,0.815,1.0,0.182,0.308,0.252,6.92,False,6,27,33,353.303
99,mimic-9461-156692-597,True,False,True,0.429,0.272,0.240,0.801,0.840,0.820,1.0,0.778,0.875,0.276,7.71,True,21,6,27,432.438

## Aggregate

In [26]:
if metric_cols:
    agg = full[metric_cols].agg(["mean", "median", "min", "max"]).round(3)
    display(agg)
else:
    print("No metrics computed.")

,rouge1_f,rouge2_f,rougeL_f,bertscore_p,bertscore_r,bertscore_f1,entity_precision,entity_recall,entity_f1,compression_ratio,patient_fk_grade
mean,0.290,0.127,0.187,0.816,0.810,0.813,1.0,0.377,0.523,0.264,7.383
median,0.288,0.114,0.182,0.816,0.805,0.812,1.0,0.360,0.530,0.257,7.355
min,0.018,0.008,0.016,0.761,0.769,0.782,1.0,0.051,0.098,0.131,4.440
max,0.704,0.526,0.456,0.864,0.905,0.884,1.0,0.852,0.920,0.400,11.580

## Save benchmark outputs

In [27]:
import json as _json

report_path = BENCH_DIR / "benchmark_report.json"
report = {
    "models": {k: v for k, v in vars(pipeline_config.MODELS).items()},
    "context_agent_enabled": ENABLE_CONTEXT_AGENT,
    "compression_target": [SUMMARY_MIN_RATIO, SUMMARY_MAX_RATIO],
    "per_case": full.to_dict(orient="records"),
    "aggregate": (full[metric_cols].agg(["mean", "median", "min", "max"]).round(4).to_dict() if metric_cols else {}),
    "num_cases": len(full),
}
report_path.write_text(_json.dumps(report, indent=2, default=str), encoding="utf-8")
print("wrote", report_path)

csv_path = BENCH_DIR / "benchmark_metrics.csv"
full.to_csv(csv_path, index=False)
print("wrote", csv_path)

wrote /Users/natejly/Documents/GitHub/LLMS/outputs/_bench/benchmark_report.json
wrote /Users/natejly/Documents/GitHub/LLMS/outputs/_bench/benchmark_metrics.csv